In [ ]:
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-ul94tuco
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git /tmp/pip-req-build-ul94tuco
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit 3a10805389c07e13e94333e94dcfe9beafce49b0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl==0.3.6)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-dph1zozd/elegantrl_052745fabfea4177b1deb9da15e7b7cc
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-dph1zozd/elegantrl_052745fabfea4177b1deb9da15e7b7cc
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 62bf617fa87cf82b9fbf88307715d93b8ab8ee80
  Preparing metadata (setup.py) ... done
Collecting alpaca-py<0.38,>=0.37 (from finrl==0.3.6)
  Downloading alpaca_py-0.37.0-py3-none-any.whl.metadata (13 kB)
Collecting alpaca-trade-api<4,>=3 (from finrl==0.3.6)
  Downloading alpaca_trade_api-3.2.0-py3-none-any.whl.metadata (29 kB)
Collecting ccxt<4,>=3 (from finrl==0.3.6)
  Downloading ccxt-3.1.60-py2.py3-none-any.whl.metadata (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.7/108.7 kB 5.8 MB/s eta 0:00:00
Collecting exchange-calendars<5,>=4 (from finrl==0.3.6)
  Downloading exchange_calendars-4.9-py3-none-any.whl.metadata (37 kB)
Collecting jqdatasdk<2,>=1 (from finrl==0.3.6)
  Downloading jqdatasdk-1.9.7-py3-none-any.whl.metadata (5.8 kB)
Collecting pyfolio<0.10,>=0.9 (from finrl==0.3.6)
  Downloading pyfolio-0.9.2.tar.gz (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.1/91.1 kB 7.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pyportfolioopt<2,>=1 (from finrl==0.3.6)
  Downloading pyportfolioopt-1.5.6-py3-none-any.whl.metadata (22 kB)
Collecting ray<3,>=2 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading ray-2.42.1-cp311-cp311-manylinux2014_x86_64.whl.metadata (18 kB)
Requirement already satisfied: scikit-learn<2,>=1 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.6) (1.6.1)
Collecting selenium<5,>=4 (from finrl==0.3.6)
  Downloading selenium-4.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting stable-baselines3>=2.0.0a5 (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading stable_baselines3-2.6.0a1-py3-none-any.whl.metadata (4.8 kB)
Collecting stockstats<0.6,>=0.5 (from finrl==0.3.6)
  Downloading stockstats-0.5.4-py2.py3-none-any.whl.metadata (26 kB)
Collecting webdriver-manager<5,>=4 (from finrl==0.3.6)
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting wrds<4,>=3 (from finrl==0.3.6)
  Downloading wrds-3.3.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: yfinance<0.3,>=0.2 in /usr/local/lib/python3.11/dist-packages (from finrl==0.3.6) (0.2.52)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.6) (1.1.0)
Requirement already satisfied: pandas>=1.5.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.6) (2.2.2)
Requirement already satisfied: pydantic<3.0.0,>=2.0.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.6) (2.10.6)
Requirement already satisfied: requests<3.0.0,>=2.30.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.6) (2.32.3)
Collecting sseclient-py<2.0.0,>=1.7.2 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading sseclient_py-1.8.0-py2.py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.11/dist-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.6) (14.2)
Requirement already satisfied: numpy>=1.11.1 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.26.4)
Collecting urllib3<2,>1.24 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 kB 4.5 MB/s eta 0:00:00
Requirement already satisfied: websocket-client<2,>=0.56.0 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (1.8.0)
Collecting websockets>=10.4 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading websockets-10.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting msgpack<2.0.0,>=1.0.3 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading msgpack-1.0.3.tar.gz (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.8/123.8 kB 11.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aiohttp<4,>=3.8.3 in /usr/local/lib/python3.11/dist-packages (from alpaca-trade-api<4,>=3->finrl==0.3.6) (3.11.12)
Collecting PyYAML==6.0.1 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting deprecation==2.1.0 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl==0.3.6) (24.2)
Requirement already satisfied: setuptools>=60.9.0 in /usr/local/lib/python3.11/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (75.1.0)
Requirement already satisfied: certifi>=2018.1.18 in /usr/local/lib/python3.11/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (2025.1.31)
Requirement already satisfied: cryptography>=2.6.1 in /usr/local/lib/python3.11/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (43.0.3)
Collecting aiodns>=1.1.1 (from ccxt<4,>=3->finrl==0.3.6)
  Downloading aiodns-3.2.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: yarl>=1.7.2 in /usr/local/lib/python3.11/dist-packages (from ccxt<4,>=3->finrl==0.3.6) (1.18.3)
Collecting pyluach (from exchange-calendars<5,>=4->finrl==0.3.6)
  Downloading pyluach-2.2.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: toolz in /usr/local/lib/python3.11/dist-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (0.12.1)
Requirement already satisfied: tzdata in /usr/local/lib/python3.11/dist-packages (from exchange-calendars<5,>=4->finrl==0.3.6) (2025.1)
Collecting korean_lunar_calendar (from exchange-calendars<5,>=4->finrl==0.3.6)
  Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (1.17.0)
Requirement already satisfied: SQLAlchemy>=1.2.8 in /usr/local/lib/python3.11/dist-packages (from jqdatasdk<2,>=1->finrl==0.3.6) (2.0.38)
Collecting pymysql>=0.7.6 (from jqdatasdk<2,>=1->finrl==0.3.6)
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Collecting thriftpy2!=0.5.1,>=0.3.9 (from jqdatasdk<2,>=1->finrl==0.3.6)
  Downloading thriftpy2-0.5.2.tar.gz (782 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 782.3/782.3 kB 35.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: ipython>=3.2.3 in /usr/local/lib/python3.11/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (7.34.0)
Requirement already satisfied: matplotlib>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (3.10.0)
Requirement already satisfied: pytz>=2014.10 in /usr/local/lib/python3.11/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (2025.1)
Requirement already satisfied: scipy>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (1.13.1)
Requirement already satisfied: seaborn>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from pyfolio<0.10,>=0.9->finrl==0.3.6) (0.13.2)
Collecting empyrical>=0.5.0 (from pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading empyrical-0.5.5.tar.gz (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.8/52.8 kB 4.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cvxpy>=1.1.19 in /usr/local/lib/python3.11/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.6) (1.6.0)
Collecting ecos<3.0.0,>=2.0.14 (from pyportfolioopt<2,>=1->finrl==0.3.6)
  Downloading ecos-2.0.14-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in /usr/local/lib/python3.11/dist-packages (from pyportfolioopt<2,>=1->finrl==0.3.6) (5.24.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (8.1.8)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (3.17.0)
Requirement already satisfied: jsonschema in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (4.23.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (4.25.6)
Requirement already satisfied: aiosignal in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (1.3.2)
Requirement already satisfied: frozenlist in /usr/local/lib/python3.11/dist-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6) (1.5.0)
Collecting aiohttp-cors (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl.metadata (20 kB)
Collecting colorful (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading colorful-0.5.6-py2.py3-none-any.whl.metadata (16 kB)
Collecting opencensus (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading opencensus-0.11.4-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: prometheus-client>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (0.21.1)
Requirement already satisfied: smart-open in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (7.1.0)
Collecting virtualenv!=20.21.1,>=20.0.24 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading virtualenv-20.29.2-py3-none-any.whl.metadata (4.5 kB)
Collecting py-spy>=0.2.0 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading py_spy-0.4.0-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (16 kB)
Requirement already satisfied: grpcio>=1.42.0 in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (1.70.0)
Collecting tensorboardX>=1.9 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading tensorboardX-2.6.2.2-py2.py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: pyarrow>=9.0.0 in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (17.0.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from ray[default,tune]<3,>=2->finrl==0.3.6) (2024.10.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2,>=1->finrl==0.3.6) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn<2,>=1->finrl==0.3.6) (3.5.0)
Collecting trio~=0.17 (from selenium<5,>=4->finrl==0.3.6)
  Downloading trio-0.29.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.9 (from selenium<5,>=4->finrl==0.3.6)
  Downloading trio_websocket-0.12.0-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: typing_extensions~=4.9 in /usr/local/lib/python3.11/dist-packages (from selenium<5,>=4->finrl==0.3.6) (4.12.2)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (1.0.0)
Requirement already satisfied: torch<3.0,>=2.3 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.5.1+cu124)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.11/dist-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (3.1.1)
Requirement already satisfied: opencv-python in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.11.0.86)
Requirement already satisfied: pygame in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.6.1)
Requirement already satisfied: tensorboard>=2.9.1 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (2.18.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (5.9.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.67.1)
Requirement already satisfied: rich in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (13.9.4)
Requirement already satisfied: ale-py>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (0.10.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.11/dist-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (11.1.0)
Collecting python-dotenv (from webdriver-manager<5,>=4->finrl==0.3.6)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting psycopg2-binary<2.10,>=2.9 (from wrds<4,>=3->finrl==0.3.6)
  Downloading psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (5.3.1)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.3.6)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.13.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.11/dist-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (1.1)
Collecting th (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.6)
  Downloading th-0.4.1-py3-none-any.whl.metadata (3.4 kB)
Collecting pycares>=4.0.0 (from aiodns>=1.1.1->ccxt<4,>=3->finrl==0.3.6)
  Downloading pycares-4.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (2.4.6)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (25.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6) (0.2.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance<0.3,>=0.2->finrl==0.3.6) (2.6)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=2.6.1->ccxt<4,>=3->finrl==0.3.6) (1.17.1)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.11/dist-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.6) (0.6.7.post3)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.6) (0.10.0)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.11/dist-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl==0.3.6) (3.2.7.post2)
Requirement already satisfied: pandas-datareader>=0.2 in /usr/local/lib/python3.11/dist-packages (from empyrical>=0.5.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.10.0)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (0.0.4)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from html5lib>=1.1->yfinance<0.3,>=0.2->finrl==0.3.6) (0.5.1)
Collecting jedi>=0.16 (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (3.0.50)
Requirement already satisfied: pygments in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (2.18.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.11/dist-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl==0.3.6) (4.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=1.4.0->pyfolio<0.10,>=0.9->finrl==0.3.6) (2.8.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.11/dist-packages (from plotly<6.0.0,>=5.0.0->pyportfolioopt<2,>=1->finrl==0.3.6) (9.0.0)

In [ ]:
!pip install quantstats

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

Collecting quantstats
  Downloading QuantStats-0.0.64-py2.py3-none-any.whl.metadata (8.9 kB)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from quantstats) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from quantstats) (1.26.4)
Requirement already satisfied: seaborn>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from quantstats) (0.13.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.11/dist-packages (from quantstats) (3.10.0)
Requirement already satisfied: scipy>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from quantstats) (1.13.1)
Requirement already satisfied: tabulate>=0.8.0 in /usr/local/lib/python3.11/dist-packages (from quantstats) (0.9.0)
Requirement already satisfied: yfinance>=0.1.70 in /usr/local/lib/python3.11/dist-packages (from quantstats) (0.2.52)
Requirement already satisfied: python-dateutil>=2.0 in /usr/local/lib/python3.11/dist-packages (from quantstats) (2.8.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->quantstats) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->quantstats) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->quantstats) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->quantstats) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->quantstats) (24.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->quantstats) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib>=3.0.0->quantstats) (3.2.1)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->quantstats) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=0.24.0->quantstats) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.0->quantstats) (1.17.0)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance>=0.1.70->quantstats) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance>=0.1.70->quantstats) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in /usr/local/lib/python3.11/dist-packages (from yfinance>=0.1.70->quantstats) (5.3.1)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance>=0.1.70->quantstats) (4.3.6)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance>=0.1.70->quantstats) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance>=0.1.70->quantstats) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance>=0.1.70->quantstats) (4.13.3)
Requirement already satisfied: html5lib>=1.1 in /usr/local/lib/python3.11/dist-packages (from yfinance>=0.1.70->quantstats) (1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance>=0.1.70->quantstats) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance>=0.1.70->quantstats) (4.12.2)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from html5lib>=1.1->yfinance>=0.1.70->quantstats) (0.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance>=0.1.70->quantstats) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance>=0.1.70->quantstats) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance>=0.1.70->quantstats) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance>=0.1.70->quantstats) (2025.1.31)
Downloading QuantStats-0.0.64-py2.py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 2.4 MB/s eta 0:00:00
Installing collected packages: quantstats
Successfully installed quantstats-0.0.64

In [ ]:
from finrl.meta.env_portfolio_allocation.env_portfolio import StockPortfolioEnv
from finrl import config
from finrl import config_tickers
from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl.meta.env_portfolio_allocation.env_portfolio import StockPortfolioEnv
from finrl.agents.stablebaselines3.models import DRLAgent
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline,convert_daily_return_to_pyfolio_ts
from finrl.meta.data_processor import DataProcessor
from finrl.meta.data_processors.processor_yahoofinance import YahooFinanceProcessor
import sys
sys.path.append("../FinRL-Library")

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
import pandas as pd

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
import os
if not os.path.exists("./" + config.DATA_SAVE_DIR):
    os.makedirs("./" + config.DATA_SAVE_DIR)
if not os.path.exists("./" + config.TRAINED_MODEL_DIR):
    os.makedirs("./" + config.TRAINED_MODEL_DIR)
if not os.path.exists("./" + config.TENSORBOARD_LOG_DIR):
    os.makedirs("./" + config.TENSORBOARD_LOG_DIR)
if not os.path.exists("./" + config.RESULTS_DIR):
    os.makedirs("./" + config.RESULTS_DIR)

In [ ]:
df_portfolio = pd.read_csv("TSX Chart Data Sorted By Date.csv")

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
df_portfolio.shape

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

(1048575, 8)

In [118]:
df_portfolio.head(20)

          date        close      high       low      open  volume     tic  day
0   2004-01-01     0.105000     0.105     0.105     0.105       0  DYA.TO    3
1   2004-01-01     1.378000     2.650     2.650     2.650       0  EDT.TO    3
2   2004-01-02     0.489625     0.530     0.530     0.530       0  AAB.TO    4
3   2004-01-02    22.070272    29.850    29.320    29.430  413000  ABX.TO    4
4   2004-01-02     3.484277     7.050     7.050     7.050     100  ACD.TO    4
5   2004-01-02     8.834254    13.580    13.160    13.160    8671  ACX.TO    4
6   2004-01-02    12.162339    15.830    15.500    15.500   42500  AEM.TO    4
7   2004-01-02     0.762091     0.770     0.770     0.770       0   AG.TO    4
8   2004-01-02     2.261605     2.750     2.560     2.750   24800  AGI.TO    4
9   2004-01-02     2.612467     6.200     6.200     6.200    1000  ALC.TO    4
10  2004-01-02     2.121329     2.500     2.330     2.330  176300  ALS.TO    4
11  2004-01-02     2.220000     2.300     2.220     2.290   30300  AMM.TO    4
12  2004-01-02     0.826958     0.900     0.900     0.900     500  AOI.TO    4
13  2004-01-02     0.350000     0.350     0.350     0.350   16700  AOT.TO    4
14  2004-01-02  5670.000000  5670.000  5454.000  5670.000      14  APS.TO    4
15  2004-01-02     2.443065    10.750    10.600    10.700   76400  AQN.TO    4
16  2004-01-02     2.665446     4.550     4.550     4.550     500  ARE.TO    4
17  2004-01-02     1.116771     2.000     1.950     1.960   27600  ARG.TO    4
18  2004-01-02     4.169235    14.740    14.550    14.740  191900  ARX.TO    4
19  2004-01-02     1.800000     1.870     1.800     1.830    3800  ASM.TO    4

In [ ]:
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split

In [134]:
fe = FeatureEngineer()
df = fe.preprocess_data(df_portfolio)
df = df_portfolio

Successfully added technical indicators

In [121]:
df.shape

(1048575, 8)

In [120]:
df.tic.unique()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

array(['DYA.TO', 'EDT.TO', 'AAB.TO', 'ABX.TO', 'ACD.TO', 'ACX.TO',
       'AEM.TO', 'AG.TO', 'AGI.TO', 'ALC.TO', 'ALS.TO', 'AMM.TO',
       'AOI.TO', 'AOT.TO', 'APS.TO', 'AQN.TO', 'ARE.TO', 'ARG.TO',
       'ARX.TO', 'ASM.TO', 'ATCU.TO', 'ATD.TO', 'ATRL.TO', 'ATS.TO',
       'AVL.TO', 'BB.TO', 'BCE.TO', 'BDGI.TO', 'BDT.TO', 'BHC.TO',
       'BIR.TO', 'BLDP.TO', 'BLX.TO', 'BMO.TO', 'BN.TO', 'BNE.TO',
       'BNG.TO', 'BNS.TO', 'BOS.TO', 'BR.TO', 'BRY.TO', 'BSX.TO',
       'BTE.TO', 'BU.TO', 'BUI.TO', 'BYD.TO', 'CAE.TO', 'CAS.TO',
       'CCA.TO', 'CCM.TO', 'CCO.TO', 'CFP.TO', 'CFW.TO', 'CGG.TO',
       'CGI.TO', 'CGO.TO', 'CGY.TO', 'CIGI.TO', 'CIX.TO', 'CKI.TO',
       'CLS.TO', 'CM.TO', 'CMG.TO', 'CNE.TO', 'CNQ.TO', 'CNR.TO', 'CP.TO',
       'CS.TO', 'CSCI.TO', 'CTC.TO', 'CU.TO', 'CVG.TO', 'CWB.TO',
       'CWL.TO', 'CXB.TO', 'DIAM.TO', 'DIV.TO', 'DML.TO', 'DPM.TO',
       'DRX.TO', 'DSG.TO', 'EDR.TO', 'EDV.TO', 'EFR.TO', 'ELD.TO',
       'ELF.TO', 'ELR.TO', 'ELVA.TO', 'DFN.TO', 'CPH.TO', 'EIF.TO',
       'ALA.TO', 'AFN.TO', 'CG.TO', 'AIM.TO', 'BK.TO', 'E.TO', 'AEG.TO',
       'DCM.TO', 'CEU.TO', 'CF.TO', 'ELEF.TO', 'DXT.TO', 'CDZ.TO',
       'DF.TO', 'DR.TO', 'CFX.TO', 'CEMX.TO', 'CPD.TO', 'CSU.TO',
       'CWW.TO', 'DNG.TO', 'ELO.TO', 'DGS.TO', 'COW.TO', 'CYH.TO',
       'BTO.TO', 'CEW.TO', 'CLF.TO', 'CRRX.TO', 'CMR.TO', 'CRP.TO',
       'ADEN.TO', 'ADN.TO', 'AIF.TO', 'BDI.TO', 'BEPR.TO', 'BRE.TO',
       'CGAA.TO', 'ACQ.TO', 'AYA.TO', 'DBM.TO', 'CGR.TO', 'CIF.TO',
       'CYB.TO', 'DBO.TO', 'CPX.TO', 'DOL.TO', 'AAV.TO', 'AUMN.TO',
       'CVE.TO', 'CBO.TO', 'AC.TO', 'ATH.TO', 'CFF.TO', 'AII.TO',
       'ECOR.TO', 'CGX.TO', 'CGL.TO', 'ARIS.TO', 'DS.TO', 'BKI.TO',
       'CNCC.TO', 'DLR.TO', 'CGXF.TO', 'EFX.TO', 'CVD.TO', 'ECO.TO',
       'CUD.TO', 'EFN.TO', 'BLN.TO', 'CIC.TO', 'BKCC.TO', 'CNT.TO',
       'CBH.TO', 'CDR.TO', 'CJT.TO', 'CLG.TO', 'CXF.TO', 'ASND.TO',
       'BABY.TO', 'BCT.TO', 'BESG.TO', 'AI.TO', 'CXI.TO', 'DOO.TO',
       'DRM.TO', 'BXF.TO', 'BYL.TO', 'DRT.TO', 'CJ.TO', 'CIA.TO',
       'DSV.TO', 'CIBR.TO', 'CRON.TO', 'CGHY.TO', 'CRWN.TO', 'BND.TO',
       'DLCG.TO', 'CHR.TO', 'DGR.TO', 'ECN.TO', 'ATZ.TO', 'ACB.TO',
       'BNC.TO', 'DXG.TO', 'DXC.TO', 'DCP.TO', 'DCG.TO', 'DCU.TO',
       'DCC.TO', 'DISC.TO', 'DCS.TO', 'CAGG.TO', 'EDGF.TO', 'CAGS.TO',
       'DXB.TO', 'DXP.TO', 'DXU.TO', 'CALL.TO', 'CARS.TO', 'CYBR.TO',
       'DIVS.TO', 'DXO.TO', 'CEF.TO', 'COG.TO', 'DGRC.TO', 'DXF.TO',
       'DXZ.TO', 'BGC.TO', 'BGU.TO', 'AMC.TO', 'DXV.TO', 'DAY.TO',
       'EDGE.TO', 'COMM.TO', 'AVNT.TO', 'BRAG.TO', 'CTX.TO', 'CWEB.TO',
       'DRFC.TO', 'DRFD.TO', 'DRFU.TO', 'DRMU.TO', 'DRCU.TO', 'DRMC.TO',
       'ALYA.TO', 'CTS.TO', 'EARN.TO', 'CRDL.TO', 'CNL.TO', 'CAFR.TO',
       'DANC.TO', 'BDIV.TO', 'BFIN.TO', 'BPRF.TO', 'CACB.TO', 'DRFG.TO',
       'DRFE.TO', 'ATSX.TO', 'ADCO.TO', 'BASE.TO', 'CSAV.TO', 'APLI.TO',
       'BITF.TO', 'AVCN.TO', 'EAGR.TO', 'DCBO.TO', 'AND.TO', 'EGLX.TO',
       'CMAR.TO', 'CRED.TO', 'CFLX.TO', 'CMAG.TO', 'DXN.TO', 'DXW.TO',
       'BIPC.TO', 'BLOV.TO', 'BREA.TO', 'CDLB.TO', 'CGRA.TO', 'CGRE.TO',
       'CINF.TO', 'BNK.TO', 'DND.TO', 'BEPC.TO', 'CGLO.TO', 'CINT.TO',
       'CCNS.TO', 'CCRE.TO', 'CPLS.TO', 'CBND.TO', 'CDIV.TO', 'BSKT.TO',
       'AIDX.TO', 'DATA.TO', 'CMGG.TO', 'EBIT.TO', 'BTCC.TO', 'BRMI.TO',
       'CCBI.TO', 'CCEI.TO', 'CUEI.TO', 'DXIF.TO', 'CIEI.TO', 'CURA.TO',
       'BITI.TO', 'BTCQ.TO', 'DNTL.TO', 'DXEM.TO', 'ANRG.TO', 'CHPS.TO',
       'DXET.TO', 'BNT.TO', 'CLML.TO', 'CINV.TO', 'CMDO.TO', 'CIEM.TO',
       'CEMI.TO', 'CROP.TO', 'ASTL.TO', 'CASH.TO', 'DTOL.TO', 'CDEF.TO',
       'ASCU.TO', 'CVO.TO', 'DFY.TO', 'ARTI.TO', 'BTCY.TO', 'ARA.TO',
       'EBNK.TO', 'DSAE.TO', 'BANK.TO', 'CARB.TO', 'CBUG.TO', 'CDNA.TO',
       'CBNK.TO', 'BBUC.TO', 'CFRT.TO', 'CMVX.TO', 'BLCO.TO', 'COPP.TO',
       'DXQ.TO', 'CGRN.TO', 'CCOM.TO', 'DAMG.TO', 'BMAX.TO', 'DXDB.TO',
       'BAM.TO', 'CUDV.TO', 'CSBI.TO', 'CGDV.TO', 'CUTL.TO', 'CBIL.TO',
       'CBIN.TO', 'CCNV.TO', 'CEQT.TO', 'CGRO.TO', 'CBAL.TO', 'CBGR.TO',
       'CNCL.TO', 'CANL.TO', 'BNKL.TO', 'BKCL.TO', 'CMNY.TO', 'AAUC.TO',
       'BOND.TO', 'DXBC.TO', 'DXUS.TO', 'DXBU.TO', 'DXGE.TO', 'ARB.TO',
       'CBCX.TO', 'CGBI.TO', 'CGIN.TO', 'CIEH.TO', 'CUEH.TO', 'DRMD.TO',
       'DRME.TO', 'DXR.TO', 'CMOM.TO', 'CVLU.TO', 'AMAX.TO', 'ADIV.TO',
       'DMEI.TO', 'DCBC.TO', 'DMEC.TO', 'DMEU.TO', 'CIAI.TO', 'AIGO.TO',
       'CNDX.TO', 'CBL.TO', 'CNV.TO', 'DXAU.TO', 'DXMO.TO', 'ACAA.TO',
       'CUBD.TO', 'COPR.TO', 'CORE.TO', 'AMZH.TO', 'AMHE.TO', 'BCHT.TO',
       'AGG.TO', 'AW.TO', 'CAPG.TO', 'CAPI.TO', 'CAPM.TO', 'CAPW.TO',
       'DXBB.TO', 'DXCB.TO', 'DXBG.TO', 'DXCP.TO', 'DXCO.TO'],
      dtype=object)

In [135]:
df.head(20)

          date        close      high       low      open  volume     tic  day
0   2004-01-01     0.105000     0.105     0.105     0.105       0  DYA.TO    3
1   2004-01-01     1.378000     2.650     2.650     2.650       0  EDT.TO    3
2   2004-01-02     0.489625     0.530     0.530     0.530       0  AAB.TO    4
3   2004-01-02    22.070272    29.850    29.320    29.430  413000  ABX.TO    4
4   2004-01-02     3.484277     7.050     7.050     7.050     100  ACD.TO    4
5   2004-01-02     8.834254    13.580    13.160    13.160    8671  ACX.TO    4
6   2004-01-02    12.162339    15.830    15.500    15.500   42500  AEM.TO    4
7   2004-01-02     0.762091     0.770     0.770     0.770       0   AG.TO    4
8   2004-01-02     2.261605     2.750     2.560     2.750   24800  AGI.TO    4
9   2004-01-02     2.612467     6.200     6.200     6.200    1000  ALC.TO    4
10  2004-01-02     2.121329     2.500     2.330     2.330  176300  ALS.TO    4
11  2004-01-02     2.220000     2.300     2.220     2.290   30300  AMM.TO    4
12  2004-01-02     0.826958     0.900     0.900     0.900     500  AOI.TO    4
13  2004-01-02     0.350000     0.350     0.350     0.350   16700  AOT.TO    4
14  2004-01-02  5670.000000  5670.000  5454.000  5670.000      14  APS.TO    4
15  2004-01-02     2.443065    10.750    10.600    10.700   76400  AQN.TO    4
16  2004-01-02     2.665446     4.550     4.550     4.550     500  ARE.TO    4
17  2004-01-02     1.116771     2.000     1.950     1.960   27600  ARG.TO    4
18  2004-01-02     4.169235    14.740    14.550    14.740  191900  ARX.TO    4
19  2004-01-02     1.800000     1.870     1.800     1.830    3800  ASM.TO    4

In [136]:
# add covariance matrix as states
df=df.sort_values(['date','tic'],ignore_index=True)
df.index = df.date.factorize()[0]

cov_list = []
return_list = []

# look back is one year
lookback=252
for i in range(lookback,len(df.index.unique())):
  data_lookback = df.loc[i-lookback:i,:]
  price_lookback=data_lookback.pivot_table(index = 'date',columns = 'tic', values = 'close')
  return_lookback = price_lookback.pct_change().dropna()
  return_list.append(return_lookback)

  covs = return_lookback.cov().values
  cov_list.append(covs)


df_cov = pd.DataFrame({'date':df.date.unique()[lookback:],'cov_list':cov_list,'return_list':return_list})
df = df.merge(df_cov, on='date')
df = df.sort_values(['date','tic']).reset_index(drop=True)

Streaming output truncated to the last 5000 lines.
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
<ipython-input-136-abea03093a39>:13: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  return_lookback = price_lookback.pct_change().dropna()
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py:11211: RuntimeWarning: Degrees of freedom <= 0 for slice
  base_cov = np.cov(mat.T, ddof=ddof)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply

In [137]:
df.shape

(1026079, 10)

In [138]:
df.head()

,date,close,high,low,open,volume,tic,day,cov_list,return_list
0,2004-12-20,0.415720,0.450000,0.450000,0.450000,0,AAB.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
1,2004-12-20,21.684490,29.090000,28.629999,28.629999,892100,ABX.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
2,2004-12-20,4.109743,8.100000,8.100000,8.100000,1000,ACD.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
3,2004-12-20,17.205807,24.150000,23.100000,23.799999,22143,ACX.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
4,2004-12-20,12.918009,17.040001,16.670000,16.790001,217000,AEM.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...

In [139]:
df.tail()

,date,close,high,low,open,volume,tic,day,cov_list,return_list
1026074,2024-12-27,21.60,21.65000,21.219999,21.40000,153600,ELD.TO,4,"[[0.014899914608964001, 0.001120277539557747, ...",tic AAB.TO AAUC.TO AAV.TO AB...
1026075,2024-12-27,0.37,0.38000,0.360000,0.36000,16900,ELEF.TO,4,"[[0.014899914608964001, 0.001120277539557747, ...",tic AAB.TO AAUC.TO AAV.TO AB...
1026076,2024-12-27,1311.25,1319.98999,1299.520020,1299.52002,1200,ELF.TO,4,"[[0.014899914608964001, 0.001120277539557747, ...",tic AAB.TO AAUC.TO AAV.TO AB...
1026077,2024-12-27,0.85,0.88000,0.840000,0.88000,116800,ELO.TO,4,"[[0.014899914608964001, 0.001120277539557747, ...",tic AAB.TO AAUC.TO AAV.TO AB...
1026078,2024-12-27,0.15,0.15000,0.150000,0.15000,4500,ELR.TO,4,"[[0.014899914608964001, 0.001120277539557747, ...",tic AAB.TO AAUC.TO AAV.TO AB...

In [140]:
train = data_split(df, '2004-01-01','2008-12-31')

In [141]:
train.head()

,date,close,high,low,open,volume,tic,day,cov_list,return_list
0,2004-12-20,0.415720,0.450000,0.450000,0.450000,0,AAB.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
0,2004-12-20,21.684490,29.090000,28.629999,28.629999,892100,ABX.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
0,2004-12-20,4.109743,8.100000,8.100000,8.100000,1000,ACD.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
0,2004-12-20,17.205807,24.150000,23.100000,23.799999,22143,ACX.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
0,2004-12-20,12.918009,17.040001,16.670000,16.790001,217000,AEM.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...

In [142]:
train.tail()

,date,close,high,low,open,volume,tic,day,cov_list,return_list
1014,2008-12-30,260.000000,270.0,260.00,270.00,50,ELEF.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...
1014,2008-12-30,284.767181,425.0,425.00,425.00,200,ELF.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...
1014,2008-12-30,2.800000,2.8,2.40,2.40,275,ELO.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...
1014,2008-12-30,3.500000,3.7,3.30,3.60,245130,ELR.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...
1014,2008-12-30,1.200000,1.3,1.15,1.15,4800,ELVA.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...

In [143]:
stock_dimension = len(train.tic.unique())
state_space = stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 132, State Space: 132

In [145]:
from finrl import config

In [144]:
train

,date,close,high,low,open,volume,tic,day,cov_list,return_list
0,2004-12-20,0.415720,0.450000,0.450000,0.450000,0,AAB.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
0,2004-12-20,21.684490,29.090000,28.629999,28.629999,892100,ABX.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
0,2004-12-20,4.109743,8.100000,8.100000,8.100000,1000,ACD.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
0,2004-12-20,17.205807,24.150000,23.100000,23.799999,22143,ACX.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
0,2004-12-20,12.918009,17.040001,16.670000,16.790001,217000,AEM.TO,0,"[[0.009335785113573457, -0.0001770641735861586...",tic AAB.TO ABX.TO ACD.TO AC...
...,...,...,...,...,...,...,...,...,...,...
1014,2008-12-30,260.000000,270.000000,260.000000,270.000000,50,ELEF.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...
1014,2008-12-30,284.767181,425.000000,425.000000,425.000000,200,ELF.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...
1014,2008-12-30,2.800000,2.800000,2.400000,2.400000,275,ELO.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...
1014,2008-12-30,3.500000,3.700000,3.300000,3.600000,245130,ELR.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...
1014,2008-12-30,1.200000,1.300000,1.150000,1.150000,4800,ELVA.TO,1,"[[0.0063487681552264075, 0.0007747908218029484...",tic AAB.TO ABX.TO ACD.TO AC...

In [161]:
df["cov_list"].values[10]

array([[ 9.33578511e-03, -1.77064174e-04, -2.41722955e-04, ...,
         1.09106765e-04, -9.57817708e-05, -4.40586243e-04],
       [-1.77064174e-04,  2.18624177e-04,  9.41348069e-07, ...,
        -1.08353227e-05,  7.11334593e-05,  7.16566591e-05],
       [-2.41722955e-04,  9.41348069e-07,  7.88279562e-04, ...,
        -7.05087166e-06,  4.26553707e-05, -1.78650959e-04],
       ...,
       [ 1.09106765e-04, -1.08353227e-05, -7.05087166e-06, ...,
         2.21115191e-04, -1.91547895e-04,  2.05752034e-06],
       [-9.57817708e-05,  7.11334593e-05,  4.26553707e-05, ...,
        -1.91547895e-04,  3.95109288e-03,  1.99793837e-04],
       [-4.40586243e-04,  7.16566591e-05, -1.78650959e-04, ...,
         2.05752034e-06,  1.99793837e-04,  3.16168905e-03]])

In [158]:
env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "transaction_cost_pct": 0.001,
    "state_space": 10,
    "stock_dim": stock_dimension,
    "tech_indicator_list": [],
    "action_space": stock_dimension,
    "reward_scaling": 1e-4

}

e_train_gym = StockPortfolioEnv(df = train, **env_kwargs)

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [162]:
from finrl.meta.data_processor import DataProcessor

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [164]:
df_portfolio.head()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

         date      close    high     low    open  volume     tic  day
0  2004-01-01   0.105000   0.105   0.105   0.105       0  DYA.TO    3
1  2004-01-01   1.378000   2.650   2.650   2.650       0  EDT.TO    3
2  2004-01-02   0.489625   0.530   0.530   0.530       0  AAB.TO    4
3  2004-01-02  22.070272  29.850  29.320  29.430  413000  ABX.TO    4
4  2004-01-02   3.484277   7.050   7.050   7.050     100  ACD.TO    4

In [169]:
dp = DataProcessor(df_portfolio)
rocessed_data = dp.clean_data()

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [170]:
from stable_baselines3.common.vec_env import DummyVecEnv
from finrl.meta.env_portfolio_optimization.env_portfolio_optimization import PortfolioOptimizationEnv

In [173]:
tickers_list = df_portfolio.tic.unique()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [183]:
pip install 'shimmy>=2.0'

Collecting shimmy>=2.0
  Downloading Shimmy-2.0.0-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.18.0 in /usr/local/lib/python3.11/dist-packages (from shimmy>=2.0) (1.26.4)
Requirement already satisfied: gymnasium>=1.0.0a1 in /usr/local/lib/python3.11/dist-packages (from shimmy>=2.0) (1.0.0)
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium>=1.0.0a1->shimmy>=2.0) (3.1.1)
Requirement already satisfied: typing-extensions>=4.3.0 in /usr/local/lib/python3.11/dist-packages (from gymnasium>=1.0.0a1->shimmy>=2.0) (4.12.2)
Requirement already satisfied: farama-notifications>=0.0.1 in /usr/local/lib/python3.11/dist-packages (from gymnasium>=1.0.0a1->shimmy>=2.0) (0.0.4)
Downloading Shimmy-2.0.0-py3-none-any.whl (30 kB)
Installing collected packages: shimmy
Successfully installed shimmy-2.0.0

In [184]:
env_kwargs = {
    "df": df_portfolio,
    "initial_amount": 1e6,  # Initial capital
    "comission_fee_pct": 0.001,  # Trading cost
    "reward_scaling": 1e-4,
    "time_window": 50,
    "normalize_df": None
}

env = PortfolioOptimizationEnv(**env_kwargs)
env = DummyVecEnv([lambda: env])  # Vectorized for SB3 compatibility

/usr/local/lib/python3.11/dist-packages/stable_baselines3/common/vec_env/patch_gym.py:49: UserWarning: You provided an OpenAI Gym environment. We strongly recommend transitioning to Gymnasium environments. Stable-Baselines3 is automatically wrapping your environments in a compatibility layer, which could potentially cause issues.
  warnings.warn(

In [185]:
from stable_baselines3 import A2C

In [186]:
model = A2C("MlpPolicy", env, verbose=1, learning_rate=0.0005, gamma=0.99)
model.learn(total_timesteps=100000)

Using cpu device

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 49 and the array at index 1 has size 0