In [1]:
# ## install finrl library
!pip install wrds
!pip install swig
!pip install -q condacolab
import condacolab
condacolab.install()
!apt-get update -y -qq && apt-get install -y -qq cmake libopenmpi-dev python3-dev zlib1g-dev libgl1-mesa-glx swig
!pip install git+https://github.com/AI4Finance-Foundation/FinRL.git

Collecting wrds
  Downloading wrds-3.3.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: packaging<=24.2 in /usr/local/lib/python3.11/dist-packages (from wrds) (24.2)
Requirement already satisfied: pandas<2.3,>=2.2 in /usr/local/lib/python3.11/dist-packages (from wrds) (2.2.2)
Collecting psycopg2-binary<2.10,>=2.9 (from wrds)
  Downloading psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: sqlalchemy<2.1,>=2 in /usr/local/lib/python3.11/dist-packages (from wrds) (2.0.38)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3,>=2.2->wrds) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3,>=2.2->wrds) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3,>=2.2->wrds) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<2.3,>=2.2->wrds) (2025.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<2.1,>=2->wrds) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.11/dist-packages (from sqlalchemy<2.1,>=2->wrds) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.17.0)
Downloading wrds-3.3.0-py3-none-any.whl (13 kB)
Downloading psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 23.9 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary, wrds
Successfully installed psycopg2-binary-2.9.10 wrds-3.3.0
Collecting swig
  Downloading swig-4.3.0-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (3.5 kB)
Downloading swig-4.3.0-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 16.9 MB/s eta 0:00:00
Installing collected packages: swig
Successfully installed swig-4.3.0
⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:20
🔁 Restarting kernel...
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package libgl1-mesa-glx:amd64.
(Reading database ... 124926 files and directories currently installed.)
Preparing to unpack .../libgl1-mesa-glx_23.0.4-0ubuntu1~22.04.1_amd64.deb ...
Unpacking libgl1-mesa-glx:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Selecting previously unselected package swig4.0.
Preparing to unpack .../swig4.0_4.0.2-1ubuntu1_amd64.deb ...
Unpacking swig4.0 (4.0.2-1ubuntu1) ...
Selecting previously unselected package swig.
Preparing to unpack .../swig_4.0.2-1ubuntu1_all.deb ...
Unpacking swig (4.0.2-1ubuntu1) ...
Setting up libgl1-mesa-glx:amd64 (23.0.4-0ubuntu1~22.04.1) ...
Setting up swig4.0 (4.0.2-1ubuntu1) ...
Setting up swig (4.0.2-1ubuntu1) ...
Processing triggers for man-db (2.10.2-1) ...
Collecting git+https://github.com/AI4Finance-Foundation/FinRL.git
  Cloning https://github.com/AI4Finance-Foundation/FinRL.git to /tmp/pip-req-build-3y_vg142
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/FinRL.git /tmp/pip-req-build-3y_vg142
  Resolved https://github.com/AI4Finance-Foundation/FinRL.git to commit 3a10805389c07e13e94333e94dcfe9beafce49b0
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl==0.3.6)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to /tmp/pip-install-bkneghzc/elegantrl_f8d735d5c6804677a3cede8b68c4d10a
  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git /tmp/pip-install-bkneghzc/elegantrl_f8d735d5c6804677a3cede8b68c4d10a
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 62bf617fa87cf82b9fbf88307715d93b8ab8ee80
  Preparing metadata (setup.py) ... done
Collecting alpaca-py<0.38,>=0.37 (from finrl==0.3.6)
  Downloading alpaca_py-0.37.0-py3-none-any.whl.metadata (13 kB)
Collecting alpaca-trade-api<4,>=3 (from finrl==0.3.6)
  Downloading alpaca_trade_api-3.2.0-py3-none-any.whl.metadata (29 kB)
Collecting ccxt<4,>=3 (from finrl==0.3.6)
  Downloading ccxt-3.1.60-py2.py3-none-any.whl.metadata (108 kB)
Collecting exchange-calendars<5,>=4 (from finrl==0.3.6)
  Downloading exchange_calendars-4.9-py3-none-any.whl.metadata (37 kB)
Collecting jqdatasdk<2,>=1 (from finrl==0.3.6)
  Downloading jqdatasdk-1.9.7-py3-none-any.whl.metadata (5.8 kB)
Collecting pyfolio<0.10,>=0.9 (from finrl==0.3.6)
  Downloading pyfolio-0.9.2.tar.gz (91 kB)
  Preparing metadata (setup.py) ... done
Collecting pyportfolioopt<2,>=1 (from finrl==0.3.6)
  Downloading pyportfolioopt-1.5.6-py3-none-any.whl.metadata (22 kB)
Collecting ray<3,>=2 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading ray-2.42.1-cp311-cp311-manylinux2014_x86_64.whl.metadata (18 kB)
Collecting scikit-learn<2,>=1 (from finrl==0.3.6)
  Downloading scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting selenium<5,>=4 (from finrl==0.3.6)
  Downloading selenium-4.28.1-py3-none-any.whl.metadata (7.1 kB)
Collecting stable-baselines3>=2.0.0a5 (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading stable_baselines3-2.6.0a1-py3-none-any.whl.metadata (4.8 kB)
Collecting stockstats<0.6,>=0.5 (from finrl==0.3.6)
  Downloading stockstats-0.5.4-py2.py3-none-any.whl.metadata (26 kB)
Collecting webdriver-manager<5,>=4 (from finrl==0.3.6)
  Downloading webdriver_manager-4.0.2-py2.py3-none-any.whl.metadata (12 kB)
Collecting wrds<4,>=3 (from finrl==0.3.6)
  Using cached wrds-3.3.0-py3-none-any.whl.metadata (5.7 kB)
Collecting yfinance<0.3,>=0.2 (from finrl==0.3.6)
  Downloading yfinance-0.2.53-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting msgpack<2.0.0,>=1.0.3 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading msgpack-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.4 kB)
Collecting pandas>=1.5.3 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting pydantic<3.0.0,>=2.0.3 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading pydantic-2.10.6-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: requests<3.0.0,>=2.30.0 in /usr/local/lib/python3.11/site-packages (from alpaca-py<0.38,>=0.37->finrl==0.3.6) (2.32.3)
Collecting sseclient-py<2.0.0,>=1.7.2 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading sseclient_py-1.8.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting websockets>=10.4 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading websockets-15.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting numpy>=1.11.1 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading numpy-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Collecting urllib3<2,>1.24 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading urllib3-1.26.20-py2.py3-none-any.whl.metadata (50 kB)
Collecting websocket-client<2,>=0.56.0 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading websocket_client-1.8.0-py3-none-any.whl.metadata (8.0 kB)
Collecting websockets>=10.4 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading websockets-10.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Collecting msgpack<2.0.0,>=1.0.3 (from alpaca-py<0.38,>=0.37->finrl==0.3.6)
  Downloading msgpack-1.0.3.tar.gz (123 kB)
  Preparing metadata (setup.py) ... done
Collecting aiohttp<4,>=3.8.3 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading aiohttp-3.11.12-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)
Collecting PyYAML==6.0.1 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting deprecation==2.1.0 (from alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading deprecation-2.1.0-py2.py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/site-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl==0.3.6) (24.2)
Requirement already satisfied: setuptools>=60.9.0 in /usr/local/lib/python3.11/site-packages (from ccxt<4,>=3->finrl==0.3.6) (65.6.3)
Requirement already satisfied: certifi>=2018.1.18 in /usr/local/lib/python3.11/site-packages (from ccxt<4,>=3->finrl==0.3.6) (2024.12.14)
Collecting cryptography>=2.6.1 (from ccxt<4,>=3->finrl==0.3.6)
  Downloading cryptography-44.0.1-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (5.7 kB)
Collecting aiodns>=1.1.1 (from ccxt<4,>=3->finrl==0.3.6)
  Downloading aiodns-3.2.0-py3-none-any.whl.metadata (4.0 kB)
Collecting yarl>=1.7.2 (from ccxt<4,>=3->finrl==0.3.6)
  Downloading yarl-1.18.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (69 kB)
Collecting pyluach (from exchange-calendars<5,>=4->finrl==0.3.6)
  Downloading pyluach-2.2.0-py3-none-any.whl.metadata (4.3 kB)
Collecting toolz (from exchange-calendars<5,>=4->finrl==0.3.6)
  Downloading toolz-1.0.0-py3-none-any.whl.metadata (5.1 kB)
Collecting tzdata (from exchange-calendars<5,>=4->finrl==0.3.6)
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting korean_lunar_calendar (from exchange-calendars<5,>=4->finrl==0.3.6)
  Downloading korean_lunar_calendar-0.3.1-py3-none-any.whl.metadata (2.8 kB)
Collecting six (from jqdatasdk<2,>=1->finrl==0.3.6)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting SQLAlchemy>=1.2.8 (from jqdatasdk<2,>=1->finrl==0.3.6)
  Downloading SQLAlchemy-2.0.38-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting pymysql>=0.7.6 (from jqdatasdk<2,>=1->finrl==0.3.6)
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Collecting thriftpy2!=0.5.1,>=0.3.9 (from jqdatasdk<2,>=1->finrl==0.3.6)
  Downloading thriftpy2-0.5.2.tar.gz (782 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 782.3/782.3 kB 14.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ipython>=3.2.3 (from pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading ipython-8.32.0-py3-none-any.whl.metadata (5.0 kB)
Collecting matplotlib>=1.4.0 (from pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading matplotlib-3.10.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pytz>=2014.10 (from pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting scipy>=0.14.0 (from pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting seaborn>=0.7.1 (from pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting empyrical>=0.5.0 (from pyfolio<0.10,>=0.9->finrl==0.3.6)
  Downloading empyrical-0.5.5.tar.gz (52 kB)
  Preparing metadata (setup.py) ... done
Collecting cvxpy>=1.1.19 (from pyportfolioopt<2,>=1->finrl==0.3.6)
  Downloading cvxpy-1.6.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting ecos<3.0.0,>=2.0.14 (from pyportfolioopt<2,>=1->finrl==0.3.6)
  Downloading ecos-2.0.14-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting plotly<6.0.0,>=5.0.0 (from pyportfolioopt<2,>=1->finrl==0.3.6)
  Downloading plotly-5.24.1-py3-none-any.whl.metadata (7.3 kB)
Collecting click>=7.0 (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Collecting filelock (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting protobuf!=3.19.5,>=3.15.3 (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading protobuf-5.29.3-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting aiosignal (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading aiosignal-1.3.2-py2.py3-none-any.whl.metadata (3.8 kB)
Collecting frozenlist (from ray<3,>=2->ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading frozenlist-1.5.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting aiohttp-cors (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading aiohttp_cors-0.7.0-py3-none-any.whl.metadata (20 kB)
Collecting colorful (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading colorful-0.5.6-py2.py3-none-any.whl.metadata (16 kB)
Collecting opencensus (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading opencensus-0.11.4-py2.py3-none-any.whl.metadata (12 kB)
Collecting prometheus-client>=0.7.1 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading prometheus_client-0.21.1-py3-none-any.whl.metadata (1.8 kB)
Collecting smart-open (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading smart_open-7.1.0-py3-none-any.whl.metadata (24 kB)
Collecting virtualenv!=20.21.1,>=20.0.24 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading virtualenv-20.29.2-py3-none-any.whl.metadata (4.5 kB)
Collecting py-spy>=0.2.0 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading py_spy-0.4.0-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (16 kB)
Collecting grpcio>=1.42.0 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading grpcio-1.70.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting tensorboardX>=1.9 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading tensorboardX-2.6.2.2-py2.py3-none-any.whl.metadata (5.8 kB)
Collecting pyarrow>=9.0.0 (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading pyarrow-19.0.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (3.3 kB)
Collecting fsspec (from ray[default,tune]<3,>=2->finrl==0.3.6)
  Downloading fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)
Collecting joblib>=1.2.0 (from scikit-learn<2,>=1->finrl==0.3.6)
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn<2,>=1->finrl==0.3.6)
  Downloading threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Collecting trio~=0.17 (from selenium<5,>=4->finrl==0.3.6)
  Downloading trio-0.29.0-py3-none-any.whl.metadata (8.5 kB)
Collecting trio-websocket~=0.9 (from selenium<5,>=4->finrl==0.3.6)
  Downloading trio_websocket-0.12.0-py3-none-any.whl.metadata (5.0 kB)
Collecting typing_extensions~=4.9 (from selenium<5,>=4->finrl==0.3.6)
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting gymnasium<1.1.0,>=0.29.1 (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading gymnasium-1.0.0-py3-none-any.whl.metadata (9.5 kB)
Collecting torch<3.0,>=2.3 (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading torch-2.6.0-cp311-cp311-manylinux1_x86_64.whl.metadata (28 kB)
Collecting cloudpickle (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading cloudpickle-3.1.1-py3-none-any.whl.metadata (7.1 kB)
Collecting opencv-python (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading opencv_python-4.11.0.86-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting pygame (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading pygame-2.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting tensorboard>=2.9.1 (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading tensorboard-2.19.0-py3-none-any.whl.metadata (1.8 kB)
Collecting psutil (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading psutil-7.0.0-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6) (4.67.1)
Collecting rich (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting ale-py>=0.9.0 (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading ale_py-0.10.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.2 kB)
Collecting pillow (from stable-baselines3[extra]>=2.0.0a5->finrl==0.3.6)
  Downloading pillow-11.1.0-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting python-dotenv (from webdriver-manager<5,>=4->finrl==0.3.6)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Collecting psycopg2-binary<2.10,>=2.9 (from wrds<4,>=3->finrl==0.3.6)
  Using cached psycopg2_binary-2.9.10-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting multitasking>=0.0.7 (from yfinance<0.3,>=0.2->finrl==0.3.6)
  Downloading multitasking-0.0.11-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (4.3.6)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/site-packages (from yfinance<0.3,>=0.2->finrl==0.3.6) (2.4.6)
Collecting peewee>=3.16.2 (from yfinance<0.3,>=0.2->finrl==0.3.6)
  Downloading peewee-3.17.9.tar.gz (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 47.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting beautifulsoup4>=4.11.1 (from yfinance<0.3,>=0.2->finrl==0.3.6)
  Downloading beautifulsoup4-4.13.3-py3-none-any.whl.metadata (3.8 kB)
Collecting th (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl==0.3.6)
  Downloading th-0.4.1-py3-none-any.whl.metadata (3.4 kB)
Collecting pycares>=4.0.0 (from aiodns>=1.1.1->ccxt<4,>=3->finrl==0.3.6)
  Downloading pycares-4.5.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading aiohappyeyeballs-2.4.6-py3-none-any.whl.metadata (5.9 kB)
Collecting attrs>=17.3.0 (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading attrs-25.1.0-py3-none-any.whl.metadata (10 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading multidict-6.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Collecting propcache>=0.2.0 (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl==0.3.6)
  Downloading propcache-0.2.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.2 kB)
Collecting soupsieve>1.2 (from beautifulsoup4>=4.11.1->yfinance<0.3,>=0.2->finrl==0.3.6)
  Downloading soupsieve-2.6-py3-none-any.whl.metadata (4.6 kB)

In [1]:
import warnings
warnings.filterwarnings("ignore")

In [2]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# matplotlib.use('Agg')
import datetime

%matplotlib inline
from finrl.config_tickers import DOW_30_TICKER
from finrl.meta.preprocessor.yahoodownloader import YahooDownloader
from finrl.meta.preprocessor.preprocessors import FeatureEngineer, data_split
from finrl.meta.env_stock_trading.env_stocktrading import StockTradingEnv
from finrl.agents.stablebaselines3.models import DRLAgent,DRLEnsembleAgent
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline

from pprint import pprint

import sys
sys.path.append("../FinRL-Library")

import itertools

/usr/local/lib/python3.11/site-packages/pandas_datareader/compat/__init__.py:11: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  PANDAS_VERSION = LooseVersion(pd.__version__)

In [3]:
import os
from finrl.main import check_and_make_directories
from finrl.config import (
    DATA_SAVE_DIR,
    TRAINED_MODEL_DIR,
    TENSORBOARD_LOG_DIR,
    RESULTS_DIR,
    INDICATORS,
    TRAIN_START_DATE,
    TRAIN_END_DATE,
    TEST_START_DATE,
    TEST_END_DATE,
    TRADE_START_DATE,
    TRADE_END_DATE,
)

check_and_make_directories([DATA_SAVE_DIR, TRAINED_MODEL_DIR, TENSORBOARD_LOG_DIR, RESULTS_DIR])

In [ ]:
#Saved the preprocessed historical_data.csv as data.csv

df = pd.read_csv('data.csv')

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Selecting the indicators 

INDICATORS = ['macd',
               'rsi_30',
               'cci_30',
               'dx_30']

In [6]:
from finrl.meta.preprocessor.preprocessors import FeatureEngineer
fe = FeatureEngineer(use_technical_indicator=True,
                     tech_indicator_list = INDICATORS,
                     use_turbulence=True,
                     user_defined_feature = False)

processed = fe.preprocess_data(df)

Successfully added technical indicators
Successfully added turbulence index

In [7]:
df.head()

,date,close,high,low,open,volume,tic,day,daily_return
0,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3,NaN
1,2004-01-01,1.378000,1.378000,1.378000,1.378000,0,EDT.TO,3,12.123810
2,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3,-0.782293
3,2004-01-02,0.489625,0.489625,0.489625,0.489625,0,AAB.TO,4,0.632084
4,2004-01-02,22.070263,22.211644,21.817266,21.899118,413000,ABX.TO,4,44.075824

In [9]:
len(df)

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

4066965

In [10]:
stock_dimension = len(processed.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 3, State Space: 19

In [ ]:
env_kwargs = {
    "hmax": 100, #maximum number of shares
    "initial_amount": 1000000,
    "buy_cost_pct": 0.001, #percentage transaction cost
    "sell_cost_pct": 0.001, #percentage transaction cost
    "state_space": state_space, #umber of features in the state representation
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension, #number of actions available
    "reward_scaling": 1e-4, #scaling factor for rewards
    "print_verbosity":5

}

In [12]:
df.head()

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

,date,close,high,low,open,volume,tic,day,daily_return
0,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3,NaN
1,2004-01-01,1.378000,1.378000,1.378000,1.378000,0,EDT.TO,3,12.123810
2,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3,-0.782293
3,2004-01-02,0.489625,0.489625,0.489625,0.489625,0,AAB.TO,4,0.632084
4,2004-01-02,22.070263,22.211644,21.817266,21.899118,413000,ABX.TO,4,44.075824

In [15]:
df.date.value_counts()

date
2024-12-30    1621
2024-12-02    1620
2024-12-13    1619
2024-12-20    1618
2024-12-05    1618
              ...
2004-09-06       3
2004-10-11       3
2004-12-27       3
2004-12-28       3
2004-01-01       3
Name: count, Length: 5281, dtype: int64

In [16]:
df.date.info()

<class 'pandas.core.series.Series'>
RangeIndex: 4066965 entries, 0 to 4066964
Series name: date
Non-Null Count    Dtype
--------------    -----
4066965 non-null  object
dtypes: object(1)
memory usage: 31.0+ MB

/usr/local/lib/python3.11/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [19]:
(len(df) * 0.8)

3253572.0

In [18]:
df = df.sort_values(by='date').reset_index(drop=True)

In [22]:
split_idx = int(len(df) * 0.8)

In [23]:
# Extract training and validation periods directly
TRAIN_START_DATE = df.iloc[0]['date']
TRAIN_END_DATE = df.iloc[split_idx - 1]['date']

TEST_START_DATE = df.iloc[split_idx]['date']
TEST_END_DATE = df.iloc[-1]['date']

In [24]:
rebalance_window = 63 # rebalance_window is the number of days to retrain the model
validation_window = 63 # validation_window is the number of days to do validation and trading (e.g. if validation_window=63, then both validation and trading period will be 63 days)

ensemble_agent = DRLEnsembleAgent(df=processed,
                 train_period=(TRAIN_START_DATE,TRAIN_END_DATE),
                 val_test_period=(TEST_START_DATE,TEST_END_DATE),
                 rebalance_window=rebalance_window,
                 validation_window=validation_window,
                 **env_kwargs)

In [25]:
SAC_model_kwargs = {
    "batch_size": 64,
    "buffer_size": 100000,
    "learning_rate": 0.0001,
    "learning_starts": 100,
    "ent_coef": "auto_0.1",
}