In [ ]:
# GPT Thread Links
# https://chatgpt.com/share/67888ac6-7414-8009-9219-a4f4ec62f951
# https://chatgpt.com/share/678f107c-d880-8009-a1d2-58315121697c

In [ ]:
import yfinance as yf
import pandas as pd
import time

In [ ]:
def fetch_tickers_info(symbols):
    # List to store ticker info dictionaries
    data = []

    # Iterate over the symbols
    for symbol in symbols:
        try:
            # Fetch the ticker info
            ticker = yf.Ticker(symbol)
            info = ticker.info

            # Append the info dictionary to the list
            data.append(info)
            print(f"Fetched info for {symbol}")

            # Delay to avoid rate limiting
            time.sleep(1)
        except Exception as e:
            print(f"Error fetching data for {symbol}: {e}")

    # Convert the list of dictionaries into a DataFrame
    df = pd.DataFrame(data)
    return df

In [ ]:
# Load the Excel file
df = pd.read_csv('TSX stocks.csv')

# Convert the 'Symbol' column to an array (list)
symbols_array = df['Symbol'].tolist()

# Display the array
print(symbols_array)

['AAB.TO', 'AAUC.TO', 'AAV.TO', 'ABX.TO', 'AC.TO', 'ACAA.TO', 'ACB.TO', 'ACD.TO', 'ACQ.TO', 'ACX.TO', 'ADCO.TO', 'ADEN.TO', 'ADIV.TO', 'ADN.TO', 'AEG.TO', 'AEM.TO', 'AFN.TO', 'AG.TO', 'AGG.TO', 'AGI.TO', 'AI.TO', 'AIDX.TO', 'AIF.TO', 'AIGO.TO', 'AII.TO', 'AIM.TO', 'ALA.TO', 'ALC.TO', 'ALS.TO', 'ALYA.TO', 'AMAX.TO', 'AMC.TO', 'AMHE.TO', 'AMM.TO', 'AMZH.TO', 'AND.TO', 'ANRG.TO', 'AOI.TO', 'AOT.TO', 'APLI.TO', 'APM.TO', 'APS.TO', 'AQN.TO', 'ARA.TO', 'ARB.TO', 'ARE.TO', 'ARG.TO', 'ARIS.TO', 'ARTI.TO', 'ARX.TO', 'ASCU.TO', 'ASM.TO', 'ASND.TO', 'ASTL.TO', 'ATCU.TO', 'ATD.TO', 'ATH.TO', 'ATRL.TO', 'ATS.TO', 'ATSX.TO', 'ATZ.TO', 'AUMN.TO', 'AVCN.TO', 'AVL.TO', 'AVNT.TO', 'AW.TO', 'AYA.TO', 'BABY.TO', 'BAM.TO', 'BANK.TO', 'BASE.TO', 'BB.TO', 'BBUC.TO', 'BCE.TO', 'BCHT.TO', 'BCT.TO', 'BDGI.TO', 'BDI.TO', 'BDIV.TO', 'BDT.TO', 'BEPC.TO', 'BEPR.TO', 'BESG.TO', 'BFIN.TO', 'BGC.TO', 'BGU.TO', 'BHC.TO', 'BIPC.TO', 'BIR.TO', 'BITF.TO', 'BITI.TO', 'BK.TO', 'BKCC.TO', 'BKCL.TO', 'BKI.TO', 'BLCO.TO', 'BLDP.TO', 'BLN.TO', 'BLOV.TO', 'BLX.TO', 'BMAX.TO', 'BMO.TO', 'BN.TO', 'BNC.TO', 'BND.TO', 'BNE.TO', 'BNG.TO', 'BNK.TO', 'BNKL.TO', 'BNS.TO', 'BNT.TO', 'BOND.TO', 'BOS.TO', 'BPRF.TO', 'BR.TO', 'BRAG.TO', 'BRE.TO', 'BREA.TO', 'BRMI.TO', 'BRY.TO', 'BSKT.TO', 'BSX.TO', 'BTCC.TO', 'BTCQ.TO', 'BTCY.TO', 'BTE.TO', 'BTO.TO', 'BU.TO', 'BUI.TO', 'BXF.TO', 'BYD.TO', 'BYL.TO', 'CACB.TO', 'CAE.TO', 'CAFR.TO', 'CAGG.TO', 'CAGS.TO', 'CALL.TO', 'CANL.TO', 'CAPG.TO', 'CAPI.TO', 'CAPM.TO', 'CAPW.TO', 'CARB.TO', 'CARS.TO', 'CAS.TO', 'CASH.TO', 'CBAL.TO', 'CBCX.TO', 'CBGR.TO', 'CBH.TO', 'CBIL.TO', 'CBIN.TO', 'CBL.TO', 'CBND.TO', 'CBNK.TO', 'CBO.TO', 'CBUG.TO', 'CCA.TO', 'CCBI.TO', 'CCEI.TO', 'CCM.TO', 'CCNS.TO', 'CCNV.TO', 'CCO.TO', 'CCOM.TO', 'CCRE.TO', 'CDEF.TO', 'CDIV.TO', 'CDLB.TO', 'CDNA.TO', 'CDR.TO', 'CDZ.TO', 'CEF.TO', 'CEMI.TO', 'CEMX.TO', 'CEQT.TO', 'CEU.TO', 'CEW.TO', 'CF.TO', 'CFF.TO', 'CFLX.TO', 'CFP.TO', 'CFRT.TO', 'CFW.TO', 'CFX.TO', 'CG.TO', 'CGAA.TO', 'CGBI.TO', 'CGDV.TO', 'CGG.TO', 'CGHY.TO', 'CGI.TO', 'CGIN.TO', 'CGL.TO', 'CGLO.TO', 'CGO.TO', 'CGR.TO', 'CGRA.TO', 'CGRE.TO', 'CGRN.TO', 'CGRO.TO', 'CGX.TO', 'CGXF.TO', 'CGY.TO', 'CHPS.TO', 'CHR.TO', 'CIA.TO', 'CIAI.TO', 'CIBR.TO', 'CIC.TO', 'CIEH.TO', 'CIEI.TO', 'CIEM.TO', 'CIF.TO', 'CIGI.TO', 'CINF.TO', 'CINT.TO', 'CINV.TO', 'CIX.TO', 'CJ.TO', 'CJT.TO', 'CKI.TO', 'CLF.TO', 'CLG.TO', 'CLML.TO', 'CLS.TO', 'CM.TO', 'CMAG.TO', 'CMAR.TO', 'CMDO.TO', 'CMG.TO', 'CMGG.TO', 'CMNY.TO', 'CMOM.TO', 'CMR.TO', 'CMVX.TO', 'CNCC.TO', 'CNCL.TO', 'CNDX.TO', 'CNE.TO', 'CNL.TO', 'CNQ.TO', 'CNR.TO', 'CNT.TO', 'CNV.TO', 'COG.TO', 'COMM.TO', 'COPP.TO', 'COPR.TO', 'CORE.TO', 'COW.TO', 'CP.TO', 'CPD.TO', 'CPH.TO', 'CPLS.TO', 'CPX.TO', 'CRDL.TO', 'CRED.TO', 'CRON.TO', 'CROP.TO', 'CRP.TO', 'CRRX.TO', 'CRWN.TO', 'CS.TO', 'CSAV.TO', 'CSBI.TO', 'CSCI.TO', 'CSU.TO', 'CTC.TO', 'CTS.TO', 'CTX.TO', 'CU.TO', 'CUBD.TO', 'CUD.TO', 'CUDV.TO', 'CUEH.TO', 'CUEI.TO', 'CURA.TO', 'CUTL.TO', 'CVD.TO', 'CVE.TO', 'CVG.TO', 'CVLU.TO', 'CVO.TO', 'CWB.TO', 'CWEB.TO', 'CWL.TO', 'CWW.TO', 'CXB.TO', 'CXF.TO', 'CXI.TO', 'CYB.TO', 'CYBR.TO', 'CYH.TO', 'DAMG.TO', 'DANC.TO', 'DATA.TO', 'DAY.TO', 'DBM.TO', 'DBO.TO', 'DCBC.TO', 'DCBO.TO', 'DCC.TO', 'DCG.TO', 'DCM.TO', 'DCP.TO', 'DCS.TO', 'DCU.TO', 'DF.TO', 'DFN.TO', 'DFY.TO', 'DGR.TO', 'DGRC.TO', 'DGS.TO', 'DIAM.TO', 'DISC.TO', 'DIV.TO', 'DIVS.TO', 'DLCG.TO', 'DLR.TO', 'DMEC.TO', 'DMEI.TO', 'DMEU.TO', 'DML.TO', 'DND.TO', 'DNG.TO', 'DNTL.TO', 'DOL.TO', 'DOO.TO', 'DPM.TO', 'DR.TO', 'DRCU.TO', 'DRFC.TO', 'DRFD.TO', 'DRFE.TO', 'DRFG.TO', 'DRFU.TO', 'DRM.TO', 'DRMC.TO', 'DRMD.TO', 'DRME.TO', 'DRMU.TO', 'DRT.TO', 'DRX.TO', 'DS.TO', 'DSAE.TO', 'DSG.TO', 'DSV.TO', 'DTOL.TO', 'DXAU.TO', 'DXB.TO', 'DXBB.TO', 'DXBC.TO', 'DXBG.TO', 'DXBU.TO', 'DXC.TO', 'DXCB.TO', 'DXCO.TO', 'DXCP.TO', 'DXDB.TO', 'DXEM.TO', 'DXET.TO', 'DXF.TO', 'DXG.TO', 'DXGE.TO', 'DXIF.TO', 'DXMO.TO', 'DXN.TO', 'DXO.TO', 'DXP.TO', 'DXQ.TO', 'DXR.TO', 'DXT.TO', 'DXU.TO', 'DXUS.TO', 'DXV.TO', 'DXW.TO', 'DXZ.TO', 'DYA.TO', 'E.TO', 'EAGR.TO', 'EARN.TO', 'EBIT.TO', 'EBNK.TO', 'ECN.TO', 'ECO.TO', 'ECOR.TO', 'EDGE.TO', 'EDGF.TO', 'EDR.TO', 'EDT.TO', 'EDV.TO', 'EFN.TO', 'EFR.TO', 'EFX.TO', 'EGLX.TO', 'EIF.TO', 'ELD.TO', 'ELEF.TO', 'ELF.TO', 'ELO.TO', 'ELR.TO', 'ELVA.TO', 'EMA.TO', 'EMAX.TO', 'ENB.TO', 'ENCC.TO', 'ENCL.TO', 'ENGH.TO', 'ENS.TO', 'EPRX.TO', 'EQB.TO', 'EQCC.TO', 'EQCL.TO', 'EQL.TO', 'EQLI.TO', 'EQX.TO', 'ERD.TO', 'ERO.TO', 'ESG.TO', 'ESGA.TO', 'ESGB.TO', 'ESGC.TO', 'ESGE.TO', 'ESGF.TO', 'ESGG.TO', 'ESGH.TO', 'ESGY.TO', 'ESI.TO', 'ESM.TO', 'ESP.TO', 'ESPX.TO', 'ET.TO', 'ETC.TO', 'ETG.TO', 'ETHH.TO', 'ETHI.TO', 'ETHQ.TO', 'ETHR.TO', 'ETHY.TO', 'ETP.TO', 'ETSX.TO', 'EVO.TO', 'EVT.TO', 'EXE.TO', 'EXN.TO', 'EXRO.TO', 'FAP.TO', 'FAR.TO', 'FBGO.TO', 'FBT.TO', 'FBTC.TO', 'FC.TO', 'FCCD.TO', 'FCCQ.TO', 'FCCV.TO', 'FCEM.TO', 'FCGI.TO', 'FCID.TO', 'FCII.TO', 'FCIQ.TO', 'FCIV.TO', 'FCMI.TO', 'FCQH.TO', 'FCRR.TO', 'FCUD.TO', 'FCUH.TO', 'FCUQ.TO', 'FCUV.TO', 'FCVH.TO', 'FDL.TO', 'FDN.TO', 'FDY.TO', 'FEC.TO', 'FETH.TO', 'FF.TO', 'FFH.TO', 'FFM.TO', 'FFN.TO', 'FGB.TO', 'FGEB.TO', 'FGEP.TO', 'FGGE.TO', 'FGO.TO', 'FGOV.TO', 'FGRW.TO', 'FHG.TO', 'FHH.TO', 'FHI.TO', 'FHIS.TO', 'FHQ.TO', 'FIE.TO', 'FIG.TO', 'FIL.TO', 'FINC.TO', 'FINE.TO', 'FINO.TO', 'FLCI.TO', 'FLCP.TO', 'FLGA.TO', 'FLI.TO', 'FLNT.TO', 'FLOW.TO', 'FLSD.TO', 'FLUS.TO', 'FLX.TO', 'FM.TO', 'FMAX.TO', 'FN.TO', 'FNV.TO', 'FOM.TO', 'FOOD.TO', 'FORA.TO', 'FOUR.TO', 'FPR.TO', 'FRU.TO', 'FRX.TO', 'FSB.TO', 'FSF.TO', 'FSL.TO', 'FST.TO', 'FSV.TO', 'FSY.TO', 'FSZ.TO', 'FT.TO', 'FTG.TO', 'FTHI.TO', 'FTN.TO', 'FTS.TO', 'FTT.TO', 'FTU.TO', 'FURY.TO', 'FVI.TO', 'FVL.TO', 'FXM.TO', 'G.TO', 'GATO.TO', 'GAU.TO', 'GBAL.TO', 'GBT.TO', 'GCBD.TO', 'GCFE.TO', 'GCG.TO', 'GCL.TO', 'GCNS.TO', 'GCSC.TO', 'GCTB.TO', 'GCU.TO', 'GDC.TO', 'GDEP.TO', 'GDI.TO', 'GDL.TO', 'GDPY.TO', 'GDV.TO', 'GEC.TO', 'GEI.TO', 'GENM.TO', 'GEO.TO', 'GEQT.TO', 'GFL.TO', 'GFP.TO', 'GFR.TO', 'GGD.TO', 'GGRO.TO', 'GH.TO', 'GIGC.TO', 'GIL.TO', 'GIQG.TO', 'GIQU.TO', 'GLCC.TO', 'GLDX.TO', 'GLO.TO', 'GLXY.TO', 'GMIN.TO', 'GMTN.TO', 'GMX.TO', 'GOLD.TO', 'GOOS.TO', 'GPMD.TO', 'GRA.TO', 'GRC.TO', 'GRCC.TO', 'GRGD.TO', 'GRID.TO', 'GRN.TO', 'GRNI.TO', 'GRO.TO', 'GSY.TO', 'GTE.TO', 'GTWO.TO', 'GUD.TO', 'GURU.TO', 'GVC.TO', 'GWO.TO', 'GXE.TO', 'H.TO', 'HAB.TO', 'HAC.TO', 'HAD.TO', 'HAF.TO', 'HAI.TO', 'HAL.TO', 'HAZ.TO', 'HBA.TO', 'HBAL.TO', 'HBB.TO', 'HBD.TO', 'HBF.TO', 'HBGD.TO', 'HBIE.TO', 'HBIG.TO', 'HBIL.TO', 'HBKD.TO', 'HBKU.TO', 'HBLK.TO', 'HBM.TO', 'HBND.TO', 'HBNK.TO', 'HBP.TO', 'HBU.TO', 'HBUG.TO', 'HCA.TO', 'HCAL.TO', 'HCLN.TO', 'HCON.TO', 'HCRE.TO', 'HDGE.TO', 'HDIF.TO', 'HDIV.TO', 'HEB.TO', 'HED.TO', 'HEQL.TO', 'HEQT.TO', 'HERO.TO', 'HEU.TO', 'HEWB.TO', 'HFD.TO', 'HFG.TO', 'HFIN.TO', 'HFR.TO', 'HFU.TO', 'HGD.TO', 'HGGG.TO', 'HGR.TO', 'HGRW.TO', 'HGU.TO', 'HGY.TO', 'HHL.TO', 'HHLE.TO', 'HIG.TO', 'HIND.TO', 'HIU.TO', 'HIX.TO', 'HLF.TO', 'HLIF.TO', 'HLIT.TO', 'HLPR.TO', 'HLS.TO', 'HMAX.TO', 'HMMJ.TO', 'HMP.TO', 'HND.TO', 'HNU.TO', 'HOD.TO', 'HOU.TO', 'HPF.TO', 'HPR.TO', 'HPYM.TO', 'HPYT.TO', 'HQD.TO', 'HQU.TO', 'HRAA.TO', 'HRED.TO', 'HREU.TO', 'HRIF.TO', 'HRX.TO', 'HSAV.TO', 'HSD.TO', 'HSH.TO', 'HSU.TO', 'HTA.TO', 'HTAE.TO', 'HTB.TO', 'HUBL.TO', 'HUC.TO', 'HUG.TO', 'HULC.TO', 'HUM.TO', 'HUN.TO', 'HURA.TO', 'HUT.TO', 'HUTE.TO', 'HUTL.TO', 'HUTS.TO', 'HUV.TO', 'HUZ.TO', 'HWO.TO', 'HWX.TO', 'HXCN.TO', 'HXD.TO', 'HXDM.TO', 'HXE.TO', 'HXEM.TO', 'HXF.TO', 'HXH.TO', 'HXQ.TO', 'HXS.TO', 'HXT.TO', 'HXU.TO', 'HXX.TO', 'HYBR.TO', 'HYLD.TO', 'HZD.TO', 'HZU.TO', 'IAG.TO', 'IAU.TO', 'ICAE.TO', 'ICE.TO', 'ICPB.TO', 'ICTE.TO', 'IE.TO', 'IFA.TO', 'IFC.TO', 'IFP.TO', 'IFRF.TO', 'IGAF.TO', 'IGB.TO', 'IGEO.TO', 'IGET.TO', 'IGM.TO', 'IIAE.TO', 'IICE.TO', 'III.TO', 'IIMF.TO', 'IITE.TO', 'ILGB.TO', 'ILLM.TO', 'IMG.TO', 'IMO.TO', 'IMP.TO', 'INAI.TO', 'INCM.TO', 'INE.TO', 'INOC.TO', 'IPCO.TO', 'IPO.TO', 'IQD.TO', 'IS.TO', 'ISC.TO', 'ISCB.TO', 'ISO.TO', 'ISTE.TO', 'ITH.TO', 'IUAE.TO', 'IUCE.TO', 'IUMF.TO', 'IUTE.TO', 'IVN.TO', 'IVQ.TO', 'IWBE.TO', 'IXTE.TO', 'JAG.TO', 'JAPN.TO', 'JEPI.TO', 'JEPQ.TO', 'JOY.TO', 'JWEL.TO', 'K.TO', 'KBL.TO', 'KEC.TO', 'KEI.TO', 'KEL.TO', 'KEY.TO', 'KILO.TO', 'KITS.TO', 'KLS.TO', 'KNGC.TO', 'KNGU.TO', 'KNGX.TO', 'KNT.TO', 'KPT.TO', 'KRN.TO', 'KSI.TO', 'KXS.TO', 'L.TO', 'LAAC.TO', 'LABS.TO', 'LAC.TO', 'LAM.TO', 'LB.TO', 'LBS.TO', 'LCFS.TO', 'LCS.TO', 'LEAD.TO', 'LFE.TO', 'LGD.TO', 'LGO.TO', 'LIF.TO', 'LIFE.TO', 'LIRC.TO', 'LLHE.TO', 'LLYH.TO', 'LMAX.TO', 'LN.TO', 'LNF.TO', 'LNR.TO', 'LPAY.TO', 'LSPD.TO', 'LSPK.TO', 'LUC.TO', 'LUG.TO', 'LUN.TO', 'LYCT.TO', 'LYFR.TO', 'MAG.TO', 'MAL.TO', 'MARI.TO', 'MART.TO', 'MATR.TO', 'MBAL.TO', 'MBX.TO', 'MCAD.TO', 'MCB.TO', 'MCLC.TO', 'MCLV.TO', 'MCON.TO', 'MCSB.TO', 'MCSM.TO', 'MDA.TO', 'MDI.TO', 'MDIV.TO', 'MDNA.TO', 'MDP.TO', 'MDVD.TO', 'MEG.TO', 'MEQ.TO', 'MEQT.TO', 'MFC.TO', 'MFI.TO', 'MFT.TO', 'MG.TO', 'MGA.TO', 'MGAB.TO', 'MGB.TO', 'MGDV.TO', 'MGQE.TO', 'MGRW.TO', 'MHCD.TO', 'MINF.TO', 'MINN.TO', 'MINT.TO', 'MIQE.TO', 'MIVG.TO', 'MKB.TO', 'MKP.TO', 'MND.TO', 'MNO.TO', 'MNS.TO', 'MNT.TO', 'MNXT.TO', 'MNY.TO', 'MOGO.TO', 'MORE.TO', 'MPAY.TO', 'MPC.TO', 'MPVD.TO', 'MPY.TO', 'MRC.TO', 'MRD.TO', 'MRE.TO', 'MREL.TO', 'MRU.TO', 'MSA.TO', 'MSCL.TO', 'MSFH.TO', 'MSHE.TO', 'MSV.TO', 'MTAV.TO', 'MTL.TO', 'MTY.TO', 'MUB.TO', 'MULC.TO', 'MULV.TO', 'MUMC.TO', 'MUSA.TO', 'MUX.TO', 'MWLV.TO', 'MX.TO', 'MXG.TO', 'nan.TO', 'NALT.TO', 'NANO.TO', 'NCF.TO', 'NDIV.TO', 'NDM.TO', 'NEO.TO', 'NEXT.TO', 'NFI.TO', 'NG.TO', 'NGD.TO', 'NGDN.TO', 'NGEX.TO', 'NGPE.TO', 'NGT.TO', 'NGUP.TO', 'NHYB.TO', 'NINT.TO', 'NOA.TO', 'NPI.TO', 'NPK.TO', 'NPRF.TO', 'NPS.TO', 'NREA.TO', 'NRGY.TO', 'NSCB.TO', 'NSCC.TO', 'NSCE.TO', 'NSGE.TO', 'NSSB.TO', 'NTR.TO', 'NUAG.TO', 'NUBF.TO', 'NUMI.TO', 'NUSA.TO', 'NVA.TO', 'NVDH.TO', 'NVHE.TO', 'NVO.TO', 'NWC.TO', 'NXE.TO', 'NXF.TO', 'NXTG.TO', 'OBE.TO', 'OGC.TO', 'OGD.TO', 'OGI.TO', 'OLA.TO', 'OLY.TO', 'ONC.TO', 'ONEB.TO', 'ONEC.TO', 'ONEQ.TO', 'ONEX.TO', 'OPT.TO', 'OR.TO', 'ORA.TO', 'ORE.TO', 'ORV.TO', 'OTEX.TO', 'OVV.TO', 'PAAS.TO', 'PABF.TO', 'PACF.TO', 'PAGF.TO', 'PAY.TO', 'PAYF.TO', 'PAYL.TO', 'PAYM.TO', 'PAYS.TO', 'PBD.TO', 'PBH.TO', 'PBI.TO', 'PBL.TO', 'PCOR.TO', 'PD.TO', 'PDC.TO', 'PDF.TO', 'PDIV.TO', 'PDN.TO', 'PDV.TO', 'PEA.TO', 'PET.TO', 'PEY.TO', 'PFAA.TO', 'PFAE.TO', 'PFCB.TO', 'PFIA.TO', 'PFL.TO', 'PFLS.TO', 'PFMN.TO', 'PFSS.TO', 'PGIC.TO', 'PHR.TO', 'PHX.TO', 'PHYS.TO', 'PID.TO', 'PIF.TO', 'PIN.TO', 'PINC.TO', 'PKI.TO', 'PLDI.TO', 'PLV.TO', 'PME.TO', 'PMET.TO', 'PMIF.TO', 'PMM.TO', 'PMNT.TO', 'PNE.TO', 'PNP.TO', 'POU.TO', 'POW.TO', 'PPL.TO', 'PPLN.TO', 'PPR.TO', 'PPTA.TO', 'PR.TO', 'PRA.TO', 'PRB.TO', 'PREF.TO', 'PRL.TO', 'PRM.TO', 'PRN.TO', 'PRQ.TO', 'PRU.TO', 'PRYM.TO', 'PSA.TO', 'PSB.TO', 'PSD.TO', 'PSI.TO', 'PSK.TO', 'PSLV.TO', 'PTM.TO', 'PWI.TO', 'PXC.TO', 'PXS.TO', 'PXT.TO', 'PYF.TO', 'PYR.TO', 'PZA.TO', 'PZW.TO', 'QAH.TO', 'QASH.TO', 'QBB.TO', 'QBTC.TO', 'QBTL.TO', 'QCE.TO', 'QCLN.TO', 'QCN.TO', 'QDX.TO', 'QDXB.TO', 'QDXH.TO', 'QEBH.TO', 'QEBL.TO', 'QEC.TO', 'QEE.TO', 'QHY.TO', 'QIE.TO', 'QINF.TO', 'QIPT.TO', 'QLB.TO', 'QMAX.TO', 'QQC.TO', 'QQCC.TO', 'QQCE.TO', 'QQCI.TO', 'QQCL.TO', 'QQEQ.TO', 'QQJE.TO', 'QQJR.TO', 'QQQL.TO', 'QQQT.TO', 'QQQX.TO', 'QQQY.TO', 'QRC.TO', 'QRET.TO', 'QSB.TO', 'QSR.TO', 'QTLT.TO', 'QTRH.TO', 'QUB.TO', 'QUIG.TO', 'QUS.TO', 'QUU.TO', 'QXM.TO', 'RAAA.TO', 'RATE.TO', 'RBA.TO', 'RBNK.TO', 'RBO.TO', 'RBOT.TO', 'RBY.TO', 'RCD.TO', 'RCDC.TO', 'RCG.TO', 'RCH.TO', 'RDBH.TO', 'REAL.TO', 'RGQN.TO', 'RGQO.TO', 'RGQP.TO', 'RGQQ.TO', 'RGQR.TO', 'RGQS.TO', 'RID.TO', 'RIDH.TO', 'RIFI.TO', 'RIIN.TO', 'RING.TO', 'RIRA.TO', 'RIT.TO', 'RLB.TO', 'RMAX.TO', 'ROOT.TO', 'RPD.TO', 'RPDH.TO', 'RPF.TO', 'RPSB.TO', 'RQN.TO', 'RQO.TO', 'RQP.TO', 'RQQ.TO', 'RQR.TO', 'RQS.TO', 'RS.TO', 'RSI.TO', 'RTG.TO', 'RUBH.TO', 'RUBY.TO', 'RUD.TO', 'RUDB.TO', 'RUDC.TO', 'RUDH.TO', 'RUP.TO', 'RUQN.TO', 'RUQO.TO', 'RUQQ.TO', 'RUQR.TO', 'RUQS.TO', 'RUS.TO', 'RUSB.TO', 'RVX.TO', 'RXD.TO', 'RY.TO', 'S.TO', 'SAFE.TO', 'SAM.TO', 'SAP.TO', 'SAU.TO', 'SBC.TO', 'SBI.TO', 'SBT.TO', 'SCR.TO', 'SCY.TO', 'SDE.TO', 'SEA.TO', 'SEC.TO', 'SES.TO', 'SFC.TO', 'SFD.TO', 'SFI.TO', 'SFTC.TO', 'SGLD.TO', 'SGY.TO', 'SHLE.TO', 'SHOP.TO', 'SIA.TO', 'SII.TO', 'SIL.TO', 'SIS.TO', 'SJ.TO', 'SKE.TO', 'SKYY.TO', 'SLF.TO', 'SLR.TO', 'SLS.TO', 'SMAX.TO', 'SMC.TO', 'SMT.TO', 'SOBO.TO', 'SOIL.TO', 'SOLG.TO', 'SOY.TO', 'SPAY.TO', 'SPB.TO', 'SPFD.TO', 'SPLT.TO', 'SPPP.TO', 'SSL.TO', 'SSRM.TO', 'STC.TO', 'STCK.TO', 'STEP.TO', 'STGO.TO', 'STLR.TO', 'STN.TO', 'STPL.TO', 'SU.TO', 'SVA.TO', 'SVB.TO', 'SVI.TO', 'SVM.TO', 'SVR.TO', 'SWP.TO', 'SXI.TO', 'SXP.TO', 'SYLD.TO', 'SYZ.TO', 'T.TO', 'TA.TO', 'TAL.TO', 'TBAL.TO', 'TBCE.TO', 'TBCF.TO', 'TBCG.TO', 'TBIL.TO', 'TBL.TO', 'TBNK.TO', 'TC.TO', 'TCBN.TO', 'TCLB.TO', 'TCLV.TO', 'TCON.TO', 'TCS.TO', 'TCSB.TO', 'TCSH.TO', 'TCW.TO', 'TD.TO', 'TDB.TO', 'TDOC.TO', 'TEC.TO', 'TECH.TO', 'TECI.TO', 'TECX.TO', 'TERM.TO', 'TF.TO', 'TFII.TO', 'TFPM.TO', 'TGAF.TO', 'TGED.TO', 'TGFI.TO', 'TGGR.TO', 'TGO.TO', 'TGRE.TO', 'TGRO.TO', 'TH.TO', 'The.TO', 'THNC.TO', 'THU.TO', 'TI.TO', 'TIH.TO', 'TILV.TO', 'TINF.TO', 'TIPS.TO', 'TIXT.TO', 'TKN.TO', 'TKO.TO', 'TLF.TO', 'TLG.TO', 'TLO.TO', 'TLRY.TO', 'TLV.TO', 'TMQ.TO', 'TNZ.TO', 'TOT.TO', 'TOU.TO', 'TOWR.TO', 'TOY.TO', 'TPE.TO', 'TPRF.TO', 'TPU.TO', 'TPZ.TO', 'TQCD.TO', 'TQGD.TO', 'TQGM.TO', 'TQSM.TO', 'TRI.TO', 'TRP.TO', 'TRVI.TO', 'TRVL.TO', 'TRX.TO', 'TRZ.TO', 'TSAT.TO', 'TSK.TO', 'TSL.TO', 'TSND.TO', 'TSU.TO', 'TTNM.TO', 'TTP.TO', 'TTTX.TO', 'TUED.TO', 'TUEX.TO', 'TUHY.TO', 'TULB.TO', 'TULV.TO', 'TUSB.TO', 'TVE.TO', 'TVK.TO', 'TWC.TO', 'TWM.TO', 'TXF.TO', 'TXG.TO', 'TXP.TO', 'UDA.TO', 'UDIV.TO', 'UMAX.TO', 'UMI.TO', 'UNC.TO', 'UNI.TO', 'URB.TO', 'URC.TO', 'URE.TO', 'USA.TO', 'USCC.TO', 'USCL.TO', 'USSL.TO', 'USSX.TO', 'UTES.TO', 'UTIL.TO', 'VA.TO', 'VAB.TO', 'VALT.TO', 'VBAL.TO', 'VBNK.TO', 'VCB.TO', 'VCE.TO', 'VCIP.TO', 'VCM.TO', 'VCN.TO', 'VCNS.TO', 'VDU.TO', 'VDY.TO', 'VE.TO', 'VEE.TO', 'VEF.TO', 'VEQT.TO', 'VET.TO', 'VFV.TO', 'VGG.TO', 'VGH.TO', 'VGRO.TO', 'VGV.TO', 'VGZ.TO', 'VHI.TO', 'VI.TO', 'VIDY.TO', 'VIU.TO', 'VLB.TO', 'VLE.TO', 'VLN.TO', 'VMO.TO', 'VNP.TO', 'VOXR.TO', 'VQS.TO', 'VRE.TO', 'VRIF.TO', 'VRN.TO', 'VRTS.TO', 'VSB.TO', 'VSC.TO', 'VSP.TO', 'VUN.TO', 'VUS.TO', 'VVL.TO', 'VVO.TO', 'VVSG.TO', 'VXC.TO', 'VXM.TO', 'VZLA.TO', 'WCN.TO', 'WCP.TO', 'WDO.TO', 'WEED.TO', 'WEF.TO', 'WELL.TO', 'WFC.TO', 'WFG.TO', 'WGX.TO', 'WILD.TO', 'WJX.TO', 'WLLW.TO', 'WM.TO', 'WN.TO', 'WNDR.TO', 'WOMN.TO', 'WPK.TO', 'WPM.TO', 'WPRT.TO', 'WRG.TO', 'WRN.TO', 'WRX.TO', 'WSP.TO', 'WSRD.TO', 'WSRI.TO', 'WTE.TO', 'WXM.TO', 'X.TO', 'XAD.TO', 'XAGG.TO', 'XAGH.TO', 'XAM.TO', 'XAU.TO', 'XAW.TO', 'XBAL.TO', 'XBB.TO', 'XBM.TO', 'XCB.TO', 'XCBG.TO', 'XCBU.TO', 'XCD.TO', 'XCG.TO', 'XCH.TO', 'XCHP.TO', 'XCLN.TO', 'XCNS.TO', 'XCS.TO', 'XCSR.TO', 'XCV.TO', 'XDG.TO', 'XDGH.TO', 'XDIV.TO', 'XDNA.TO', 'XDRV.TO', 'XDSR.TO', 'XDU.TO', 'XDUH.TO', 'XDV.TO', 'XEB.TO', 'XEC.TO', 'XEF.TO', 'XEG.TO', 'XEH.TO', 'XEI.TO', 'XEM.TO', 'XEMC.TO', 'XEN.TO', 'XEQT.TO', 'XESG.TO', 'XETM.TO', 'XEU.TO', 'XEXP.TO', 'XFH.TO', 'XFLB.TO', 'XFLI.TO', 'XFLX.TO', 'XFN.TO', 'XFR.TO', 'XGB.TO', 'XGD.TO', 'XGI.TO', 'XGRO.TO', 'XHAK.TO', 'XHB.TO', 'XHC.TO', 'XHD.TO', 'XHU.TO', 'XHY.TO', 'XIC.TO', 'XID.TO', 'XIG.TO', 'XIGS.TO', 'XIN.TO', 'XINC.TO', 'XIT.TO', 'XIU.TO', 'XLB.TO', 'XLY.TO', 'XMA.TO', 'XMC.TO', 'XMD.TO', 'XMH.TO', 'XMI.TO', 'XML.TO', 'XMM.TO', 'XMS.TO', 'XMTM.TO', 'XMU.TO', 'XMV.TO', 'XMW.TO', 'XMY.TO', 'XPF.TO', 'XQB.TO', 'XQLT.TO', 'XQQ.TO', 'XQQU.TO', 'XRB.TO', 'XRE.TO', 'XSAB.TO', 'XSB.TO', 'XSC.TO', 'XSE.TO', 'XSEA.TO', 'XSEM.TO', 'XSH.TO', 'XSHG.TO', 'XSHU.TO', 'XSI.TO', 'XSMC.TO', 'XSMH.TO', 'XSP.TO', 'XSPC.TO', 'XST.TO', 'XSTB.TO', 'XSTH.TO', 'XSTP.TO', 'XSU.TO', 'XSUS.TO', 'XTC.TO', 'XTD.TO', 'XTG.TO', 'XTLH.TO', 'XTLT.TO', 'XTR.TO', 'XTRA.TO', 'XUH.TO', 'XUS.TO', 'XUSC.TO', 'XUSF.TO', 'XUSR.TO', 'XUT.TO', 'XUU.TO', 'XVLU.TO', 'XWD.TO', 'Y.TO', 'YCM.TO', 'YGR.TO', 'YRB.TO', 'ZACE.TO', 'ZAG.TO', 'ZBAL.TO', 'ZBBB.TO', 'ZBI.TO', 'ZBK.TO', 'ZCB.TO', 'ZCDB.TO', 'ZCH.TO', 'ZCLN.TO', 'ZCM.TO', 'ZCN.TO', 'ZCON.TO', 'ZCPB.TO', 'ZCS.TO', 'ZDB.TO', 'ZDH.TO', 'ZDI.TO', 'ZDJ.TO', 'ZDM.TO', 'ZDV.TO', 'ZDY.TO', 'ZEA.TO', 'ZEAT.TO', 'ZEB.TO', 'ZEF.TO', 'ZEM.TO', 'ZEO.TO', 'ZEQ.TO', 'ZEQT.TO', 'ZESG.TO', 'ZFC.TO', 'ZFH.TO', 'ZFL.TO', 'ZFM.TO', 'ZFN.TO', 'ZFS.TO', 'ZGB.TO', 'ZGD.TO', 'ZGI.TO', 'ZGLD.TO', 'ZGLH.TO', 'ZGQ.TO', 'ZGRN.TO', 'ZGRO.TO', 'ZGSB.TO', 'ZHP.TO', 'ZHU.TO', 'ZHY.TO', 'ZIC.TO', 'ZID.TO', 'ZIN.TO', 'ZIQ.TO', 'ZIU.TO', 'ZJG.TO', 'ZJK.TO', 'ZJPN.TO', 'ZLB.TO', 'ZLC.TO', 'ZLD.TO', 'ZLE.TO', 'ZLH.TO', 'ZLI.TO', 'ZLSC.TO', 'ZLSU.TO', 'ZLU.TO', 'ZMBS.TO', 'ZMI.TO', 'ZMID.TO', 'ZMMK.TO', 'ZMP.TO', 'ZMSB.TO', 'ZMT.TO', 'ZMU.TO', 'ZNQ.TO', 'ZPAY.TO', 'ZPH.TO', 'ZPL.TO', 'ZPR.TO', 'ZPS.TO', 'ZPW.TO', 'ZQB.TO', 'ZQQ.TO', 'ZRE.TO', 'ZRR.TO', 'ZSB.TO', 'ZSDB.TO', 'ZSML.TO', 'ZSP.TO', 'ZST.TO', 'ZSU.TO', 'ZTIP.TO', 'ZUAG.TO', 'ZUB.TO', 'ZUCM.TO', 'ZUD.TO', 'ZUE.TO', 'ZUGE.TO', 'ZUH.TO', 'ZUP.TO', 'ZUQ.TO', 'ZUT.TO', 'ZVC.TO', 'ZVU.TO', 'ZWA.TO', 'ZWB.TO', 'ZWC.TO', 'ZWE.TO', 'ZWEN.TO', 'ZWG.TO', 'ZWH.TO', 'ZWHC.TO', 'ZWK.TO', 'ZWP.TO', 'ZWQT.TO', 'ZWS.TO', 'ZWT.TO', 'ZWU.TO', 'ZXM.TO', 'ZZZD.TO']

In [ ]:
tickers = yf.Tickers(symbols_array)
# ticker_data = tickers.download(period='1mo', interval='1d', group_by='ticker')

# sample = symbols_array[0:2]
# sample
# fetch_canadian_stocks_data(symbols_array[0:100])

In [ ]:
ticker_data

Ticker     ACX.TO                                                  ACB.TO  \
Price        Open  High   Low Close  Volume Dividends Stock Splits   Open
Date
2024-12-16   6.54  6.54  6.44  6.48   24200       0.0          0.0   6.08
2024-12-17   6.45  6.46  6.35  6.43   33200       0.0          0.0   6.09
2024-12-18   6.43  6.66  6.43  6.47  121300       0.0          0.0   6.35
2024-12-19   6.53  6.53  6.30  6.30   42700       0.0          0.0   6.12
2024-12-20   6.47  6.47  6.25  6.25   17100       0.0          0.0   5.87
2024-12-23   6.25  6.30  6.19  6.26   23600       0.0          0.0   6.25
2024-12-24   6.26  6.36  6.22  6.26  379500       0.0          0.0   6.14
2024-12-27   6.30  6.39  6.28  6.28  118800       0.0          0.0   6.16
2024-12-30   6.29  6.29  6.12  6.22   12300       0.0          0.0   6.10
2024-12-31   6.22  6.45  6.22  6.45  256900       0.0          0.0   6.07
2025-01-02   6.82  6.82  6.32  6.50   90300       0.0          0.0   6.19
2025-01-03   6.51  6.61  6.51  6.58   71200       0.0          0.0   6.56
2025-01-06   6.57  6.62  6.55  6.56   95800       0.0          0.0   6.74
2025-01-07   6.51  6.60  6.47  6.58  619900       0.0          0.0   6.68
2025-01-08   6.59  6.68  6.59  6.65  444600       0.0          0.0   6.63
2025-01-09   6.65  6.69  6.56  6.58  152800       0.0          0.0   6.33
2025-01-10   6.60  6.70  6.59  6.66   69500       0.0          0.0   6.27
2025-01-13   6.69  6.70  6.55  6.57   50800       0.0          0.0   5.99
2025-01-14   6.56  6.73  6.55  6.73  294900       0.0          0.0   5.83
2025-01-15   6.75  6.93  6.73  6.90  111600       0.0          0.0   5.73

Ticker                   ... AAUC.TO                        ACD.TO        \
Price       High    Low  ...  Volume Dividends Stock Splits   Open  High
Date                     ...
2024-12-16  6.25  6.040  ...  490900       0.0          0.0   3.78  3.78
2024-12-17  6.43  6.090  ...  430200       0.0          0.0   3.79  3.79
2024-12-18  6.48  6.080  ...  496200       0.0          0.0   3.75  3.75
2024-12-19  6.25  5.880  ...  683500       0.0          0.0   3.74  3.75
2024-12-20  6.22  5.760  ...  980900       0.0          0.0   3.75  3.85
2024-12-23  6.36  6.030  ...  253900       0.0          0.0   3.93  3.93
2024-12-24  6.26  6.105  ...   94800       0.0          0.0   3.97  3.98
2024-12-27  6.34  6.060  ...  125100       0.0          0.0   3.86  3.86
2024-12-30  6.13  5.930  ...  157100       0.0          0.0   3.85  3.85
2024-12-31  6.15  5.860  ...  211000       0.0          0.0   3.86  3.86
2025-01-02  6.77  6.190  ...  300200       0.0          0.0   3.95  3.95
2025-01-03  6.81  6.460  ...  235000       0.0          0.0   3.98  4.00
2025-01-06  6.93  6.650  ...  217500       0.0          0.0   4.00  4.00
2025-01-07  6.86  6.630  ...  270400       0.0          0.0   4.00  4.00
2025-01-08  6.63  6.240  ...  639700       0.0          0.0   4.00  4.00
2025-01-09  6.34  6.260  ...  325700       0.0          0.0   3.99  3.99
2025-01-10  6.27  5.920  ...  252300       0.0          0.0   3.90  3.90
2025-01-13  6.00  5.640  ...  309300       0.0          0.0   3.71  3.94
2025-01-14  5.88  5.620  ...  299500       0.0          0.0   3.77  3.77
2025-01-15  5.83  5.630  ...  381400       0.0          0.0   3.90  3.90

Ticker
Price        Low Close Volume Dividends Stock Splits
Date
2024-12-16  3.75  3.76   3100       0.0          0.0
2024-12-17  3.79  3.79    100       0.0          0.0
2024-12-18  3.71  3.71    400       0.0          0.0
2024-12-19  3.73  3.73    300       0.0          0.0
2024-12-20  3.68  3.75   6900       0.0          0.0
2024-12-23  3.80  3.80    700       0.0          0.0
2024-12-24  3.92  3.92    300       0.0          0.0
2024-12-27  3.80  3.80   1100       0.0          0.0
2024-12-30  3.85  3.85    100       0.0          0.0
2024-12-31  3.86  3.86    100       0.0          0.0
2025-01-02  3.90  3.92   2900       0.0          0.0
2025-01-03  3.91  4.00   1400       0.0          0.0
2025-01-06  4.00  4.00    300       0.0          0.0
2025-01-07  4.00  4.00    100       0.0          0.0
2025-01-08  3.90  3.90   2200       0.0          0.0
2025-01-09  3.80  3.81   2400       0.0          0.0
2025-01-10  3.38  3.64  15300       0.0          0.0
2025-01-13  3.70  3.70   1000       0.0          0.0
2025-01-14  3.65  3.65   2500       0.0          0.0
2025-01-15  3.70  3.70   3000       0.0          0.0

[20 rows x 71 columns]

In [ ]:
ticker_data.to_csv('ticker_download.csv', index=False)

In [ ]:
tickers_info_df = fetch_tickers_info(symbols_array)

Fetched info for AAB.TO
Fetched info for AAUC.TO
Fetched info for AAV.TO
Fetched info for ABX.TO
Fetched info for AC.TO
Fetched info for ACAA.TO
Fetched info for ACB.TO
Fetched info for ACD.TO
Fetched info for ACQ.TO
Fetched info for ACX.TO
Fetched info for ADCO.TO
Fetched info for ADEN.TO
Fetched info for ADIV.TO
Fetched info for ADN.TO
Fetched info for AEG.TO
Fetched info for AEM.TO
Fetched info for AFN.TO
Fetched info for AG.TO
Fetched info for AGG.TO
Fetched info for AGI.TO
Fetched info for AI.TO
Fetched info for AIDX.TO
Fetched info for AIF.TO
Fetched info for AIGO.TO
Fetched info for AII.TO
Fetched info for AIM.TO
Fetched info for ALA.TO
Fetched info for ALC.TO
Fetched info for ALS.TO
Fetched info for ALYA.TO
Fetched info for AMAX.TO
Fetched info for AMC.TO
Fetched info for AMHE.TO
Fetched info for AMM.TO
Fetched info for AMZH.TO
Fetched info for AND.TO
Fetched info for ANRG.TO
Fetched info for AOI.TO
Fetched info for AOT.TO
Fetched info for APLI.TO
Fetched info for APM.TO
Fetched info for APS.TO
Fetched info for AQN.TO
Fetched info for ARA.TO
Fetched info for ARB.TO
Fetched info for ARE.TO
Fetched info for ARG.TO
Fetched info for ARIS.TO
Fetched info for ARTI.TO
Fetched info for ARX.TO
Fetched info for ASCU.TO
Fetched info for ASM.TO
Fetched info for ASND.TO
Fetched info for ASTL.TO
Fetched info for ATCU.TO
Fetched info for ATD.TO
Fetched info for ATH.TO
Fetched info for ATRL.TO
Fetched info for ATS.TO
Fetched info for ATSX.TO
Fetched info for ATZ.TO
Fetched info for AUMN.TO
Fetched info for AVCN.TO
Fetched info for AVL.TO
Fetched info for AVNT.TO
Fetched info for AW.TO
Fetched info for AYA.TO
Fetched info for BABY.TO
Fetched info for BAM.TO
Fetched info for BANK.TO
Fetched info for BASE.TO
Fetched info for BB.TO
Fetched info for BBUC.TO
Fetched info for BCE.TO
Fetched info for BCHT.TO
Fetched info for BCT.TO
Fetched info for BDGI.TO
Fetched info for BDI.TO
Fetched info for BDIV.TO
Fetched info for BDT.TO
Fetched info for BEPC.TO
Fetched info for BEPR.TO
Fetched info for BESG.TO
Fetched info for BFIN.TO
Fetched info for BGC.TO
Fetched info for BGU.TO
Fetched info for BHC.TO
Fetched info for BIPC.TO
Fetched info for BIR.TO
Fetched info for BITF.TO
Fetched info for BITI.TO
Fetched info for BK.TO
Fetched info for BKCC.TO
Fetched info for BKCL.TO
Fetched info for BKI.TO
Fetched info for BLCO.TO
Fetched info for BLDP.TO
Fetched info for BLN.TO
Fetched info for BLOV.TO
Fetched info for BLX.TO
Fetched info for BMAX.TO
Fetched info for BMO.TO
Fetched info for BN.TO
Fetched info for BNC.TO
Fetched info for BND.TO
Fetched info for BNE.TO
Fetched info for BNG.TO
Fetched info for BNK.TO
Fetched info for BNKL.TO
Fetched info for BNS.TO
Fetched info for BNT.TO
Fetched info for BOND.TO
Fetched info for BOS.TO
Fetched info for BPRF.TO
Fetched info for BR.TO
Fetched info for BRAG.TO
Fetched info for BRE.TO
Fetched info for BREA.TO
Fetched info for BRMI.TO
Fetched info for BRY.TO
Fetched info for BSKT.TO
Fetched info for BSX.TO
Fetched info for BTCC.TO
Fetched info for BTCQ.TO
Fetched info for BTCY.TO
Fetched info for BTE.TO
Fetched info for BTO.TO
Fetched info for BU.TO
Fetched info for BUI.TO
Fetched info for BXF.TO
Fetched info for BYD.TO
Fetched info for BYL.TO
Fetched info for CACB.TO
Fetched info for CAE.TO
Fetched info for CAFR.TO
Fetched info for CAGG.TO
Fetched info for CAGS.TO
Fetched info for CALL.TO
Fetched info for CANL.TO
Fetched info for CAPG.TO
Fetched info for CAPI.TO
Fetched info for CAPM.TO
Fetched info for CAPW.TO
Fetched info for CARB.TO
Fetched info for CARS.TO
Fetched info for CAS.TO
Fetched info for CASH.TO
Fetched info for CBAL.TO
Fetched info for CBCX.TO
Fetched info for CBGR.TO
Fetched info for CBH.TO
Fetched info for CBIL.TO
Fetched info for CBIN.TO
Fetched info for CBL.TO
Fetched info for CBND.TO
Fetched info for CBNK.TO
Fetched info for CBO.TO
Fetched info for CBUG.TO
Fetched info for CCA.TO
Fetched info for CCBI.TO
Fetched info for CCEI.TO
Fetched info for CCM.TO
Fetched info for CCNS.TO
Fetched info for CCNV.TO
Fetched info for CCO.TO
Fetched info for CCOM.TO
Fetched info for CCRE.TO
Fetched info for CDEF.TO
Fetched info for CDIV.TO
Fetched info for CDLB.TO
Fetched info for CDNA.TO
Fetched info for CDR.TO
Fetched info for CDZ.TO
Fetched info for CEF.TO
Fetched info for CEMI.TO
Fetched info for CEMX.TO
Fetched info for CEQT.TO
Fetched info for CEU.TO
Fetched info for CEW.TO
Fetched info for CF.TO
Fetched info for CFF.TO
Fetched info for CFLX.TO
Fetched info for CFP.TO
Fetched info for CFRT.TO
Fetched info for CFW.TO
Fetched info for CFX.TO
Fetched info for CG.TO
Fetched info for CGAA.TO
Fetched info for CGBI.TO
Fetched info for CGDV.TO
Fetched info for CGG.TO
Fetched info for CGHY.TO
Fetched info for CGI.TO
Fetched info for CGIN.TO
Fetched info for CGL.TO
Fetched info for CGLO.TO
Fetched info for CGO.TO
Fetched info for CGR.TO
Fetched info for CGRA.TO
Fetched info for CGRE.TO
Fetched info for CGRN.TO
Fetched info for CGRO.TO
Fetched info for CGX.TO
Fetched info for CGXF.TO
Fetched info for CGY.TO
Fetched info for CHPS.TO
Fetched info for CHR.TO
Fetched info for CIA.TO
Fetched info for CIAI.TO
Fetched info for CIBR.TO
Fetched info for CIC.TO
Fetched info for CIEH.TO
Fetched info for CIEI.TO
Fetched info for CIEM.TO
Fetched info for CIF.TO
Fetched info for CIGI.TO
Fetched info for CINF.TO
Fetched info for CINT.TO
Fetched info for CINV.TO
Fetched info for CIX.TO
Fetched info for CJ.TO
Fetched info for CJT.TO
Fetched info for CKI.TO
Fetched info for CLF.TO
Fetched info for CLG.TO
Fetched info for CLML.TO
Fetched info for CLS.TO
Fetched info for CM.TO
Fetched info for CMAG.TO
Fetched info for CMAR.TO
Fetched info for CMDO.TO
Fetched info for CMG.TO
Fetched info for CMGG.TO
Fetched info for CMNY.TO
Fetched info for CMOM.TO
Fetched info for CMR.TO
Fetched info for CMVX.TO
Fetched info for CNCC.TO
Fetched info for CNCL.TO
Fetched info for CNDX.TO
Fetched info for CNE.TO
Fetched info for CNL.TO
Fetched info for CNQ.TO
Fetched info for CNR.TO
Fetched info for CNT.TO
Fetched info for CNV.TO
Fetched info for COG.TO
Fetched info for COMM.TO
Fetched info for COPP.TO
Fetched info for COPR.TO
Fetched info for CORE.TO
Fetched info for COW.TO
Fetched info for CP.TO
Fetched info for CPD.TO
Fetched info for CPH.TO
Fetched info for CPLS.TO
Fetched info for CPX.TO
Fetched info for CRDL.TO
Fetched info for CRED.TO
Fetched info for CRON.TO
Fetched info for CROP.TO
Fetched info for CRP.TO
Fetched info for CRRX.TO
Fetched info for CRWN.TO
Fetched info for CS.TO
Fetched info for CSAV.TO
Fetched info for CSBI.TO
Fetched info for CSCI.TO
Fetched info for CSU.TO
Fetched info for CTC.TO
Fetched info for CTS.TO
Fetched info for CTX.TO
Fetched info for CU.TO
Fetched info for CUBD.TO
Fetched info for CUD.TO
Fetched info for CUDV.TO
Fetched info for CUEH.TO
Fetched info for CUEI.TO
Fetched info for CURA.TO
Fetched info for CUTL.TO
Fetched info for CVD.TO
Fetched info for CVE.TO
Fetched info for CVG.TO
Fetched info for CVLU.TO
Fetched info for CVO.TO
Fetched info for CWB.TO
Fetched info for CWEB.TO
Fetched info for CWL.TO
Fetched info for CWW.TO
Fetched info for CXB.TO
Fetched info for CXF.TO
Fetched info for CXI.TO
Fetched info for CYB.TO
Fetched info for CYBR.TO
Fetched info for CYH.TO
Fetched info for DAMG.TO
Fetched info for DANC.TO
Fetched info for DATA.TO
Fetched info for DAY.TO
Fetched info for DBM.TO
Fetched info for DBO.TO
Fetched info for DCBC.TO
Fetched info for DCBO.TO
Fetched info for DCC.TO
Fetched info for DCG.TO
Fetched info for DCM.TO
Fetched info for DCP.TO
Fetched info for DCS.TO
Fetched info for DCU.TO
Fetched info for DF.TO
Fetched info for DFN.TO
Fetched info for DFY.TO
Fetched info for DGR.TO
Fetched info for DGRC.TO
Fetched info for DGS.TO
Fetched info for DIAM.TO
Fetched info for DISC.TO
Fetched info for DIV.TO
Fetched info for DIVS.TO
Fetched info for DLCG.TO
Fetched info for DLR.TO
Fetched info for DMEC.TO
Fetched info for DMEI.TO
Fetched info for DMEU.TO
Fetched info for DML.TO
Fetched info for DND.TO
Fetched info for DNG.TO
Fetched info for DNTL.TO
Fetched info for DOL.TO
Fetched info for DOO.TO
Fetched info for DPM.TO
Fetched info for DR.TO
Fetched info for DRCU.TO
Fetched info for DRFC.TO
Fetched info for DRFD.TO
Fetched info for DRFE.TO
Fetched info for DRFG.TO
Fetched info for DRFU.TO
Fetched info for DRM.TO
Fetched info for DRMC.TO
Fetched info for DRMD.TO
Fetched info for DRME.TO
Fetched info for DRMU.TO
Fetched info for DRT.TO
Fetched info for DRX.TO
Fetched info for DS.TO
Fetched info for DSAE.TO
Fetched info for DSG.TO
Fetched info for DSV.TO
Fetched info for DTOL.TO
Fetched info for DXAU.TO
Fetched info for DXB.TO
Fetched info for DXBB.TO
Fetched info for DXBC.TO
Fetched info for DXBG.TO
Fetched info for DXBU.TO
Fetched info for DXC.TO
Fetched info for DXCB.TO
Fetched info for DXCO.TO
Fetched info for DXCP.TO
Fetched info for DXDB.TO
Fetched info for DXEM.TO
Fetched info for DXET.TO
Fetched info for DXF.TO
Fetched info for DXG.TO
Fetched info for DXGE.TO
Fetched info for DXIF.TO
Error fetching data for DXMO.TO: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Fetched info for DXN.TO
Fetched info for DXO.TO
Fetched info for DXP.TO
Fetched info for DXQ.TO
Fetched info for DXR.TO
Fetched info for DXT.TO
Fetched info for DXU.TO
Fetched info for DXUS.TO
Fetched info for DXV.TO
Fetched info for DXW.TO
Fetched info for DXZ.TO
Fetched info for DYA.TO
Fetched info for E.TO
Fetched info for EAGR.TO
Fetched info for EARN.TO
Fetched info for EBIT.TO
Fetched info for EBNK.TO
Fetched info for ECN.TO
Fetched info for ECO.TO
Fetched info for ECOR.TO
Fetched info for EDGE.TO
Fetched info for EDGF.TO
Fetched info for EDR.TO
Fetched info for EDT.TO
Fetched info for EDV.TO
Fetched info for EFN.TO
Fetched info for EFR.TO
Fetched info for EFX.TO
Fetched info for EGLX.TO
Fetched info for EIF.TO
Fetched info for ELD.TO
Fetched info for ELEF.TO
Fetched info for ELF.TO
Fetched info for ELO.TO
Fetched info for ELR.TO
Fetched info for ELVA.TO
Fetched info for EMA.TO
Fetched info for EMAX.TO
Fetched info for ENB.TO
Fetched info for ENCC.TO
Fetched info for ENCL.TO
Fetched info for ENGH.TO
Fetched info for ENS.TO
Fetched info for EPRX.TO
Fetched info for EQB.TO
Fetched info for EQCC.TO
Fetched info for EQCL.TO
Fetched info for EQL.TO
Fetched info for EQLI.TO
Fetched info for EQX.TO
Fetched info for ERD.TO
Fetched info for ERO.TO
Fetched info for ESG.TO
Fetched info for ESGA.TO
Fetched info for ESGB.TO
Fetched info for ESGC.TO
Fetched info for ESGE.TO
Fetched info for ESGF.TO
Fetched info for ESGG.TO
Fetched info for ESGH.TO
Fetched info for ESGY.TO
Fetched info for ESI.TO
Fetched info for ESM.TO
Fetched info for ESP.TO
Fetched info for ESPX.TO
Fetched info for ET.TO
Fetched info for ETC.TO
Fetched info for ETG.TO
Fetched info for ETHH.TO
Fetched info for ETHI.TO
Fetched info for ETHQ.TO
Fetched info for ETHR.TO
Fetched info for ETHY.TO
Fetched info for ETP.TO
Fetched info for ETSX.TO
Fetched info for EVO.TO
Fetched info for EVT.TO
Fetched info for EXE.TO
Fetched info for EXN.TO
Fetched info for EXRO.TO
Fetched info for FAP.TO
Fetched info for FAR.TO
Fetched info for FBGO.TO
Fetched info for FBT.TO
Fetched info for FBTC.TO
Fetched info for FC.TO
Fetched info for FCCD.TO
Fetched info for FCCQ.TO
Fetched info for FCCV.TO
Fetched info for FCEM.TO
Fetched info for FCGI.TO
Fetched info for FCID.TO
Fetched info for FCII.TO
Fetched info for FCIQ.TO
Fetched info for FCIV.TO
Fetched info for FCMI.TO
Fetched info for FCQH.TO
Fetched info for FCRR.TO
Fetched info for FCUD.TO
Fetched info for FCUH.TO
Fetched info for FCUQ.TO
Fetched info for FCUV.TO
Fetched info for FCVH.TO
Fetched info for FDL.TO
Fetched info for FDN.TO
Fetched info for FDY.TO
Fetched info for FEC.TO
Fetched info for FETH.TO
Fetched info for FF.TO
Fetched info for FFH.TO
Fetched info for FFM.TO
Fetched info for FFN.TO
Fetched info for FGB.TO
Fetched info for FGEB.TO
Fetched info for FGEP.TO
Fetched info for FGGE.TO
Fetched info for FGO.TO
Fetched info for FGOV.TO
Fetched info for FGRW.TO
Fetched info for FHG.TO
Fetched info for FHH.TO
Fetched info for FHI.TO
Fetched info for FHIS.TO
Fetched info for FHQ.TO
Fetched info for FIE.TO
Fetched info for FIG.TO
Fetched info for FIL.TO
Fetched info for FINC.TO
Fetched info for FINE.TO
Fetched info for FINO.TO
Fetched info for FLCI.TO
Fetched info for FLCP.TO
Fetched info for FLGA.TO
Fetched info for FLI.TO
Fetched info for FLNT.TO
Fetched info for FLOW.TO
Fetched info for FLSD.TO
Fetched info for FLUS.TO
Fetched info for FLX.TO
Fetched info for FM.TO
Fetched info for FMAX.TO
Fetched info for FN.TO
Fetched info for FNV.TO
Fetched info for FOM.TO
Fetched info for FOOD.TO
Fetched info for FORA.TO
Fetched info for FOUR.TO
Fetched info for FPR.TO
Fetched info for FRU.TO
Fetched info for FRX.TO
Fetched info for FSB.TO
Fetched info for FSF.TO
Fetched info for FSL.TO
Fetched info for FST.TO
Fetched info for FSV.TO
Fetched info for FSY.TO
Fetched info for FSZ.TO
Fetched info for FT.TO
Fetched info for FTG.TO
Fetched info for FTHI.TO
Fetched info for FTN.TO
Fetched info for FTS.TO
Fetched info for FTT.TO
Fetched info for FTU.TO
Fetched info for FURY.TO
Fetched info for FVI.TO
Fetched info for FVL.TO
Fetched info for FXM.TO
Fetched info for G.TO
Fetched info for GATO.TO
Fetched info for GAU.TO
Fetched info for GBAL.TO
Fetched info for GBT.TO
Fetched info for GCBD.TO
Fetched info for GCFE.TO
Fetched info for GCG.TO
Fetched info for GCL.TO
Fetched info for GCNS.TO
Fetched info for GCSC.TO
Fetched info for GCTB.TO
Fetched info for GCU.TO
Fetched info for GDC.TO
Fetched info for GDEP.TO
Fetched info for GDI.TO
Fetched info for GDL.TO
Fetched info for GDPY.TO
Fetched info for GDV.TO
Fetched info for GEC.TO
Fetched info for GEI.TO
Fetched info for GENM.TO
Fetched info for GEO.TO
Fetched info for GEQT.TO
Fetched info for GFL.TO
Fetched info for GFP.TO
Fetched info for GFR.TO
Fetched info for GGD.TO
Fetched info for GGRO.TO
Fetched info for GH.TO
Fetched info for GIGC.TO
Fetched info for GIL.TO
Fetched info for GIQG.TO
Fetched info for GIQU.TO
Fetched info for GLCC.TO
Fetched info for GLDX.TO
Fetched info for GLO.TO
Fetched info for GLXY.TO
Fetched info for GMIN.TO
Fetched info for GMTN.TO
Fetched info for GMX.TO
Fetched info for GOLD.TO
Fetched info for GOOS.TO
Fetched info for GPMD.TO
Fetched info for GRA.TO
Fetched info for GRC.TO
Fetched info for GRCC.TO
Fetched info for GRGD.TO
Fetched info for GRID.TO
Fetched info for GRN.TO
Fetched info for GRNI.TO
Fetched info for GRO.TO
Fetched info for GSY.TO
Fetched info for GTE.TO
Fetched info for GTWO.TO
Fetched info for GUD.TO
Fetched info for GURU.TO
Fetched info for GVC.TO
Fetched info for GWO.TO
Fetched info for GXE.TO
Fetched info for H.TO
Fetched info for HAB.TO
Fetched info for HAC.TO
Fetched info for HAD.TO
Fetched info for HAF.TO
Fetched info for HAI.TO
Fetched info for HAL.TO
Fetched info for HAZ.TO
Fetched info for HBA.TO
Fetched info for HBAL.TO
Fetched info for HBB.TO
Fetched info for HBD.TO
Fetched info for HBF.TO
Fetched info for HBGD.TO
Fetched info for HBIE.TO
Fetched info for HBIG.TO
Fetched info for HBIL.TO
Fetched info for HBKD.TO
Fetched info for HBKU.TO
Fetched info for HBLK.TO
Fetched info for HBM.TO
Fetched info for HBND.TO
Fetched info for HBNK.TO
Fetched info for HBP.TO
Fetched info for HBU.TO
Fetched info for HBUG.TO
Fetched info for HCA.TO
Fetched info for HCAL.TO
Fetched info for HCLN.TO
Fetched info for HCON.TO
Fetched info for HCRE.TO
Fetched info for HDGE.TO
Fetched info for HDIF.TO
Fetched info for HDIV.TO
Fetched info for HEB.TO
Fetched info for HED.TO
Fetched info for HEQL.TO
Fetched info for HEQT.TO
Fetched info for HERO.TO
Fetched info for HEU.TO
Fetched info for HEWB.TO
Fetched info for HFD.TO
Fetched info for HFG.TO
Fetched info for HFIN.TO
Fetched info for HFR.TO
Fetched info for HFU.TO
Fetched info for HGD.TO
Fetched info for HGGG.TO
Fetched info for HGR.TO
Fetched info for HGRW.TO
Fetched info for HGU.TO
Fetched info for HGY.TO
Fetched info for HHL.TO
Fetched info for HHLE.TO
Fetched info for HIG.TO
Fetched info for HIND.TO
Fetched info for HIU.TO
Fetched info for HIX.TO
Fetched info for HLF.TO
Fetched info for HLIF.TO
Fetched info for HLIT.TO
Fetched info for HLPR.TO
Fetched info for HLS.TO
Fetched info for HMAX.TO
Fetched info for HMMJ.TO
Fetched info for HMP.TO
Fetched info for HND.TO
Fetched info for HNU.TO
Fetched info for HOD.TO
Fetched info for HOU.TO
Fetched info for HPF.TO
Fetched info for HPR.TO
Fetched info for HPYM.TO
Fetched info for HPYT.TO
Fetched info for HQD.TO
Fetched info for HQU.TO
Fetched info for HRAA.TO
Fetched info for HRED.TO
Fetched info for HREU.TO
Fetched info for HRIF.TO
Fetched info for HRX.TO
Fetched info for HSAV.TO
Fetched info for HSD.TO
Fetched info for HSH.TO
Fetched info for HSU.TO
Fetched info for HTA.TO
Fetched info for HTAE.TO
Fetched info for HTB.TO
Fetched info for HUBL.TO
Fetched info for HUC.TO
Fetched info for HUG.TO
Fetched info for HULC.TO
Fetched info for HUM.TO
Fetched info for HUN.TO
Fetched info for HURA.TO
Fetched info for HUT.TO
Fetched info for HUTE.TO
Fetched info for HUTL.TO
Fetched info for HUTS.TO
Fetched info for HUV.TO
Fetched info for HUZ.TO
Fetched info for HWO.TO
Fetched info for HWX.TO
Fetched info for HXCN.TO
Fetched info for HXD.TO
Fetched info for HXDM.TO
Fetched info for HXE.TO
Fetched info for HXEM.TO
Fetched info for HXF.TO
Fetched info for HXH.TO
Fetched info for HXQ.TO
Fetched info for HXS.TO
Fetched info for HXT.TO
Fetched info for HXU.TO
Fetched info for HXX.TO
Fetched info for HYBR.TO
Fetched info for HYLD.TO
Fetched info for HZD.TO
Fetched info for HZU.TO
Fetched info for IAG.TO
Fetched info for IAU.TO
Fetched info for ICAE.TO
Fetched info for ICE.TO
Fetched info for ICPB.TO
Fetched info for ICTE.TO
Fetched info for IE.TO
Fetched info for IFA.TO
Fetched info for IFC.TO
Fetched info for IFP.TO
Fetched info for IFRF.TO
Fetched info for IGAF.TO
Fetched info for IGB.TO
Fetched info for IGEO.TO
Fetched info for IGET.TO
Fetched info for IGM.TO
Fetched info for IIAE.TO
Fetched info for IICE.TO
Fetched info for III.TO
Fetched info for IIMF.TO
Fetched info for IITE.TO
Fetched info for ILGB.TO
Fetched info for ILLM.TO
Fetched info for IMG.TO
Fetched info for IMO.TO
Fetched info for IMP.TO
Fetched info for INAI.TO
Fetched info for INCM.TO
Fetched info for INE.TO
Fetched info for INOC.TO
Fetched info for IPCO.TO
Fetched info for IPO.TO
Fetched info for IQD.TO
Fetched info for IS.TO
Fetched info for ISC.TO
Fetched info for ISCB.TO
Fetched info for ISO.TO
Fetched info for ISTE.TO
Fetched info for ITH.TO
Fetched info for IUAE.TO
Fetched info for IUCE.TO
Fetched info for IUMF.TO
Fetched info for IUTE.TO
Fetched info for IVN.TO
Fetched info for IVQ.TO
Fetched info for IWBE.TO
Fetched info for IXTE.TO
Fetched info for JAG.TO
Fetched info for JAPN.TO
Fetched info for JEPI.TO
Fetched info for JEPQ.TO
Fetched info for JOY.TO
Fetched info for JWEL.TO
Fetched info for K.TO
Fetched info for KBL.TO
Fetched info for KEC.TO
Fetched info for KEI.TO
Fetched info for KEL.TO
Fetched info for KEY.TO
Fetched info for KILO.TO
Fetched info for KITS.TO
Fetched info for KLS.TO
Fetched info for KNGC.TO
Fetched info for KNGU.TO
Fetched info for KNGX.TO
Fetched info for KNT.TO
Fetched info for KPT.TO
Fetched info for KRN.TO
Fetched info for KSI.TO
Fetched info for KXS.TO
Fetched info for L.TO
Fetched info for LAAC.TO
Fetched info for LABS.TO
Fetched info for LAC.TO
Fetched info for LAM.TO
Fetched info for LB.TO
Fetched info for LBS.TO
Fetched info for LCFS.TO
Fetched info for LCS.TO
Fetched info for LEAD.TO
Fetched info for LFE.TO
Fetched info for LGD.TO
Fetched info for LGO.TO
Fetched info for LIF.TO
Fetched info for LIFE.TO
Fetched info for LIRC.TO
Fetched info for LLHE.TO
Fetched info for LLYH.TO
Fetched info for LMAX.TO
Fetched info for LN.TO
Fetched info for LNF.TO
Fetched info for LNR.TO
Fetched info for LPAY.TO
Fetched info for LSPD.TO
Fetched info for LSPK.TO
Fetched info for LUC.TO
Fetched info for LUG.TO
Fetched info for LUN.TO
Fetched info for LYCT.TO

ERROR:yfinance:404 Client Error: Not Found for url: https://query2.finance.yahoo.com/v10/finance/quoteSummary/NAN.TO?modules=financialData%2CquoteType%2CdefaultKeyStatistics%2CassetProfile%2CsummaryDetail&corsDomain=finance.yahoo.com&formatted=false&symbol=NAN.TO&crumb=NtgihVrZ0xp

Fetched info for nan.TO
Fetched info for NALT.TO
Fetched info for NANO.TO
Fetched info for NCF.TO
Fetched info for NDIV.TO
Fetched info for NDM.TO
Fetched info for NEO.TO
Fetched info for NEXT.TO
Fetched info for NFI.TO
Fetched info for NG.TO
Fetched info for NGD.TO
Fetched info for NGDN.TO
Fetched info for NGEX.TO
Fetched info for NGPE.TO
Fetched info for NGT.TO
Fetched info for NGUP.TO
Fetched info for NHYB.TO
Fetched info for NINT.TO
Fetched info for NOA.TO
Fetched info for NPI.TO
Fetched info for NPK.TO
Fetched info for NPRF.TO
Fetched info for NPS.TO
Fetched info for NREA.TO
Fetched info for NRGY.TO
Fetched info for NSCB.TO
Fetched info for NSCC.TO
Fetched info for NSCE.TO
Fetched info for NSGE.TO
Fetched info for NSSB.TO
Fetched info for NTR.TO
Fetched info for NUAG.TO
Fetched info for NUBF.TO
Fetched info for NUMI.TO
Fetched info for NUSA.TO
Fetched info for NVA.TO
Fetched info for NVDH.TO
Fetched info for NVHE.TO
Fetched info for NVO.TO
Fetched info for NWC.TO
Fetched info for NXE.TO
Fetched info for NXF.TO
Fetched info for NXTG.TO
Fetched info for OBE.TO
Fetched info for OGC.TO
Fetched info for OGD.TO
Fetched info for OGI.TO
Fetched info for OLA.TO
Fetched info for OLY.TO
Fetched info for ONC.TO
Fetched info for ONEB.TO
Fetched info for ONEC.TO
Fetched info for ONEQ.TO
Fetched info for ONEX.TO
Fetched info for OPT.TO
Fetched info for OR.TO
Fetched info for ORA.TO
Fetched info for ORE.TO
Fetched info for ORV.TO
Fetched info for OTEX.TO
Fetched info for OVV.TO
Fetched info for PAAS.TO
Fetched info for PABF.TO
Fetched info for PACF.TO
Fetched info for PAGF.TO
Fetched info for PAY.TO
Fetched info for PAYF.TO
Fetched info for PAYL.TO
Fetched info for PAYM.TO
Fetched info for PAYS.TO
Fetched info for PBD.TO
Fetched info for PBH.TO
Fetched info for PBI.TO
Fetched info for PBL.TO
Fetched info for PCOR.TO
Fetched info for PD.TO
Fetched info for PDC.TO
Fetched info for PDF.TO
Fetched info for PDIV.TO
Fetched info for PDN.TO
Fetched info for PDV.TO
Fetched info for PEA.TO
Fetched info for PET.TO
Fetched info for PEY.TO
Fetched info for PFAA.TO
Fetched info for PFAE.TO
Fetched info for PFCB.TO
Fetched info for PFIA.TO
Fetched info for PFL.TO
Fetched info for PFLS.TO
Fetched info for PFMN.TO
Fetched info for PFSS.TO
Fetched info for PGIC.TO
Fetched info for PHR.TO
Fetched info for PHX.TO
Fetched info for PHYS.TO
Fetched info for PID.TO
Fetched info for PIF.TO
Fetched info for PIN.TO
Fetched info for PINC.TO
Fetched info for PKI.TO
Fetched info for PLDI.TO
Fetched info for PLV.TO
Fetched info for PME.TO
Fetched info for PMET.TO
Fetched info for PMIF.TO
Fetched info for PMM.TO
Fetched info for PMNT.TO
Fetched info for PNE.TO
Fetched info for PNP.TO
Fetched info for POU.TO
Fetched info for POW.TO
Fetched info for PPL.TO
Fetched info for PPLN.TO
Fetched info for PPR.TO
Fetched info for PPTA.TO
Fetched info for PR.TO
Fetched info for PRA.TO
Fetched info for PRB.TO
Fetched info for PREF.TO
Fetched info for PRL.TO
Fetched info for PRM.TO
Fetched info for PRN.TO
Fetched info for PRQ.TO
Fetched info for PRU.TO
Fetched info for PRYM.TO
Fetched info for PSA.TO
Fetched info for PSB.TO
Fetched info for PSD.TO
Fetched info for PSI.TO
Fetched info for PSK.TO
Fetched info for PSLV.TO
Fetched info for PTM.TO
Fetched info for PWI.TO
Fetched info for PXC.TO
Fetched info for PXS.TO
Fetched info for PXT.TO
Fetched info for PYF.TO
Fetched info for PYR.TO
Fetched info for PZA.TO
Fetched info for PZW.TO
Fetched info for QAH.TO
Fetched info for QASH.TO
Fetched info for QBB.TO
Fetched info for QBTC.TO
Fetched info for QBTL.TO
Fetched info for QCE.TO
Fetched info for QCLN.TO
Fetched info for QCN.TO
Fetched info for QDX.TO
Fetched info for QDXB.TO
Fetched info for QDXH.TO
Fetched info for QEBH.TO
Fetched info for QEBL.TO
Fetched info for QEC.TO
Fetched info for QEE.TO
Fetched info for QHY.TO
Fetched info for QIE.TO
Fetched info for QINF.TO
Fetched info for QIPT.TO
Fetched info for QLB.TO
Fetched info for QMAX.TO
Fetched info for QQC.TO
Fetched info for QQCC.TO
Fetched info for QQCE.TO
Fetched info for QQCI.TO
Fetched info for QQCL.TO
Fetched info for QQEQ.TO
Fetched info for QQJE.TO
Fetched info for QQJR.TO
Fetched info for QQQL.TO
Fetched info for QQQT.TO
Fetched info for QQQX.TO
Fetched info for QQQY.TO
Fetched info for QRC.TO
Fetched info for QRET.TO
Fetched info for QSB.TO
Fetched info for QSR.TO
Fetched info for QTLT.TO
Fetched info for QTRH.TO
Fetched info for QUB.TO
Fetched info for QUIG.TO
Fetched info for QUS.TO
Fetched info for QUU.TO
Fetched info for QXM.TO
Fetched info for RAAA.TO
Fetched info for RATE.TO
Fetched info for RBA.TO
Fetched info for RBNK.TO
Fetched info for RBO.TO
Fetched info for RBOT.TO
Fetched info for RBY.TO
Fetched info for RCD.TO
Fetched info for RCDC.TO
Fetched info for RCG.TO
Fetched info for RCH.TO
Fetched info for RDBH.TO
Fetched info for REAL.TO
Fetched info for RGQN.TO
Fetched info for RGQO.TO
Fetched info for RGQP.TO
Fetched info for RGQQ.TO
Fetched info for RGQR.TO
Fetched info for RGQS.TO
Fetched info for RID.TO
Fetched info for RIDH.TO
Fetched info for RIFI.TO
Fetched info for RIIN.TO
Fetched info for RING.TO
Fetched info for RIRA.TO
Fetched info for RIT.TO
Fetched info for RLB.TO
Fetched info for RMAX.TO
Fetched info for ROOT.TO
Fetched info for RPD.TO
Fetched info for RPDH.TO
Fetched info for RPF.TO
Fetched info for RPSB.TO
Fetched info for RQN.TO
Fetched info for RQO.TO
Fetched info for RQP.TO
Fetched info for RQQ.TO
Fetched info for RQR.TO
Fetched info for RQS.TO
Fetched info for RS.TO
Fetched info for RSI.TO
Fetched info for RTG.TO
Fetched info for RUBH.TO
Fetched info for RUBY.TO
Fetched info for RUD.TO
Fetched info for RUDB.TO
Fetched info for RUDC.TO
Fetched info for RUDH.TO
Fetched info for RUP.TO
Fetched info for RUQN.TO
Fetched info for RUQO.TO
Fetched info for RUQQ.TO
Fetched info for RUQR.TO
Fetched info for RUQS.TO
Fetched info for RUS.TO
Fetched info for RUSB.TO
Fetched info for RVX.TO
Fetched info for RXD.TO
Fetched info for RY.TO
Fetched info for S.TO
Fetched info for SAFE.TO
Fetched info for SAM.TO
Fetched info for SAP.TO
Fetched info for SAU.TO
Fetched info for SBC.TO
Fetched info for SBI.TO
Fetched info for SBT.TO
Fetched info for SCR.TO
Fetched info for SCY.TO
Fetched info for SDE.TO
Fetched info for SEA.TO
Fetched info for SEC.TO
Fetched info for SES.TO
Fetched info for SFC.TO
Fetched info for SFD.TO
Fetched info for SFI.TO
Fetched info for SFTC.TO
Fetched info for SGLD.TO
Fetched info for SGY.TO
Fetched info for SHLE.TO
Fetched info for SHOP.TO
Fetched info for SIA.TO
Fetched info for SII.TO
Fetched info for SIL.TO
Fetched info for SIS.TO
Fetched info for SJ.TO
Fetched info for SKE.TO
Fetched info for SKYY.TO
Fetched info for SLF.TO
Fetched info for SLR.TO
Fetched info for SLS.TO
Fetched info for SMAX.TO
Fetched info for SMC.TO
Fetched info for SMT.TO
Fetched info for SOBO.TO
Fetched info for SOIL.TO
Fetched info for SOLG.TO
Fetched info for SOY.TO
Fetched info for SPAY.TO
Fetched info for SPB.TO
Fetched info for SPFD.TO
Fetched info for SPLT.TO
Fetched info for SPPP.TO
Fetched info for SSL.TO
Fetched info for SSRM.TO
Fetched info for STC.TO
Fetched info for STCK.TO
Fetched info for STEP.TO
Fetched info for STGO.TO
Fetched info for STLR.TO
Fetched info for STN.TO
Fetched info for STPL.TO
Fetched info for SU.TO
Fetched info for SVA.TO
Fetched info for SVB.TO
Fetched info for SVI.TO
Fetched info for SVM.TO
Fetched info for SVR.TO
Fetched info for SWP.TO
Fetched info for SXI.TO
Fetched info for SXP.TO
Fetched info for SYLD.TO
Fetched info for SYZ.TO
Fetched info for T.TO
Fetched info for TA.TO
Fetched info for TAL.TO
Fetched info for TBAL.TO
Fetched info for TBCE.TO
Fetched info for TBCF.TO
Fetched info for TBCG.TO
Fetched info for TBIL.TO
Fetched info for TBL.TO
Fetched info for TBNK.TO
Fetched info for TC.TO
Fetched info for TCBN.TO
Fetched info for TCLB.TO
Fetched info for TCLV.TO
Fetched info for TCON.TO
Fetched info for TCS.TO
Fetched info for TCSB.TO
Fetched info for TCSH.TO
Fetched info for TCW.TO
Fetched info for TD.TO
Fetched info for TDB.TO
Fetched info for TDOC.TO
Fetched info for TEC.TO
Fetched info for TECH.TO
Fetched info for TECI.TO
Fetched info for TECX.TO
Fetched info for TERM.TO
Fetched info for TF.TO
Fetched info for TFII.TO
Fetched info for TFPM.TO
Fetched info for TGAF.TO
Fetched info for TGED.TO
Fetched info for TGFI.TO
Fetched info for TGGR.TO
Fetched info for TGO.TO
Fetched info for TGRE.TO
Fetched info for TGRO.TO
Fetched info for TH.TO
Fetched info for The.TO
Fetched info for THNC.TO
Fetched info for THU.TO
Fetched info for TI.TO
Fetched info for TIH.TO
Fetched info for TILV.TO
Fetched info for TINF.TO
Fetched info for TIPS.TO
Fetched info for TIXT.TO
Fetched info for TKN.TO
Fetched info for TKO.TO
Fetched info for TLF.TO
Fetched info for TLG.TO
Fetched info for TLO.TO
Fetched info for TLRY.TO
Fetched info for TLV.TO
Fetched info for TMQ.TO
Fetched info for TNZ.TO
Fetched info for TOT.TO
Fetched info for TOU.TO
Fetched info for TOWR.TO
Fetched info for TOY.TO
Fetched info for TPE.TO
Fetched info for TPRF.TO
Fetched info for TPU.TO
Fetched info for TPZ.TO
Fetched info for TQCD.TO
Fetched info for TQGD.TO
Fetched info for TQGM.TO
Fetched info for TQSM.TO
Fetched info for TRI.TO
Fetched info for TRP.TO
Fetched info for TRVI.TO
Fetched info for TRVL.TO
Fetched info for TRX.TO
Fetched info for TRZ.TO
Fetched info for TSAT.TO
Fetched info for TSK.TO
Fetched info for TSL.TO
Fetched info for TSND.TO
Fetched info for TSU.TO
Fetched info for TTNM.TO
Fetched info for TTP.TO
Fetched info for TTTX.TO
Fetched info for TUED.TO
Fetched info for TUEX.TO
Fetched info for TUHY.TO
Fetched info for TULB.TO
Fetched info for TULV.TO
Fetched info for TUSB.TO
Fetched info for TVE.TO
Fetched info for TVK.TO
Fetched info for TWC.TO
Fetched info for TWM.TO
Fetched info for TXF.TO
Fetched info for TXG.TO
Fetched info for TXP.TO
Fetched info for UDA.TO
Fetched info for UDIV.TO
Fetched info for UMAX.TO
Fetched info for UMI.TO
Fetched info for UNC.TO
Fetched info for UNI.TO
Fetched info for URB.TO
Fetched info for URC.TO
Fetched info for URE.TO
Fetched info for USA.TO
Fetched info for USCC.TO
Fetched info for USCL.TO
Fetched info for USSL.TO
Fetched info for USSX.TO
Fetched info for UTES.TO
Fetched info for UTIL.TO
Fetched info for VA.TO
Fetched info for VAB.TO
Fetched info for VALT.TO
Fetched info for VBAL.TO
Fetched info for VBNK.TO
Fetched info for VCB.TO
Fetched info for VCE.TO
Fetched info for VCIP.TO
Fetched info for VCM.TO
Fetched info for VCN.TO
Fetched info for VCNS.TO
Fetched info for VDU.TO
Fetched info for VDY.TO
Fetched info for VE.TO
Fetched info for VEE.TO
Fetched info for VEF.TO
Fetched info for VEQT.TO
Fetched info for VET.TO
Fetched info for VFV.TO
Fetched info for VGG.TO
Fetched info for VGH.TO
Fetched info for VGRO.TO
Fetched info for VGV.TO
Fetched info for VGZ.TO
Fetched info for VHI.TO
Fetched info for VI.TO
Fetched info for VIDY.TO
Fetched info for VIU.TO
Fetched info for VLB.TO
Fetched info for VLE.TO
Fetched info for VLN.TO
Fetched info for VMO.TO
Fetched info for VNP.TO
Fetched info for VOXR.TO
Fetched info for VQS.TO
Fetched info for VRE.TO
Fetched info for VRIF.TO
Fetched info for VRN.TO
Fetched info for VRTS.TO
Fetched info for VSB.TO
Fetched info for VSC.TO
Fetched info for VSP.TO
Fetched info for VUN.TO
Fetched info for VUS.TO
Fetched info for VVL.TO
Fetched info for VVO.TO
Fetched info for VVSG.TO
Fetched info for VXC.TO
Fetched info for VXM.TO
Fetched info for VZLA.TO
Fetched info for WCN.TO
Fetched info for WCP.TO
Fetched info for WDO.TO
Fetched info for WEED.TO
Fetched info for WEF.TO
Fetched info for WELL.TO
Fetched info for WFC.TO
Fetched info for WFG.TO
Fetched info for WGX.TO
Fetched info for WILD.TO
Fetched info for WJX.TO
Fetched info for WLLW.TO
Fetched info for WM.TO
Fetched info for WN.TO
Fetched info for WNDR.TO
Fetched info for WOMN.TO
Fetched info for WPK.TO
Fetched info for WPM.TO
Fetched info for WPRT.TO
Fetched info for WRG.TO
Fetched info for WRN.TO
Fetched info for WRX.TO
Fetched info for WSP.TO
Fetched info for WSRD.TO
Fetched info for WSRI.TO
Fetched info for WTE.TO
Fetched info for WXM.TO
Fetched info for X.TO
Fetched info for XAD.TO
Fetched info for XAGG.TO
Fetched info for XAGH.TO
Fetched info for XAM.TO
Fetched info for XAU.TO
Fetched info for XAW.TO
Fetched info for XBAL.TO
Fetched info for XBB.TO
Fetched info for XBM.TO
Fetched info for XCB.TO
Fetched info for XCBG.TO
Fetched info for XCBU.TO
Fetched info for XCD.TO
Fetched info for XCG.TO
Fetched info for XCH.TO
Fetched info for XCHP.TO
Fetched info for XCLN.TO
Fetched info for XCNS.TO
Fetched info for XCS.TO
Fetched info for XCSR.TO
Fetched info for XCV.TO
Fetched info for XDG.TO
Fetched info for XDGH.TO
Fetched info for XDIV.TO
Fetched info for XDNA.TO
Fetched info for XDRV.TO
Fetched info for XDSR.TO
Fetched info for XDU.TO
Fetched info for XDUH.TO
Fetched info for XDV.TO
Fetched info for XEB.TO
Fetched info for XEC.TO
Fetched info for XEF.TO
Fetched info for XEG.TO
Fetched info for XEH.TO
Fetched info for XEI.TO
Fetched info for XEM.TO
Fetched info for XEMC.TO
Fetched info for XEN.TO
Fetched info for XEQT.TO
Fetched info for XESG.TO
Fetched info for XETM.TO
Fetched info for XEU.TO
Fetched info for XEXP.TO
Fetched info for XFH.TO
Fetched info for XFLB.TO
Fetched info for XFLI.TO
Fetched info for XFLX.TO
Fetched info for XFN.TO
Fetched info for XFR.TO
Fetched info for XGB.TO
Fetched info for XGD.TO
Fetched info for XGI.TO
Fetched info for XGRO.TO
Fetched info for XHAK.TO
Fetched info for XHB.TO
Fetched info for XHC.TO
Fetched info for XHD.TO
Fetched info for XHU.TO
Fetched info for XHY.TO
Fetched info for XIC.TO
Fetched info for XID.TO
Fetched info for XIG.TO
Fetched info for XIGS.TO
Fetched info for XIN.TO
Fetched info for XINC.TO
Fetched info for XIT.TO
Fetched info for XIU.TO
Fetched info for XLB.TO
Fetched info for XLY.TO
Fetched info for XMA.TO
Fetched info for XMC.TO
Fetched info for XMD.TO
Fetched info for XMH.TO
Fetched info for XMI.TO
Fetched info for XML.TO
Fetched info for XMM.TO
Fetched info for XMS.TO
Fetched info for XMTM.TO
Fetched info for XMU.TO
Fetched info for XMV.TO
Fetched info for XMW.TO
Fetched info for XMY.TO
Fetched info for XPF.TO
Fetched info for XQB.TO
Fetched info for XQLT.TO
Fetched info for XQQ.TO
Fetched info for XQQU.TO
Fetched info for XRB.TO
Fetched info for XRE.TO
Fetched info for XSAB.TO
Fetched info for XSB.TO
Fetched info for XSC.TO
Fetched info for XSE.TO
Fetched info for XSEA.TO
Fetched info for XSEM.TO
Fetched info for XSH.TO
Fetched info for XSHG.TO
Fetched info for XSHU.TO
Fetched info for XSI.TO
Fetched info for XSMC.TO
Fetched info for XSMH.TO
Fetched info for XSP.TO
Fetched info for XSPC.TO
Fetched info for XST.TO
Fetched info for XSTB.TO
Fetched info for XSTH.TO
Fetched info for XSTP.TO
Fetched info for XSU.TO
Fetched info for XSUS.TO
Fetched info for XTC.TO
Fetched info for XTD.TO
Fetched info for XTG.TO
Fetched info for XTLH.TO
Fetched info for XTLT.TO
Fetched info for XTR.TO
Fetched info for XTRA.TO
Fetched info for XUH.TO
Fetched info for XUS.TO
Fetched info for XUSC.TO
Fetched info for XUSF.TO
Fetched info for XUSR.TO
Fetched info for XUT.TO
Fetched info for XUU.TO
Fetched info for XVLU.TO
Fetched info for XWD.TO
Fetched info for Y.TO
Fetched info for YCM.TO
Fetched info for YGR.TO
Fetched info for YRB.TO
Fetched info for ZACE.TO
Fetched info for ZAG.TO
Fetched info for ZBAL.TO
Fetched info for ZBBB.TO
Fetched info for ZBI.TO
Fetched info for ZBK.TO
Fetched info for ZCB.TO
Fetched info for ZCDB.TO
Fetched info for ZCH.TO
Fetched info for ZCLN.TO
Fetched info for ZCM.TO
Fetched info for ZCN.TO
Fetched info for ZCON.TO
Fetched info for ZCPB.TO
Fetched info for ZCS.TO
Fetched info for ZDB.TO
Fetched info for ZDH.TO
Fetched info for ZDI.TO
Fetched info for ZDJ.TO
Fetched info for ZDM.TO
Fetched info for ZDV.TO
Fetched info for ZDY.TO
Fetched info for ZEA.TO
Fetched info for ZEAT.TO
Fetched info for ZEB.TO
Fetched info for ZEF.TO
Fetched info for ZEM.TO
Fetched info for ZEO.TO
Fetched info for ZEQ.TO
Fetched info for ZEQT.TO
Fetched info for ZESG.TO
Fetched info for ZFC.TO
Fetched info for ZFH.TO
Fetched info for ZFL.TO
Fetched info for ZFM.TO
Fetched info for ZFN.TO
Fetched info for ZFS.TO
Fetched info for ZGB.TO
Fetched info for ZGD.TO
Fetched info for ZGI.TO
Fetched info for ZGLD.TO
Fetched info for ZGLH.TO
Fetched info for ZGQ.TO
Fetched info for ZGRN.TO
Fetched info for ZGRO.TO
Fetched info for ZGSB.TO
Fetched info for ZHP.TO
Fetched info for ZHU.TO
Fetched info for ZHY.TO
Fetched info for ZIC.TO
Fetched info for ZID.TO
Fetched info for ZIN.TO
Fetched info for ZIQ.TO
Fetched info for ZIU.TO
Fetched info for ZJG.TO
Fetched info for ZJK.TO
Fetched info for ZJPN.TO
Fetched info for ZLB.TO
Fetched info for ZLC.TO
Fetched info for ZLD.TO
Fetched info for ZLE.TO
Fetched info for ZLH.TO
Fetched info for ZLI.TO
Fetched info for ZLSC.TO
Fetched info for ZLSU.TO
Fetched info for ZLU.TO
Fetched info for ZMBS.TO
Fetched info for ZMI.TO
Fetched info for ZMID.TO
Fetched info for ZMMK.TO
Fetched info for ZMP.TO
Fetched info for ZMSB.TO
Fetched info for ZMT.TO
Fetched info for ZMU.TO
Fetched info for ZNQ.TO
Fetched info for ZPAY.TO
Fetched info for ZPH.TO
Fetched info for ZPL.TO
Fetched info for ZPR.TO
Fetched info for ZPS.TO
Fetched info for ZPW.TO
Fetched info for ZQB.TO
Fetched info for ZQQ.TO
Fetched info for ZRE.TO
Fetched info for ZRR.TO
Fetched info for ZSB.TO
Fetched info for ZSDB.TO
Fetched info for ZSML.TO
Fetched info for ZSP.TO
Fetched info for ZST.TO
Fetched info for ZSU.TO
Fetched info for ZTIP.TO
Fetched info for ZUAG.TO
Fetched info for ZUB.TO
Fetched info for ZUCM.TO
Fetched info for ZUD.TO
Fetched info for ZUE.TO
Fetched info for ZUGE.TO
Fetched info for ZUH.TO
Fetched info for ZUP.TO
Fetched info for ZUQ.TO
Fetched info for ZUT.TO
Fetched info for ZVC.TO
Fetched info for ZVU.TO
Fetched info for ZWA.TO
Fetched info for ZWB.TO
Fetched info for ZWC.TO
Fetched info for ZWE.TO
Fetched info for ZWEN.TO
Fetched info for ZWG.TO
Fetched info for ZWH.TO
Fetched info for ZWHC.TO
Fetched info for ZWK.TO
Fetched info for ZWP.TO
Fetched info for ZWQT.TO
Fetched info for ZWS.TO
Fetched info for ZWT.TO
Fetched info for ZWU.TO
Fetched info for ZXM.TO
Fetched info for ZZZD.TO

In [ ]:
tickers_info_df

,address1,city,state,zip,country,phone,fax,website,industry,industryKey,...,navPrice,ytdReturn,fundFamily,fundInceptionDate,legalType,yield,threeYearAverageReturn,fiveYearAverageReturn,irWebsite,beta3Year
0,198 Davenport Road,Toronto,ON,M5R 1J2,Canada,416 861 5882,416 861 8165,https://www.aberdeen.green,Asset Management,asset-management,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"North Tower, Royal Bank Plaza",Toronto,ON,M5J 2J3,Canada,NaN,NaN,https://alliedgold.com,Gold,gold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Millennium Tower,Calgary,AB,T2P 5E9,Canada,403 718 8000,403 718 8332,https://www.advantageog.com,Oil & Gas E&P,oil-gas-e-p,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Brookfield Place, TD Canada Trust Tower",Toronto,ON,M5J 2S1,Canada,416 861 9911,NaN,https://www.barrick.com,Gold,gold,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7373 COte-Vertu Boulevard West,Saint-Laurent,QC,NaN,Canada,NaN,NaN,https://www.aircanada.com,Airlines,airlines,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,NaN,NaN,NaN,NaN,NaN,+1 8003611392,NaN,NaN,NaN,NaN,...,20.36416,0.008412,BMO Asset Management Inc,1.519862e+09,Exchange Traded Fund,0.0534,0.025391,0.062181,NaN,0.81
1632,NaN,NaN,NaN,NaN,NaN,+1 8003611392,NaN,NaN,NaN,NaN,...,52.94526,0.006265,BMO Asset Management Inc,1.611619e+09,Exchange Traded Fund,0.0334,0.219085,NaN,NaN,1.40
1633,NaN,NaN,NaN,NaN,NaN,+1 8003611392,NaN,NaN,NaN,NaN,...,10.44929,-0.010427,BMO Asset Management Inc,1.319069e+09,Exchange Traded Fund,0.0797,0.008859,0.017905,NaN,0.63
1634,NaN,NaN,NaN,NaN,NaN,+1 416 3622929,NaN,NaN,NaN,NaN,...,42.61740,-0.000117,CI Investments Inc,1.415837e+09,Exchange Traded Fund,0.0297,0.050808,0.094018,NaN,0.90
1635,NaN,NaN,NaN,NaN,NaN,1-800-668-7327,NaN,NaN,NaN,NaN,...,28.18158,0.004651,BMO Investments Inc.,1.447632e+09,Exchange Traded Fund,0.0430,0.041152,0.014513,NaN,0.65

In [ ]:
tickers_info_df.to_csv('TSX Ticker Info.csv', index=False)

In [ ]:
tickers_info_df = pd.read_csv('TSX Ticker Info.csv')

Find and confirm duplicate columns

In [ ]:
(tickers_info_df['industry'] == tickers_info_df['industryDisp']).all()

False

In [ ]:
filtered_tickers_industry_info = tickers_info_df[
    (tickers_info_df['industry'] != tickers_info_df['industryDisp']) &
    tickers_info_df['industry'].notna() &
    tickers_info_df['industryDisp'].notna()
]
print(filtered_tickers_industry_info['industry'])
print(filtered_tickers_industry_info['industryDisp'])

502     Beverages - Non-Alcoholic
591     Beverages - Non-Alcoholic
1171    Beverages - Non-Alcoholic
Name: industry, dtype: object
502     Beverages - Non - Alcoholic
591     Beverages - Non - Alcoholic
1171    Beverages - Non - Alcoholic
Name: industryDisp, dtype: object

In [ ]:
(tickers_info_df['symbol'] == tickers_info_df['underlyingSymbol']).all()

False

In [ ]:
filtered_tickers_industry_info = tickers_info_df[
    (tickers_info_df['symbol'] != tickers_info_df['underlyingSymbol']) &
    tickers_info_df['symbol'].notna() &
    tickers_info_df['underlyingSymbol'].notna()
]
print(filtered_tickers_industry_info['symbol'])
print(filtered_tickers_industry_info['underlyingSymbol'])
print(filtered_tickers_industry_info['longName'])

843      MGB.TO
884     MUSA.TO
1209    TCLB.TO
1217     TDB.TO
Name: symbol, dtype: object
843      MG-B.TO
884     MUS-A.TO
1209    TCL-B.TO
1217     T-DB.TO
Name: underlyingSymbol, dtype: object
843     Mackenzie Core Plus Global Fixed Income ETF
884              Middlefield US Equity Dividend ETF
1209         TD Canadian Long Term Federal Bond ETF
1217           TD Canadian Aggregate Bond Index ETF
Name: longName, dtype: object

Remove unwanted columns from ticker info DF

In [ ]:
tickers_info_df = pd.read_csv('TSX Ticker Info.csv')

In [ ]:
tickers_info_df = tickers_info_df.drop(errors='ignore', columns=['address1', 'address2', 'city', 'state', 'zip', 'country', 'phone', 'fax', 'website', 'industryKey', 'industryDisp', 'sectorKey', 'sectorDisp', 'companyOfficers', 'maxAge', 'previousClose', 'open', 'dayLow', 'dayHigh', 'regularMarketPreviousClose', 'regularMarketOpen', 'regularMarketDayLow', 'regularMarketDayHigh', 'exDividendDate', 'volume', 'averageVolume10days', 'averageDailyVolume10Day', 'bid', 'ask', 'irWebsite', 'fundInceptionDate', 'governanceEpochDate', 'fullTimeEmployees', 'currentPrice', 'gmtOffSetMilliseconds', 'messageBoardId', 'uuid', 'timeZoneShortName', 'timeZoneFullName', 'firstTradeDateEpochUtc', 'underlyingSymbol', 'exchange', 'lastDividendDate', 'lastSplitDate', 'nextFiscalYearEnd', 'lastFiscalYearEnd', 'mostRecentQuarter', 'sharesShortPreviousMonthDate', 'dateShortInterest', 'compensationAsOfEpochDate'])

In [ ]:
tickers_info_df

,industry,sector,longBusinessSummary,priceHint,beta,regularMarketVolume,averageVolume,marketCap,fiftyTwoWeekLow,fiftyTwoWeekHigh,...,earningsGrowth,totalAssets,navPrice,ytdReturn,fundFamily,legalType,yield,threeYearAverageReturn,fiveYearAverageReturn,beta3Year
0,Asset Management,Financial Services,"Aberdeen International Inc., a resource invest...",4.0,1.824,3597.0,387819.0,6.367480e+06,0.02,0.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Gold,Basic Materials,"Allied Gold Corporation, together with its sub...",4.0,NaN,115702.0,610130.0,1.105064e+09,2.69,4.50,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Oil & Gas E&P,Energy,"Advantage Energy Ltd., together with its subsi...",2.0,1.445,257238.0,440509.0,1.636326e+09,8.24,11.73,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Gold,Basic Materials,Barrick Gold Corporation engages in the explor...,2.0,0.480,606469.0,3595311.0,3.990798e+10,18.65,29.50,...,0.315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Airlines,Industrials,"Air Canada provides domestic, U.S. transborder...",2.0,2.407,1672227.0,3851196.0,7.177030e+09,14.47,26.18,...,0.743,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631,NaN,NaN,NaN,2.0,NaN,1415.0,2954.0,NaN,19.29,21.70,...,NaN,1.295231e+08,20.36416,0.008412,BMO Asset Management Inc,Exchange Traded Fund,0.0534,0.025391,0.062181,0.81
1632,NaN,NaN,NaN,2.0,NaN,1415.0,6568.0,NaN,38.21,54.54,...,NaN,1.766196e+08,52.94526,0.006265,BMO Asset Management Inc,Exchange Traded Fund,0.0334,0.219085,NaN,1.40
1633,NaN,NaN,NaN,2.0,NaN,122568.0,235435.0,NaN,9.67,11.42,...,NaN,1.804342e+09,10.44929,-0.010427,BMO Asset Management Inc,Exchange Traded Fund,0.0797,0.008859,0.017905,0.63
1634,NaN,NaN,NaN,2.0,NaN,200.0,227.0,NaN,37.24,43.55,...,NaN,5.533632e+07,42.61740,-0.000117,CI Investments Inc,Exchange Traded Fund,0.0297,0.050808,0.094018,0.90
1635,NaN,NaN,NaN,2.0,NaN,300.0,409.0,NaN,27.40,29.63,...,NaN,1.549907e+08,28.18158,0.004651,BMO Investments Inc.,Exchange Traded Fund,0.0430,0.041152,0.014513,0.65

In [ ]:
tickers_info_df.to_csv('TSX Ticker Info.csv', index=False)

In [ ]:
tickers_info_df = pd.read_csv('TSX Ticker Info.csv')

In [ ]:
tickers_chart_df = pd.read_csv('TSX Chart Data.csv')

In [ ]:
tickers_chart_df.head(10)

         date     close  high   low  open  volume     tic  day
0  2004-01-02  0.489625  0.53  0.53  0.53       0  AAB.TO    4
1  2004-01-05  0.489625  0.53  0.53  0.53       0  AAB.TO    0
2  2004-01-06  0.258670  0.28  0.28  0.28     100  AAB.TO    1
3  2004-01-07  0.489625  0.53  0.53  0.53       0  AAB.TO    2
4  2004-01-08  0.489625  0.53  0.53  0.53       0  AAB.TO    3
5  2004-01-09  0.489625  0.53  0.53  0.53       0  AAB.TO    4
6  2004-01-12  0.489625  0.53  0.53  0.53       0  AAB.TO    0
7  2004-01-13  0.489625  0.53  0.53  0.53       0  AAB.TO    1
8  2004-01-14  0.489625  0.53  0.53  0.53       0  AAB.TO    2
9  2004-01-15  0.489625  0.53  0.53  0.53       0  AAB.TO    3

In [ ]:
merged_df = tickers_chart_df.merge(tickers_info_df, left_on='tic', right_on='symbol', how='left')
merged_df.head()

,date,close,high,low,open,volume,tic,day,industry,sector,...,earningsGrowth,totalAssets,navPrice,ytdReturn,fundFamily,legalType,yield,threeYearAverageReturn,fiveYearAverageReturn,beta3Year
0,2004-01-02,0.489625,0.53,0.53,0.53,0,AAB.TO,4,Asset Management,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2004-01-05,0.489625,0.53,0.53,0.53,0,AAB.TO,0,Asset Management,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2004-01-06,0.258670,0.28,0.28,0.28,100,AAB.TO,1,Asset Management,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004-01-07,0.489625,0.53,0.53,0.53,0,AAB.TO,2,Asset Management,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2004-01-08,0.489625,0.53,0.53,0.53,0,AAB.TO,3,Asset Management,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sorted_df = merged_df.sort_values(by=['date', 'tic'], ascending=[True, True])
sorted_df.head()

,date,close,high,low,open,volume,tic,day,industry,sector,...,earningsGrowth,totalAssets,navPrice,ytdReturn,fundFamily,legalType,yield,threeYearAverageReturn,fiveYearAverageReturn,beta3Year
958764,2004-01-01,0.105000,0.105,0.105,0.105,0,DYA.TO,3,Specialty Industrial Machinery,Industrials,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
991346,2004-01-01,1.378000,2.650,2.650,2.650,0,EDT.TO,3,Diagnostics & Research,Healthcare,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,2004-01-02,0.489625,0.530,0.530,0.530,0,AAB.TO,4,Asset Management,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9401,2004-01-02,22.070272,29.850,29.320,29.430,413000,ABX.TO,4,Gold,Basic Materials,...,0.315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20556,2004-01-02,3.484277,7.050,7.050,7.050,100,ACD.TO,4,Credit Services,Financial Services,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
sorted_df= sorted_df.drop(columns=['longBusinessSummary'])

In [ ]:
sorted_df.to_csv('TSX Merged.csv', index=False)