In [24]:
# ## install finrl library
!pip install wrds
!pip install swig
!apt-get update -y -qq && apt-get install -y -qq cmake libopenmpi-dev python3-dev zlib1g-dev libgl1-mesa-glx swig
!pip install finrl

Requirement already satisfied: wrds in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (3.2.0)
Requirement already satisfied: numpy<1.27,>=1.26 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (1.26.4)
Requirement already satisfied: packaging<23.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (23.2)
Requirement already satisfied: pandas<2.3,>=2.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (2.2.3)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (2.9.10)
Requirement already satisfied: scipy<1.13,>=1.12 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (1.12.0)
Requirement already satisfied: sqlalchemy<2.1,>=2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (2.0.37)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\email\appdata\roaming\python\python311\site-packages (from pandas<2.3,>=2.2->wrds) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pandas<2.3,>=2.2->wrds) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pandas<2.3,>=2.2->wrds) (2025.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy<2.1,>=2->wrds) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\email\appdata\roaming\python\python311\site-packages (from sqlalchemy<2.1,>=2->wrds) (4.12.2)
Requirement already satisfied: six>=1.5 in c:\users\email\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: swig in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (4.3.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

Requirement already satisfied: finrl in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (0.3.6)
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to c:\users\email\appdata\local\temp\pip-install-xgwcz0ci\elegantrl_28833741bfa74ba1bc8de086d9d69126
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 3bdc958c8e624b61a9e661832b01fef816924f61
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: alpaca-py<0.38,>=0.37 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (0.37.0)
Requirement already satisfied: alpaca-trade-api<4,>=3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (3.2.0)
Requirement already satisfied: ccxt<4,>=3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (3.1.60)
Requirement already satisfied: exchange-calendars<5,>=4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (4.9)
Requirement already satisfied: jqdatasdk<2,>=1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (1.9.7)
Requirement already satisfied: pyfolio<0.10,>=0.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (0.9.2)
Requirement already satisfied: pyportfolioopt<2,>=1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (1.5.6)
Requirement already satisfied: ray<3,>=2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (2.42.0)
Requirement already satisfied: scikit-learn<2,>=1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (1.6.1)
Requirement already satisfied: selenium<5,>=4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (4.28.1)
Requirement already satisfied: stable-baselines3>=2.0.0a5 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (2.6.0a0)
Requirement already satisfied: stockstats<0.6,>=0.5 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (0.5.4)
Requirement already satisfied: webdriver-manager<5,>=4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (4.0.2)
Requirement already satisfied: wrds<4,>=3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (3.2.0)
Requirement already satisfied: yfinance<0.3,>=0.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (0.2.52)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (1.0.3)
Requirement already satisfied: pandas>=1.5.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (2.2.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (2.10.6)
Requirement already satisfied: requests<3.0.0,>=2.30.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (2.32.3)
Requirement already satisfied: sseclient-py<2.0.0,>=1.7.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (1.8.0)
Requirement already satisfied: websockets>=10.4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (10.4)
Requirement already satisfied: numpy>=1.11.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (1.26.4)
Requirement already satisfied: urllib3<2,>1.24 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (1.8.0)
Requirement already satisfied: aiohttp<4,>=3.8.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (3.11.11)
Requirement already satisfied: PyYAML==6.0.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (2.1.0)
Requirement already satisfied: packaging in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl) (23.2)
Requirement already satisfied: setuptools>=60.9.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (65.5.0)
Requirement already satisfied: certifi>=2018.1.18 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (2025.1.31)
Requirement already satisfied: cryptography>=2.6.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (44.0.0)
Requirement already satisfied: aiodns>=1.1.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (3.2.0)
Requirement already satisfied: yarl>=1.7.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (1.18.3)
Requirement already satisfied: pyluach in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from exchange-calendars<5,>=4->finrl) (2.2.0)
Requirement already satisfied: toolz in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from exchange-calendars<5,>=4->finrl) (1.0.0)
Requirement already satisfied: tzdata in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from exchange-calendars<5,>=4->finrl) (2025.1)
Requirement already satisfied: korean_lunar_calendar in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from exchange-calendars<5,>=4->finrl) (0.3.1)
Requirement already satisfied: six in c:\users\email\appdata\roaming\python\python311\site-packages (from jqdatasdk<2,>=1->finrl) (1.17.0)
Requirement already satisfied: SQLAlchemy>=1.2.8 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from jqdatasdk<2,>=1->finrl) (2.0.37)
Requirement already satisfied: pymysql>=0.7.6 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from jqdatasdk<2,>=1->finrl) (1.1.1)
Requirement already satisfied: thriftpy2<=0.4.20,>=0.3.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from jqdatasdk<2,>=1->finrl) (0.4.20)
Requirement already satisfied: ipython>=3.2.3 in c:\users\email\appdata\roaming\python\python311\site-packages (from pyfolio<0.10,>=0.9->finrl) (8.32.0)
Requirement already satisfied: matplotlib>=1.4.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (3.10.0)
Requirement already satisfied: pytz>=2014.10 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (2025.1)
Requirement already satisfied: scipy>=0.14.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (1.12.0)
Requirement already satisfied: seaborn>=0.7.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (0.13.2)
Requirement already satisfied: empyrical>=0.5.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (0.5.5)
Requirement already satisfied: cvxpy>=1.1.19 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyportfolioopt<2,>=1->finrl) (1.6.0)
Requirement already satisfied: ecos<3.0.0,>=2.0.14 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyportfolioopt<2,>=1->finrl) (2.0.14)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyportfolioopt<2,>=1->finrl) (5.24.1)
Requirement already satisfied: click>=7.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (8.1.8)
Requirement already satisfied: filelock in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (3.17.0)
Requirement already satisfied: jsonschema in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (4.23.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (5.29.3)
Requirement already satisfied: aiosignal in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (1.3.2)
Requirement already satisfied: frozenlist in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (1.5.0)
Requirement already satisfied: aiohttp_cors in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.7.0)
Requirement already satisfied: colorful in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.5.6)
Requirement already satisfied: py-spy>=0.2.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.4.0)
Requirement already satisfied: grpcio>=1.42.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (1.70.0)
Requirement already satisfied: opencensus in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.11.4)
Requirement already satisfied: prometheus_client>=0.7.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.21.1)
Requirement already satisfied: smart_open in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (7.1.0)
Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (20.29.1)
Requirement already satisfied: tensorboardX>=1.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (2.6.2.2)
Requirement already satisfied: pyarrow>=9.0.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (19.0.0)
Requirement already satisfied: fsspec in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (2025.2.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2,>=1->finrl) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2,>=1->finrl) (3.5.0)
Requirement already satisfied: trio~=0.17 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from selenium<5,>=4->finrl) (0.28.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from selenium<5,>=4->finrl) (0.11.1)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\email\appdata\roaming\python\python311\site-packages (from selenium<5,>=4->finrl) (4.12.2)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl) (1.0.0)
Requirement already satisfied: torch<3.0,>=2.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl) (2.6.0)
Requirement already satisfied: cloudpickle in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl) (3.1.1)
Requirement already satisfied: opencv-python in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (4.11.0.86)
Requirement already satisfied: pygame in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (2.6.1)
Requirement already satisfied: tensorboard>=2.9.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (2.18.0)
Requirement already satisfied: psutil in c:\users\email\appdata\roaming\python\python311\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (6.1.1)
Requirement already satisfied: tqdm in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (4.67.1)
Requirement already satisfied: rich in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (13.9.4)
Requirement already satisfied: ale-py>=0.9.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (0.10.1)
Requirement already satisfied: pillow in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (11.1.0)
Requirement already satisfied: python-dotenv in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from webdriver-manager<5,>=4->finrl) (1.0.1)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds<4,>=3->finrl) (2.9.10)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\email\appdata\roaming\python\python311\site-packages (from yfinance<0.3,>=0.2->finrl) (4.3.6)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (4.13.3)
Requirement already satisfied: html5lib>=1.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (1.1)
Requirement already satisfied: th in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl) (0.4.1)
Requirement already satisfied: pycares>=4.0.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiodns>=1.1.1->ccxt<4,>=3->finrl) (4.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl) (2.4.4)
Requirement already satisfied: attrs>=17.3.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl) (25.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl) (0.2.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance<0.3,>=0.2->finrl) (2.6)
Requirement already satisfied: colorama in c:\users\email\appdata\roaming\python\python311\site-packages (from click>=7.0->ray<3,>=2->ray[default,tune]<3,>=2->finrl) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from cryptography>=2.6.1->ccxt<4,>=3->finrl) (1.17.1)
Requirement already satisfied: osqp>=0.6.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl) (0.6.7.post3)
Requirement already satisfied: clarabel>=0.5.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl) (0.10.0)
Requirement already satisfied: scs>=3.2.4.post1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl) (3.2.7.post2)
Requirement already satisfied: pandas-datareader>=0.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from empyrical>=0.5.0->pyfolio<0.10,>=0.9->finrl) (0.10.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl) (0.0.4)
Requirement already satisfied: webencodings in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from html5lib>=1.1->yfinance<0.3,>=0.2->finrl) (0.5.1)
Requirement already satisfied: decorator in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (2.19.1)
Requirement already satisfied: stack_data in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (5.14.3)

  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git 'C:\Users\email\AppData\Local\Temp\pip-install-xgwcz0ci\elegantrl_28833741bfa74ba1bc8de086d9d69126'

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import warnings
warnings.filterwarnings("ignore")

In [26]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# matplotlib.use('Agg')
import datetime

import gym
from finrl import config
from finrl.agents.stablebaselines3.models import DRLEnsembleAgent
from finrl.meta.preprocessor.preprocessors import FeatureEngineer

from pprint import pprint

import sys
sys.path.append("../FinRL-Library")

import itertools

In [27]:
import os
from finrl.main import check_and_make_directories
from finrl.config import (
    DATA_SAVE_DIR,
    TRAINED_MODEL_DIR,
    TENSORBOARD_LOG_DIR,
    RESULTS_DIR,
    INDICATORS,
    TRAIN_START_DATE,
    TRAIN_END_DATE,
    TEST_START_DATE,
    TEST_END_DATE,
    TRADE_START_DATE,
    TRADE_END_DATE,
)

import os
if not os.path.exists("./" + config.DATA_SAVE_DIR):
    os.makedirs("./" + config.DATA_SAVE_DIR)
if not os.path.exists("./" + config.TRAINED_MODEL_DIR):
    os.makedirs("./" + config.TRAINED_MODEL_DIR)
if not os.path.exists("./" + config.TENSORBOARD_LOG_DIR):
    os.makedirs("./" + config.TENSORBOARD_LOG_DIR)
if not os.path.exists("./" + config.RESULTS_DIR):
    os.makedirs("./" + config.RESULTS_DIR)

In [28]:
TRAIN_START_DATE = '2017-01-01'
TRAIN_END_DATE = '2021-10-01'
TEST_START_DATE = '2021-10-01'
TEST_END_DATE = '2023-03-01'

In [29]:
df = pd.read_csv("C:\\Users\\email\\Downloads\\historical_data.csv")

In [30]:
#Data Exploration
print("First 5 rows of the dataset:")
print(df.head())

First 5 rows of the dataset:
         date      close       high        low       open  volume     tic  day
0  2004-01-01   0.105000   0.105000   0.105000   0.105000       0  DYA.TO    3
1  2004-01-01   1.378000   1.378000   1.378000   1.378000       0  EDT.TO    3
2  2004-01-01   0.300000   0.300000   0.300000   0.300000       0  TSK.TO    3
3  2004-01-02   0.489625   0.489625   0.489625   0.489625       0  AAB.TO    4
4  2004-01-02  22.070263  22.211644  21.817266  21.899118  413000  ABX.TO    4

In [31]:
print(df.isnull().sum())  # Shows the count of missing values per column

date      0
close     0
high      0
low       0
open      0
volume    0
tic       0
day       0
dtype: int64

In [32]:
# Convert 'date' column to datetime if it is not already
df['date'] = pd.to_datetime(df['date']) 

# *Step 1: Data Cleaning*
df = df.sort_values(["date", "tic"], ignore_index=True)

# Factorize the date index
df.index = df.date.factorize()[0]
df

,date,close,high,low,open,volume,tic,day
0,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3
0,2004-01-01,1.378000,1.378000,1.378000,1.378000,0,EDT.TO,3
0,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3
1,2004-01-02,0.489625,0.489625,0.489625,0.489625,0,AAB.TO,4
1,2004-01-02,22.070263,22.211644,21.817266,21.899118,413000,ABX.TO,4
...,...,...,...,...,...,...,...,...
5280,2024-12-30,20.230000,20.309999,20.150000,20.309999,700,ZWS.TO,0
5280,2024-12-30,53.099998,53.360001,52.830002,53.299999,11600,ZWT.TO,0
5280,2024-12-30,10.510000,10.520000,10.430000,10.500000,168700,ZWU.TO,0
5280,2024-12-30,42.599998,42.610001,42.599998,42.610001,300,ZXM.TO,0
5280,2024-12-30,27.700001,27.700001,27.700001,27.700001,1700,ZZZD.TO,0

In [33]:

# Drop rows where any of the required columns have NaN values
df = df.dropna(subset=["close", "high", "low", "open", "tic", "day"])

# *Step 3: Add User Defined Features*
df["daily_return"] = df.close.pct_change(1)

In [34]:
df.head()

,date,close,high,low,open,volume,tic,day,daily_return
0,2004-01-01,0.105000,0.105000,0.105000,0.105000,0,DYA.TO,3,NaN
0,2004-01-01,1.378000,1.378000,1.378000,1.378000,0,EDT.TO,3,12.123810
0,2004-01-01,0.300000,0.300000,0.300000,0.300000,0,TSK.TO,3,-0.782293
1,2004-01-02,0.489625,0.489625,0.489625,0.489625,0,AAB.TO,4,0.632084
1,2004-01-02,22.070263,22.211644,21.817266,21.899118,413000,ABX.TO,4,44.075824

In [35]:
INDICATORS = ['macd',
               'rsi_30',
               'cci_30',
               'dx_30']

In [36]:
#TICKERS = ["RY.TO", "TD.TO", "BNS.TO", "ENB.TO", "SHOP.TO"]  # Example TSX tickers

In [37]:
#df = df[df['tic'].isin(TICKERS)]
df.shape

(4066965, 9)

In [38]:
feature_engineer = FeatureEngineer(use_technical_indicator=True, tech_indicator_list=INDICATORS)

In [39]:
df = feature_engineer.add_technical_indicator(df)

In [40]:
df = feature_engineer.add_turbulence(df)

In [41]:
df["date"] = pd.to_datetime(df["date"])  # Convert main dataset date column

In [ ]:
stock_dimension = len(df.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 1631, State Space: 9787

In [43]:
env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "buy_cost_pct": 0.001,
    "sell_cost_pct": 0.001,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4,
    "print_verbosity":5

}

In [44]:
rebalance_window = 63 # rebalance_window is the number of days to retrain the model
validation_window = 63 # validation_window is the number of days to do validation and trading (e.g. if validation_window=63, then both validation and trading period will be 63 days)

ensemble_agent = DRLEnsembleAgent(df,
                 train_period=(TRAIN_START_DATE,TRAIN_END_DATE),
                 val_test_period=(TEST_START_DATE,TEST_END_DATE),
                 rebalance_window=rebalance_window,
                 validation_window=validation_window,
                 **env_kwargs)

In [45]:


DDPG_model_kwargs = {
                      #"action_noise":"ornstein_uhlenbeck",
                      "buffer_size": 10_000,
                      "learning_rate": 0.0005,
                      "batch_size": 64
                    }

TD3_model_kwargs = {"batch_size": 100, "buffer_size": 1000000, "learning_rate": 0.0001}




timesteps_dict = {'a2c' : 0,
                 'ppo' : 0,
                 'ddpg' : 10_000,
                 'sac' : 0,
                 'td3' : 0
                 }

In [46]:
df_summary = ensemble_agent.run_ensemble_strategy(
    A2C_model_kwargs={},  # Not using A2C
    PPO_model_kwargs={},  # Not using PPO
    DDPG_model_kwargs=DDPG_model_kwargs,  # Using DDPG
    SAC_model_kwargs={},  # Not using SAC
    TD3_model_kwargs={},  # Not using TD3
    timesteps_dict=timesteps_dict
)

============Start Ensemble Strategy============
============================================
turbulence_threshold:  5051557442.335041
======Model training from:  2017-01-01 to  2021-10-04 00:00:00
======a2c Training========
{}
Using cpu device

ValueError: could not broadcast input array from shape (5737,) into shape (9787,)

In [47]:
df_summary

NameError: name 'df_summary' is not defined

In [ ]:
processed=df

In [ ]:
unique_trade_date = processed[(processed.date > TEST_START_DATE)&(processed.date <= TEST_END_DATE)].date.unique()

In [ ]:
import pandas as pd

df_account_value = pd.DataFrame()

for i in range(rebalance_window + validation_window, len(unique_trade_date) + 1, rebalance_window):
    temp = pd.read_csv('results/account_value_trade_{}_{}.csv'.format('ensemble', i))
    
    # Fix: Use pd.concat() instead of .append()
    df_account_value = pd.concat([df_account_value, temp], ignore_index=True)

# Compute Sharpe Ratio
sharpe = (252 ** 0.5) * df_account_value.account_value.pct_change(1).mean() / df_account_value.account_value.pct_change(1).std()
print('Sharpe Ratio:', sharpe)

# Fix any potential DataFrame joining issues
df_account_value = df_account_value.merge(df_trade_date[validation_window:].reset_index(drop=True), left_index=True, right_index=True, how='left')

In [ ]:
df_account_value.head()

In [ ]:
from finrl.plot import backtest_stats, backtest_plot, get_daily_return, get_baseline
print("==============Get Backtest Results===========")
now = datetime.datetime.now().strftime('%Y%m%d-%Hh%M')

perf_stats_all = backtest_stats(account_value=df_account_value)
perf_stats_all = pd.DataFrame(perf_stats_all)

In [ ]:
#baseline stats
print("==============Get Baseline Stats===========")
df_dji_ = get_baseline(
        ticker="RY.TO",
        start = df_account_value.loc[0,'date'],
        end = df_account_value.loc[len(df_account_value)-1,'date'])

stats = backtest_stats(df_dji_, value_col_name = 'close')