In [23]:
# ## install finrl library
!pip install wrds
!pip install swig
!apt-get update -y -qq && apt-get install -y -qq cmake libopenmpi-dev python3-dev zlib1g-dev libgl1-mesa-glx swig
!pip install finrl

Requirement already satisfied: wrds in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (3.2.0)
Requirement already satisfied: numpy<1.27,>=1.26 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (1.26.4)
Requirement already satisfied: packaging<23.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (23.2)
Requirement already satisfied: pandas<2.3,>=2.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (2.2.3)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (2.9.10)
Requirement already satisfied: scipy<1.13,>=1.12 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (1.12.0)
Requirement already satisfied: sqlalchemy<2.1,>=2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds) (2.0.37)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\email\appdata\roaming\python\python311\site-packages (from pandas<2.3,>=2.2->wrds) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pandas<2.3,>=2.2->wrds) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pandas<2.3,>=2.2->wrds) (2025.1)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy<2.1,>=2->wrds) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\email\appdata\roaming\python\python311\site-packages (from sqlalchemy<2.1,>=2->wrds) (4.12.2)
Requirement already satisfied: six>=1.5 in c:\users\email\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas<2.3,>=2.2->wrds) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: swig in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (4.3.0)

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

Requirement already satisfied: finrl in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (0.3.6)
Collecting elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git (from finrl)
  Cloning https://github.com/AI4Finance-Foundation/ElegantRL.git to c:\users\email\appdata\local\temp\pip-install-vllwjs6i\elegantrl_fb6b188736fb4510a07c482f6db75e14
  Resolved https://github.com/AI4Finance-Foundation/ElegantRL.git to commit 62bf617fa87cf82b9fbf88307715d93b8ab8ee80
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: alpaca-py<0.38,>=0.37 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (0.37.0)
Requirement already satisfied: alpaca-trade-api<4,>=3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (3.2.0)
Requirement already satisfied: ccxt<4,>=3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (3.1.60)
Requirement already satisfied: exchange-calendars<5,>=4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (4.9)
Requirement already satisfied: jqdatasdk<2,>=1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (1.9.7)
Requirement already satisfied: pyfolio<0.10,>=0.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (0.9.2)
Requirement already satisfied: pyportfolioopt<2,>=1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (1.5.6)
Requirement already satisfied: ray<3,>=2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (2.42.0)
Requirement already satisfied: scikit-learn<2,>=1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (1.6.1)
Requirement already satisfied: selenium<5,>=4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (4.28.1)
Requirement already satisfied: stable-baselines3>=2.0.0a5 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (2.6.0a0)
Requirement already satisfied: stockstats<0.6,>=0.5 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (0.5.4)
Requirement already satisfied: webdriver-manager<5,>=4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (4.0.2)
Requirement already satisfied: wrds<4,>=3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (3.2.0)
Requirement already satisfied: yfinance<0.3,>=0.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from finrl) (0.2.52)
Requirement already satisfied: msgpack<2.0.0,>=1.0.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (1.0.3)
Requirement already satisfied: pandas>=1.5.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (2.2.3)
Requirement already satisfied: pydantic<3.0.0,>=2.0.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (2.10.6)
Requirement already satisfied: requests<3.0.0,>=2.30.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (2.32.3)
Requirement already satisfied: sseclient-py<2.0.0,>=1.7.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (1.8.0)
Requirement already satisfied: websockets>=10.4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-py<0.38,>=0.37->finrl) (10.4)
Requirement already satisfied: numpy>=1.11.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (1.26.4)
Requirement already satisfied: urllib3<2,>1.24 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (1.26.20)
Requirement already satisfied: websocket-client<2,>=0.56.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (1.8.0)
Requirement already satisfied: aiohttp<4,>=3.8.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (3.11.11)
Requirement already satisfied: PyYAML==6.0.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (6.0.1)
Requirement already satisfied: deprecation==2.1.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from alpaca-trade-api<4,>=3->finrl) (2.1.0)
Requirement already satisfied: packaging in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from deprecation==2.1.0->alpaca-trade-api<4,>=3->finrl) (23.2)
Requirement already satisfied: setuptools>=60.9.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (65.5.0)
Requirement already satisfied: certifi>=2018.1.18 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (2025.1.31)
Requirement already satisfied: cryptography>=2.6.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (44.0.0)
Requirement already satisfied: aiodns>=1.1.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (3.2.0)
Requirement already satisfied: yarl>=1.7.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ccxt<4,>=3->finrl) (1.18.3)
Requirement already satisfied: pyluach in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from exchange-calendars<5,>=4->finrl) (2.2.0)
Requirement already satisfied: toolz in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from exchange-calendars<5,>=4->finrl) (1.0.0)
Requirement already satisfied: tzdata in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from exchange-calendars<5,>=4->finrl) (2025.1)
Requirement already satisfied: korean_lunar_calendar in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from exchange-calendars<5,>=4->finrl) (0.3.1)
Requirement already satisfied: six in c:\users\email\appdata\roaming\python\python311\site-packages (from jqdatasdk<2,>=1->finrl) (1.17.0)
Requirement already satisfied: SQLAlchemy>=1.2.8 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from jqdatasdk<2,>=1->finrl) (2.0.37)
Requirement already satisfied: pymysql>=0.7.6 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from jqdatasdk<2,>=1->finrl) (1.1.1)
Requirement already satisfied: thriftpy2<=0.4.20,>=0.3.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from jqdatasdk<2,>=1->finrl) (0.4.20)
Requirement already satisfied: ipython>=3.2.3 in c:\users\email\appdata\roaming\python\python311\site-packages (from pyfolio<0.10,>=0.9->finrl) (8.32.0)
Requirement already satisfied: matplotlib>=1.4.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (3.10.0)
Requirement already satisfied: pytz>=2014.10 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (2025.1)
Requirement already satisfied: scipy>=0.14.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (1.12.0)
Requirement already satisfied: seaborn>=0.7.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (0.13.2)
Requirement already satisfied: empyrical>=0.5.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyfolio<0.10,>=0.9->finrl) (0.5.5)
Requirement already satisfied: cvxpy>=1.1.19 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyportfolioopt<2,>=1->finrl) (1.6.0)
Requirement already satisfied: ecos<3.0.0,>=2.0.14 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyportfolioopt<2,>=1->finrl) (2.0.14)
Requirement already satisfied: plotly<6.0.0,>=5.0.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from pyportfolioopt<2,>=1->finrl) (5.24.1)
Requirement already satisfied: click>=7.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (8.1.8)
Requirement already satisfied: filelock in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (3.17.0)
Requirement already satisfied: jsonschema in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (4.23.0)
Requirement already satisfied: protobuf!=3.19.5,>=3.15.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (5.29.3)
Requirement already satisfied: aiosignal in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (1.3.2)
Requirement already satisfied: frozenlist in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray<3,>=2->ray[default,tune]<3,>=2->finrl) (1.5.0)
Requirement already satisfied: aiohttp_cors in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.7.0)
Requirement already satisfied: colorful in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.5.6)
Requirement already satisfied: py-spy>=0.2.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.4.0)
Requirement already satisfied: grpcio>=1.42.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (1.70.0)
Requirement already satisfied: opencensus in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.11.4)
Requirement already satisfied: prometheus_client>=0.7.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (0.21.1)
Requirement already satisfied: smart_open in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (7.1.0)
Requirement already satisfied: virtualenv!=20.21.1,>=20.0.24 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (20.29.1)
Requirement already satisfied: tensorboardX>=1.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (2.6.2.2)
Requirement already satisfied: pyarrow>=9.0.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (19.0.0)
Requirement already satisfied: fsspec in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from ray[default,tune]<3,>=2->finrl) (2025.2.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2,>=1->finrl) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn<2,>=1->finrl) (3.5.0)
Requirement already satisfied: trio~=0.17 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from selenium<5,>=4->finrl) (0.28.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from selenium<5,>=4->finrl) (0.11.1)
Requirement already satisfied: typing_extensions~=4.9 in c:\users\email\appdata\roaming\python\python311\site-packages (from selenium<5,>=4->finrl) (4.12.2)
Requirement already satisfied: gymnasium<1.1.0,>=0.29.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl) (1.0.0)
Requirement already satisfied: torch<3.0,>=2.3 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl) (2.6.0)
Requirement already satisfied: cloudpickle in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl) (3.1.1)
Requirement already satisfied: opencv-python in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (4.11.0.86)
Requirement already satisfied: pygame in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (2.6.1)
Requirement already satisfied: tensorboard>=2.9.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (2.18.0)
Requirement already satisfied: psutil in c:\users\email\appdata\roaming\python\python311\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (6.1.1)
Requirement already satisfied: tqdm in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (4.67.1)
Requirement already satisfied: rich in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (13.9.4)
Requirement already satisfied: ale-py>=0.9.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (0.10.1)
Requirement already satisfied: pillow in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from stable-baselines3[extra]>=2.0.0a5->finrl) (11.1.0)
Requirement already satisfied: python-dotenv in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from webdriver-manager<5,>=4->finrl) (1.0.1)
Requirement already satisfied: psycopg2-binary<2.10,>=2.9 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from wrds<4,>=3->finrl) (2.9.10)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (5.3.0)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\email\appdata\roaming\python\python311\site-packages (from yfinance<0.3,>=0.2->finrl) (4.3.6)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (4.13.3)
Requirement already satisfied: html5lib>=1.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from yfinance<0.3,>=0.2->finrl) (1.1)
Requirement already satisfied: th in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from elegantrl@ git+https://github.com/AI4Finance-Foundation/ElegantRL.git->finrl) (0.4.1)
Requirement already satisfied: pycares>=4.0.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiodns>=1.1.1->ccxt<4,>=3->finrl) (4.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl) (2.4.4)
Requirement already satisfied: attrs>=17.3.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl) (25.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from aiohttp<4,>=3.8.3->alpaca-trade-api<4,>=3->finrl) (0.2.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance<0.3,>=0.2->finrl) (2.6)
Requirement already satisfied: colorama in c:\users\email\appdata\roaming\python\python311\site-packages (from click>=7.0->ray<3,>=2->ray[default,tune]<3,>=2->finrl) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from cryptography>=2.6.1->ccxt<4,>=3->finrl) (1.17.1)
Requirement already satisfied: osqp>=0.6.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl) (0.6.7.post3)
Requirement already satisfied: clarabel>=0.5.0 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl) (0.10.0)
Requirement already satisfied: scs>=3.2.4.post1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from cvxpy>=1.1.19->pyportfolioopt<2,>=1->finrl) (3.2.7.post2)
Requirement already satisfied: pandas-datareader>=0.2 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from empyrical>=0.5.0->pyfolio<0.10,>=0.9->finrl) (0.10.0)
Requirement already satisfied: farama-notifications>=0.0.1 in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from gymnasium<1.1.0,>=0.29.1->stable-baselines3>=2.0.0a5->stable-baselines3[extra]>=2.0.0a5->finrl) (0.0.4)
Requirement already satisfied: webencodings in c:\users\email\appdata\local\programs\python\python311\lib\site-packages (from html5lib>=1.1->yfinance<0.3,>=0.2->finrl) (0.5.1)
Requirement already satisfied: decorator in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (2.19.1)
Requirement already satisfied: stack_data in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (0.6.3)
Requirement already satisfied: traitlets>=5.13.0 in c:\users\email\appdata\roaming\python\python311\site-packages (from ipython>=3.2.3->pyfolio<0.10,>=0.9->finrl) (5.14.3)

  Running command git clone --filter=blob:none --quiet https://github.com/AI4Finance-Foundation/ElegantRL.git 'C:\Users\email\AppData\Local\Temp\pip-install-vllwjs6i\elegantrl_fb6b188736fb4510a07c482f6db75e14'

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import warnings
warnings.filterwarnings("ignore")

In [25]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
# matplotlib.use('Agg')
import datetime

import gym
from finrl import config
from finrl.agents.stablebaselines3.models import DRLEnsembleAgent
from finrl.meta.preprocessor.preprocessors import FeatureEngineer

from pprint import pprint

import sys
sys.path.append("../FinRL-Library")

import itertools

In [26]:
import os
from finrl.main import check_and_make_directories
from finrl.config import (
    DATA_SAVE_DIR,
    TRAINED_MODEL_DIR,
    TENSORBOARD_LOG_DIR,
    RESULTS_DIR,
    INDICATORS,
    TRAIN_START_DATE,
    TRAIN_END_DATE,
    TEST_START_DATE,
    TEST_END_DATE,
    TRADE_START_DATE,
    TRADE_END_DATE,
)

import os
if not os.path.exists("./" + config.DATA_SAVE_DIR):
    os.makedirs("./" + config.DATA_SAVE_DIR)
if not os.path.exists("./" + config.TRAINED_MODEL_DIR):
    os.makedirs("./" + config.TRAINED_MODEL_DIR)
if not os.path.exists("./" + config.TENSORBOARD_LOG_DIR):
    os.makedirs("./" + config.TENSORBOARD_LOG_DIR)
if not os.path.exists("./" + config.RESULTS_DIR):
    os.makedirs("./" + config.RESULTS_DIR)

In [27]:
TRAIN_START_DATE = '2017-01-01'
TRAIN_END_DATE = '2021-10-01'
TEST_START_DATE = '2021-10-01'
TEST_END_DATE = '2023-03-01'

In [28]:
df = pd.read_csv("C:\\Users\\email\\Downloads\\historical_data.csv")

In [29]:
#Data Exploration
print("First 5 rows of the dataset:")
print(df.head())

First 5 rows of the dataset:
         date      close       high        low       open  volume     tic  day
0  2004-01-01   0.105000   0.105000   0.105000   0.105000       0  DYA.TO    3
1  2004-01-01   1.378000   1.378000   1.378000   1.378000       0  EDT.TO    3
2  2004-01-01   0.300000   0.300000   0.300000   0.300000       0  TSK.TO    3
3  2004-01-02   0.489625   0.489625   0.489625   0.489625       0  AAB.TO    4
4  2004-01-02  22.070263  22.211644  21.817266  21.899118  413000  ABX.TO    4

In [30]:
print(df.isnull().sum())  # Shows the count of missing values per column

date      0
close     0
high      0
low       0
open      0
volume    0
tic       0
day       0
dtype: int64

In [31]:
# Convert 'date' column to datetime if it is not already
df['date'] = pd.to_datetime(df['date']) 

# *Step 1: Data Cleaning*
df = df.sort_values(["date", "tic"], ignore_index=True)

# Factorize the date index
df.index = df.date.factorize()[0]
df

           date      close       high  ...  volume      tic  day
0    2004-01-01   0.105000   0.105000  ...       0   DYA.TO    3
0    2004-01-01   1.378000   1.378000  ...       0   EDT.TO    3
0    2004-01-01   0.300000   0.300000  ...       0   TSK.TO    3
1    2004-01-02   0.489625   0.489625  ...       0   AAB.TO    4
1    2004-01-02  22.070263  22.211644  ...  413000   ABX.TO    4
...         ...        ...        ...  ...     ...      ...  ...
5280 2024-12-30  20.230000  20.309999  ...     700   ZWS.TO    0
5280 2024-12-30  53.099998  53.360001  ...   11600   ZWT.TO    0
5280 2024-12-30  10.510000  10.520000  ...  168700   ZWU.TO    0
5280 2024-12-30  42.599998  42.610001  ...     300   ZXM.TO    0
5280 2024-12-30  27.700001  27.700001  ...    1700  ZZZD.TO    0

[4066965 rows x 8 columns]

In [32]:

# Drop rows where any of the required columns have NaN values
df = df.dropna(subset=["close", "high", "low", "open", "tic", "day"])

# *Step 3: Add User Defined Features*
df["daily_return"] = df.close.pct_change(1)

In [33]:
df.head()

        date      close       high  ...     tic  day  daily_return
0 2004-01-01   0.105000   0.105000  ...  DYA.TO    3           NaN
0 2004-01-01   1.378000   1.378000  ...  EDT.TO    3     12.123810
0 2004-01-01   0.300000   0.300000  ...  TSK.TO    3     -0.782293
1 2004-01-02   0.489625   0.489625  ...  AAB.TO    4      0.632084
1 2004-01-02  22.070263  22.211644  ...  ABX.TO    4     44.075824

[5 rows x 9 columns]

In [34]:
INDICATORS = ['macd',
               'rsi_30',
               'cci_30',
               'dx_30']

In [35]:
TICKERS = ["RY.TO", "TD.TO", "BNS.TO", "ENB.TO", "SHOP.TO"]  # Example TSX tickers

In [36]:
df = df[df['tic'].isin(TICKERS)]
df.shape

(23500, 9)

In [37]:
feature_engineer = FeatureEngineer(use_technical_indicator=True, tech_indicator_list=INDICATORS)

In [38]:
df = feature_engineer.add_technical_indicator(df)

In [39]:
df = feature_engineer.add_turbulence(df)

In [40]:
df["date"] = pd.to_datetime(df["date"])  # Convert main dataset date column

In [41]:
stock_dimension = len(df.tic.unique())
state_space = 1 + 2*stock_dimension + len(INDICATORS)*stock_dimension
print(f"Stock Dimension: {stock_dimension}, State Space: {state_space}")

Stock Dimension: 5, State Space: 31

In [42]:
env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "buy_cost_pct": 0.001,
    "sell_cost_pct": 0.001,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 1e-4,
    "print_verbosity":5

}

In [43]:
rebalance_window = 63 # rebalance_window is the number of days to retrain the model
validation_window = 63 # validation_window is the number of days to do validation and trading (e.g. if validation_window=63, then both validation and trading period will be 63 days)

ensemble_agent = DRLEnsembleAgent(df,
                 train_period=(TRAIN_START_DATE,TRAIN_END_DATE),
                 val_test_period=(TEST_START_DATE,TEST_END_DATE),
                 rebalance_window=rebalance_window,
                 validation_window=validation_window,
                 **env_kwargs)

In [44]:


DDPG_model_kwargs = {
                      #"action_noise":"ornstein_uhlenbeck",
                      "buffer_size": 10_000,
                      "learning_rate": 0.0005,
                      "batch_size": 64
                    }

TD3_model_kwargs = {"batch_size": 100, "buffer_size": 1000000, "learning_rate": 0.0001}




timesteps_dict = {'a2c' : 0,
                 'ppo' : 0,
                 'ddpg' : 10_000,
                 'sac' : 0,
                 'td3' : 0
                 }

In [45]:
df_summary = ensemble_agent.run_ensemble_strategy(
    A2C_model_kwargs={},  # Not using A2C
    PPO_model_kwargs={},  # Not using PPO
    DDPG_model_kwargs=DDPG_model_kwargs,  # Using DDPG
    SAC_model_kwargs={},  # Not using SAC
    TD3_model_kwargs={},  # Not using TD3
    timesteps_dict=timesteps_dict
)

============Start Ensemble Strategy============
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2021-10-04 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_126_7
======a2c Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
a2c Sharpe Ratio:  -0.2228293066189291
======ddpg Training========
{'buffer_size': 10000, 'learning_rate': 0.0005, 'batch_size': 64}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_126_6
day: 1192, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 4880368.29
total_reward: 3880368.29
total_cost: 998.99
total_trades: 2384
Sharpe: 1.141
=================================
-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 110        |
|    time_elapsed    | 43         |
|    total_timesteps | 4772       |
| train/             |            |
|    actor_loss      | 3.7e+03    |
|    critic_loss     | 2.06e+03   |
|    learning_rate   | 0.0005     |
|    n_updates       | 4671       |
|    reward          | -2.6399457 |
-----------------------------------
-----------------------------------
| time/              |            |
|    episodes        | 8          |
|    fps             | 98         |
|    time_elapsed    | 97         |
|    total_timesteps | 9544       |
| train/             |            |
|    actor_loss      | 2.3e+03    |
|    critic_loss     | 4.33e+03   |
|    learning_rate   | 0.0005     |
|    n_updates       | 9443       |
|    reward          | -2.6399457 |
-----------------------------------
======ddpg Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
ddpg Sharpe Ratio:  -0.21830661770064846
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_126_6
======td3 Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
td3 Sharpe Ratio:  0.2806153914090799
======sac Training========
{}
Using cpu device
Logging to tensorboard_log/sac\sac_126_5
======sac Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
sac Sharpe Ratio:  0.4332003592290155
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_126_5
======ppo Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
ppo Sharpe Ratio:  -0.28216664214422144
======Best Model Retraining from:  2017-01-01 to  2022-01-05 00:00:00
======Trading from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2022-01-05 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_189_5
======a2c Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
a2c Sharpe Ratio:  -0.2644470865623524
======ddpg Training========
{'buffer_size': 10000, 'learning_rate': 0.0005, 'batch_size': 64}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_189_5
day: 1255, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 2816540.42
total_reward: 1816540.42
total_cost: 999.00
total_trades: 5020
Sharpe: 0.983
=================================
-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 123        |
|    time_elapsed    | 40         |
|    total_timesteps | 5024       |
| train/             |            |
|    actor_loss      | 579        |
|    critic_loss     | 3.85e+03   |
|    learning_rate   | 0.0005     |
|    n_updates       | 4923       |
|    reward          | -12.838872 |
-----------------------------------
======ddpg Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
ddpg Sharpe Ratio:  -0.15921532249998843
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_189_5
======td3 Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
td3 Sharpe Ratio:  -0.08384672808633874
======sac Training========
{}
Using cpu device
Logging to tensorboard_log/sac\sac_189_5
======sac Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
sac Sharpe Ratio:  -0.06764770661721535
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_189_5
======ppo Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
ppo Sharpe Ratio:  -0.162491092224033
======Best Model Retraining from:  2017-01-01 to  2022-04-05 00:00:00
======Trading from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2022-04-05 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_252_5
======a2c Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
a2c Sharpe Ratio:  -0.41464648193444403
======ddpg Training========
{'buffer_size': 10000, 'learning_rate': 0.0005, 'batch_size': 64}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_252_5
day: 1318, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1699504.13
total_reward: 699504.13
total_cost: 998.98
total_trades: 3954
Sharpe: 0.622
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 105       |
|    time_elapsed    | 49        |
|    total_timesteps | 5276      |
| train/             |           |
|    actor_loss      | 151       |
|    critic_loss     | 30.1      |
|    learning_rate   | 0.0005    |
|    n_updates       | 5175      |
|    reward          | 1.2093456 |
----------------------------------
======ddpg Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
ddpg Sharpe Ratio:  -0.3195779355377132
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_252_5
======td3 Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
td3 Sharpe Ratio:  -0.24786083764222602
======sac Training========
{}
Using cpu device
Logging to tensorboard_log/sac\sac_252_5
======sac Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
sac Sharpe Ratio:  -0.4245881511926933
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_252_5
======ppo Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
ppo Sharpe Ratio:  -0.28382427809207317
======Best Model Retraining from:  2017-01-01 to  2022-07-06 00:00:00
======Trading from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2022-07-06 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_315_5
======a2c Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
a2c Sharpe Ratio:  0.10471580842212508
======ddpg Training========
{'buffer_size': 10000, 'learning_rate': 0.0005, 'batch_size': 64}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_315_5
day: 1381, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1558873.40
total_reward: 558873.40
total_cost: 998.98
total_trades: 4143
Sharpe: 0.522
=================================
------------------------------------
| time/              |             |
|    episodes        | 4           |
|    fps             | 126         |
|    time_elapsed    | 43          |
|    total_timesteps | 5528        |
| train/             |             |
|    actor_loss      | -95.2       |
|    critic_loss     | 3.99        |
|    learning_rate   | 0.0005      |
|    n_updates       | 5427        |
|    reward          | -0.93142164 |
------------------------------------
======ddpg Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
ddpg Sharpe Ratio:  -0.0023508393144482174
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_315_5
======td3 Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
td3 Sharpe Ratio:  -0.0007252034526768607
======sac Training========
{}
Using cpu device
Logging to tensorboard_log/sac\sac_315_5
======sac Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
sac Sharpe Ratio:  0.007748831827899057
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_315_5
======ppo Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
ppo Sharpe Ratio:  0.16318563145328654
======Best Model Retraining from:  2017-01-01 to  2022-10-05 00:00:00
======Trading from:  2022-10-05 00:00:00 to  2023-01-06 00:00:00
Ensemble Strategy took:  6.189294719696045  minutes

In [46]:
df_summary

  Iter            Val Start  ... SAC Sharpe TD3 Sharpe
0  126  2021-10-04 00:00:00  ...     0.4332   0.280615
1  189  2022-01-05 00:00:00  ...  -0.067648  -0.083847
2  252  2022-04-05 00:00:00  ...  -0.424588  -0.247861
3  315  2022-07-06 00:00:00  ...   0.007749  -0.000725

[4 rows x 9 columns]

In [47]:
DDPG_model_kwargs_tuning = {
    "learning_rate": 0.0005,
    "buffer_size": 50000,
    "batch_size": 128,
    "learning_starts": 500,
    "tau": 0.005,
    "gamma": 0.99,
    "train_freq": (1, "step"),
    "gradient_steps": 1
}

In [48]:
df_summary_tuning = ensemble_agent.run_ensemble_strategy(
    A2C_model_kwargs={},  # Not using A2C
    PPO_model_kwargs={},  # Not using PPO
    DDPG_model_kwargs=DDPG_model_kwargs_tuning,  # Using DDPG
    SAC_model_kwargs={},  # Not using SAC
    TD3_model_kwargs={},  # Not using TD3
    timesteps_dict=timesteps_dict
)

============Start Ensemble Strategy============
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2021-10-04 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_126_8
======a2c Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
a2c Sharpe Ratio:  -0.07884967224883518
======ddpg Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 128, 'learning_starts': 500, 'tau': 0.005, 'gamma': 0.99, 'train_freq': (1, 'step'), 'gradient_steps': 1}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_126_7
day: 1192, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1301450.83
total_reward: 301450.83
total_cost: 999.00
total_trades: 1192
Sharpe: 0.344
=================================
-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 126        |
|    time_elapsed    | 37         |
|    total_timesteps | 4772       |
| train/             |            |
|    actor_loss      | 250        |
|    critic_loss     | 150        |
|    learning_rate   | 0.0005     |
|    n_updates       | 4271       |
|    reward          | 0.23173736 |
-----------------------------------
-----------------------------------
| time/              |            |
|    episodes        | 8          |
|    fps             | 110        |
|    time_elapsed    | 86         |
|    total_timesteps | 9544       |
| train/             |            |
|    actor_loss      | -100       |
|    critic_loss     | 4.63e+03   |
|    learning_rate   | 0.0005     |
|    n_updates       | 9043       |
|    reward          | 0.23173736 |
-----------------------------------
======ddpg Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
ddpg Sharpe Ratio:  -0.08633288245474734
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_126_7
======td3 Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
td3 Sharpe Ratio:  -0.1478193331131521
======sac Training========
{}
Using cpu device
Logging to tensorboard_log/sac\sac_126_6
======sac Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
sac Sharpe Ratio:  -0.1268781797430462
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_126_6
======ppo Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
ppo Sharpe Ratio:  -0.050894944865339846
======Best Model Retraining from:  2017-01-01 to  2022-01-05 00:00:00
======Trading from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2022-01-05 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_189_6
======a2c Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
a2c Sharpe Ratio:  -0.12677013248272168
======ddpg Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 128, 'learning_starts': 500, 'tau': 0.005, 'gamma': 0.99, 'train_freq': (1, 'step'), 'gradient_steps': 1}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_189_6
day: 1255, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 2429466.92
total_reward: 1429466.92
total_cost: 999.00
total_trades: 6275
Sharpe: 0.945
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 103       |
|    time_elapsed    | 48        |
|    total_timesteps | 5024      |
| train/             |           |
|    actor_loss      | 1.12e+03  |
|    critic_loss     | 867       |
|    learning_rate   | 0.0005    |
|    n_updates       | 4523      |
|    reward          | -7.057088 |
----------------------------------
======ddpg Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
ddpg Sharpe Ratio:  -0.17091965313633986
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_189_6
======td3 Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
td3 Sharpe Ratio:  -0.06250945858177845
======sac Training========
{}
Using cpu device
Logging to tensorboard_log/sac\sac_189_6
======sac Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
sac Sharpe Ratio:  -0.15772107054172826
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_189_6
======ppo Validation from:  2022-01-05 00:00:00 to  2022-04-05 00:00:00
ppo Sharpe Ratio:  -0.23856632296502128
======Best Model Retraining from:  2017-01-01 to  2022-04-05 00:00:00
======Trading from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2022-04-05 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_252_6
======a2c Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
a2c Sharpe Ratio:  -0.42848999061781845
======ddpg Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 128, 'learning_starts': 500, 'tau': 0.005, 'gamma': 0.99, 'train_freq': (1, 'step'), 'gradient_steps': 1}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_252_6
day: 1318, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1821332.56
total_reward: 821332.56
total_cost: 998.98
total_trades: 3954
Sharpe: 0.691
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 109       |
|    time_elapsed    | 48        |
|    total_timesteps | 5276      |
| train/             |           |
|    actor_loss      | 1.53e+03  |
|    critic_loss     | 3.23e+04  |
|    learning_rate   | 0.0005    |
|    n_updates       | 4775      |
|    reward          | 1.8929374 |
----------------------------------
======ddpg Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
ddpg Sharpe Ratio:  -0.3425624761177433
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_252_6
======td3 Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
td3 Sharpe Ratio:  -0.27490886534427345
======sac Training========
{}
Using cpu device
Logging to tensorboard_log/sac\sac_252_6
======sac Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
sac Sharpe Ratio:  -0.37944471304258404
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_252_6
======ppo Validation from:  2022-04-05 00:00:00 to  2022-07-06 00:00:00
ppo Sharpe Ratio:  -0.19168367601787123
======Best Model Retraining from:  2017-01-01 to  2022-07-06 00:00:00
======Trading from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2022-07-06 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_315_6
======a2c Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
a2c Sharpe Ratio:  -0.23935571923640084
======ddpg Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 128, 'learning_starts': 500, 'tau': 0.005, 'gamma': 0.99, 'train_freq': (1, 'step'), 'gradient_steps': 1}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_315_6
day: 1381, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1807828.55
total_reward: 807828.55
total_cost: 999.00
total_trades: 4143
Sharpe: 0.525
=================================
----------------------------------
| time/              |           |
|    episodes        | 4         |
|    fps             | 111       |
|    time_elapsed    | 49        |
|    total_timesteps | 5528      |
| train/             |           |
|    actor_loss      | 873       |
|    critic_loss     | 92.8      |
|    learning_rate   | 0.0005    |
|    n_updates       | 5027      |
|    reward          | 3.9017649 |
----------------------------------
======ddpg Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
ddpg Sharpe Ratio:  -0.044931558659543576
======td3 Training========
{}
Using cpu device
Logging to tensorboard_log/td3\td3_315_6
======td3 Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
td3 Sharpe Ratio:  -0.02053306007535208
======sac Training========
{}
Using cpu device
Logging to tensorboard_log/sac\sac_315_6
======sac Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
sac Sharpe Ratio:  -0.1331236028691857
======ppo Training========
{}
Using cpu device
Logging to tensorboard_log/ppo\ppo_315_6
======ppo Validation from:  2022-07-06 00:00:00 to  2022-10-05 00:00:00
ppo Sharpe Ratio:  -0.04148035590160038
======Best Model Retraining from:  2017-01-01 to  2022-10-05 00:00:00
======Trading from:  2022-10-05 00:00:00 to  2023-01-06 00:00:00
Ensemble Strategy took:  6.6551187833150225  minutes

In [50]:
timesteps_dict = {'a2c' : 0,
                 'ppo' : 0,
                 'ddpg' : 200000,
                 'sac' : 0,
                 'td3' : 0
                 }

In [ ]:
df_summary_tuning = ensemble_agent.run_ensemble_strategy(
    A2C_model_kwargs={},  # Not using A2C
    PPO_model_kwargs={},  # Not using PPO
    DDPG_model_kwargs=DDPG_model_kwargs_tuning,  # Using DDPG
    SAC_model_kwargs={},  # Not using SAC
    TD3_model_kwargs={},  # Not using TD3
    timesteps_dict=timesteps_dict
)

============Start Ensemble Strategy============
============================================
turbulence_threshold:  60.18625422507017
======Model training from:  2017-01-01 to  2021-10-04 00:00:00
======a2c Training========
{}
Using cpu device
Logging to tensorboard_log/a2c\a2c_126_9
======a2c Validation from:  2021-10-04 00:00:00 to  2022-01-05 00:00:00
a2c Sharpe Ratio:  0.13500446633179955
======ddpg Training========
{'learning_rate': 0.0005, 'buffer_size': 50000, 'batch_size': 128, 'learning_starts': 500, 'tau': 0.005, 'gamma': 0.99, 'train_freq': (1, 'step'), 'gradient_steps': 1}
Using cpu device
Logging to tensorboard_log/ddpg\ddpg_126_8
day: 1192, episode: 5
begin_total_asset: 1000000.00
end_total_asset: 1470913.35
total_reward: 470913.35
total_cost: 998.98
total_trades: 3576
Sharpe: 0.511
=================================
-----------------------------------
| time/              |            |
|    episodes        | 4          |
|    fps             | 121        |
|    time_elapsed    | 39         |
|    total_timesteps | 4772       |
| train/             |            |
|    actor_loss      | 1.21e+03   |
|    critic_loss     | 1.63e+03   |
|    learning_rate   | 0.0005     |
|    n_updates       | 4271       |
|    reward          | 0.94941837 |
-----------------------------------
-----------------------------------
| time/              |            |
|    episodes        | 8          |
|    fps             | 112        |
|    time_elapsed    | 84         |
|    total_timesteps | 9544       |
| train/             |            |
|    actor_loss      | 276        |
|    critic_loss     | 7.11e+03   |
|    learning_rate   | 0.0005     |
|    n_updates       | 9043       |
|    reward          | 0.94941837 |
-----------------------------------
day: 1192, episode: 10
begin_total_asset: 1000000.00
end_total_asset: 1470913.35
total_reward: 470913.35
total_cost: 998.98
total_trades: 3576
Sharpe: 0.511
=================================
-----------------------------------
| time/              |            |
|    episodes        | 12         |
|    fps             | 109        |
|    time_elapsed    | 130        |
|    total_timesteps | 14316      |
| train/             |            |
|    actor_loss      | 72         |
|    critic_loss     | 2.81e+03   |
|    learning_rate   | 0.0005     |
|    n_updates       | 13815      |
|    reward          | 0.94941837 |
-----------------------------------
day: 1192, episode: 15
begin_total_asset: 1000000.00
end_total_asset: 1470913.35
total_reward: 470913.35
total_cost: 998.98
total_trades: 3576
Sharpe: 0.511
=================================
-----------------------------------
| time/              |            |
|    episodes        | 16         |
|    fps             | 106        |
|    time_elapsed    | 178        |
|    total_timesteps | 19088      |
| train/             |            |
|    actor_loss      | 23.7       |
|    critic_loss     | 104        |
|    learning_rate   | 0.0005     |
|    n_updates       | 18587      |
|    reward          | 0.94941837 |
-----------------------------------

In [ ]:
env_kwargs = {
    "hmax": 100,
    "initial_amount": 1000000,
    "buy_cost_pct": 0.001,
    "sell_cost_pct": 0.001,
    "state_space": state_space,
    "stock_dim": stock_dimension,
    "tech_indicator_list": INDICATORS,
    "action_space": stock_dimension,
    "reward_scaling": 5e-4,  # Increase reward sensitivity
    "print_verbosity": 5
}